client/src/org/compiere/apps/search/Find.java
The Autoreducible feature added to CComboBox prevents the user from entering data.  Until this is fixed, the underlying JComboBox can be used and will allow user edits.
=> Change to Find.java to allow saving the name of the query.  

base/src/org/compiere/model/MUserQuery.java, client/src/org/compiere/apps/ASearch.java, client/src/org/compiere/apps/search/Find.java, migration/370lts-380lts/xml/0056_AddCommentsToAdvancedFind.xml, zkwebui/WEB-INF/src/org/adempiere/webui/panel/AbstractADWindowPanel.java, zkwebui/WEB-INF/src/org/adempiere/webui/window/FindWindow.java
advising users to select or enter a name.  Added the same functionality to ZK, including the popup search menu.  Includes an xml file to add the messages.
=> Change the advanced find to include a message in the combo box

zkwebui/WEB-INF/src/org/adempiere/webui/WSearch.java
=> Add missing file WSearch.java

client/src/org/compiere/grid/ed/VButton.java
Fixed VButton to hide non active records.
P.S.
Complexity and branches kill productivity!
=> Fixed VButton to hide non active records.

zkwebui/WEB-INF/src/org/adempiere/webui/panel/AbstractADWindowPanel.java
The message returned from Process will be shown in webui statusbar just like swing client.
Ref: http://adempiere.net/forums#!/thread/42516
=> webui statusbar message is fixed

base/src/org/compiere/model/MTable.java
=> Rename sequence if table renamed.

base/src/org/compiere/model/MColumn.java
instead of sql to update related fields.
=> #202 Change MColumn.afterSave to use models 

base/src/org/compiere/process/SequenceCheck.java
Before the table ID sequence can be checked and corrected, the AD_Sequence needs to be checked and corrected. If not, errors can be created when table IDs are updated.
=> #284 The SequenceCheck fails if the the AD_Sequence is out of sequence

base/src/org/compiere/acct/FactLine.java
This pull request fixes issue #416 and allows reversed Inventory Move documents to be posted
=> #416 Bugfix Accounting FactLine updateReverseLine SQLException for InventoryMove

base/src/org/adempiere/process/MigrationLoader.java, base/src/org/compiere/process/GardenWorldCleanUp.java, migration/390lts-391/03400-1480-ChangeClassNameGardenWorldCleanup.xml
=> #1480 Change name or CleanUpGW class to GardenWorldCleanUp

org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/model/MHRMovement.java
reference to issue: https://github.com/adempiere/adempiere/issues/1581
Please merge it from pull request...
=> #1581, fixed error with bad SQL for getConceptSum and getConceptAvg,

base/src/org/compiere/util/TimeUtil.java
TimeUtil.getMonthsBetween(Timestamp, Timestamp), reference to issue:
https://github.com/adempiere/adempiere/issues/1593
Hi, please view it bugfix for merge
Best regard
=> #1593, fixed error with month diff for helper method in

base/src/org/compiere/model/MConversionRate.java
https://github.com/adempiere/adempiere/issues/1605
Please make merge for it improvement #1605
=> #1665, add helper method for Conversion Rate, reference to issue:

base/src/org/compiere/model/MCommissionRun.java
https://github.com/adempiere/adempiere/issues/1619
Hi @all it is a pull request for resolved NPE for issue: #1619 
Best Regard
=> #1619, fixed bug with NPE for reactivate commission, reference to issue:

db/ddlutils/oracle/views/RV_M_FORECAST.sql, db/ddlutils/postgresql/views/RV_M_FORECAST.sql, migration/390lts-391/03780_1620_Fixed_RV_M_Forecast_View.xml
reference to issue: https://github.com/adempiere/adempiere/issues/1620
Hi @e-Evolution @marcalwestf it pull request is for resolve a error with issue #1620
=> #1620, fixed error with SQL for get product price on view RV_M_Forecast,

client/src/org/eevolution/form/VBrowser.java, zkwebui/WEB-INF/src/org/eevolution/form/WBrowser.java
and ZK UI on load data, reference to issue:
https://github.com/adempiere/adempiere/issues/1738
It was solved with a little change, see:
=> #1738, Fixed selected by defaul ZK UI and improve performance for Swing

base/src/org/adempiere/controller/SmallViewController.java, base/src/org/adempiere/model/MBrowseField.java
to issue: https://github.com/adempiere/adempiere/issues/1735
Please see it, the issue will be closed for continue discussion here.
=> #1735, fixed display length for Smart Browser on Swing client, reference

base/src/org/adempiere/controller/SmallViewController.java, base/src/org/compiere/process/SvrProcess.java
validation before process run, reference to issue:
https://github.com/adempiere/adempiere/issues/1733
Please see it for approval
=> #1733, Fixed error with display logic for mandatory parameters and

client/src/org/compiere/apps/ProcessPanel.java, zkwebui/WEB-INF/src/org/adempiere/webui/apps/ProcessPanel.java
UI, reference to issue:
https://github.com/adempiere/adempiere/issues/1727
Please see it pull request, i added a step by step on issue #1727
=> #1727, Fixed error with dialog for fill mandatory parameters from Swing

base/src/org/compiere/apps/ProcessController.java, client/src/org/compiere/apps/ProcessModalDialog.java, zkwebui/WEB-INF/src/org/adempiere/webui/apps/ProcessDialog.java, zkwebui/WEB-INF/src/org/adempiere/webui/apps/ProcessModalDialog.java
https://github.com/adempiere/adempiere/issues/1730
Hi, i find a bug with it change, the problem is that for DocAction button it never worked
=> #1730, fixed bug introduced with issue, reference to issue:

base/src/org/adempiere/process/CreateProductEntriesInPriceList.java, base/src/org/adempiere/process/CreateProductEntriesInPriceListAbstract.java, migration/390lts-391/03760_1615_PriceListEntries.xml
A Smartbrowser to generate or edit prices in the window Pricelist
=> Price entries

base/src/org/compiere/util/PaymentExportList.java
issue: https://github.com/adempiere/adempiere/issues/1805
Hi everybody, it pull request if a little change for **PaymentexportList** class, just add a helper method.
Please review it.
Best regard
=> #1805, Add helper method for PaymentExportList class, reference to

base/src/org/adempiere/process/MigrationLoader.java, base/src/org/compiere/model/MMigration.java, base/src/org/compiere/process/MigrationFromXML.java, utils/RUN_MigrateXML.bat, utils/RUN_MigrateXML.sh
issue: https://github.com/adempiere/adempiere/issues/1635
Hi Guy, it is a bug with migration from XML, the force parameter wasn't implemented for batch process
=> #1635, Add force parameter support to import XML loader, reference to

base/src/org/adempiere/process/InvoiceGenerateFromShipment.java, base/src/org/compiere/process/InOutGenerate.java, base/src/org/compiere/process/InvoiceGenerate.java, client/src/org/adempiere/apps/form/InvoiceGenFromShipment.java, client/src/org/adempiere/apps/form/VInvoiceGenFromShipment.java, client/src/org/compiere/apps/form/FormPanel.java, client/src/org/compiere/apps/form/VInOutGen.java, client/src/org/compiere/apps/form/VInvoiceGen.java, client/src/org/eevolution/form/VInOutInvoiceGen.java
this is my next pull request trial after #1664 was declined.
@yamelsenih:
- I use now the new approch for processes :-)
- The mandatory field/parameter is set now
- you can now use multeselection
The webUI behavior is not changed - I have no webUI to test :-(
=> bugfix for #1657 "Generate Invoices from Shipments (manual)"

base/src/org/compiere/util/PaymentExportList.java
https://github.com/adempiere/adempiere/issues/1805
Hi everybody i apologize for not detect it little bug befor make pull request.
Best regard.
=> #1805, fixed bug with left and right padding, reference to issue:

migration/390lts-391/03850_1674_SyncDimensionForPhaseAndProject.xml
#1674 Enhancement synchronize account dimension for Project Phase and Project Task from Project Header  https://github.com/adempiere/adempiere/issues/1674
=> #1674 Enhancement synchronize account dimension for Project Phase and Project Task from Project Header 

org.eevolution.manufacturing/src/main/java/ui/swing/org/eevolution/form/VOrderReceiptIssue.java, org.eevolution.manufacturing/src/main/java/ui/zk/org/eevolution/form/WOrderReceiptIssue.java
#1774 Bugfix the Order Receipt Issue for Delivery Rule does not work when is selected https://github.com/adempiere/adempiere/issues/1774
=> #1774 Bugfix the Order Receipt Issue for Delivery Rule does not work when is selected https://github.com/adempiere/adempiere/issues/1774

base/src/org/compiere/util/PaymentExportList.java
PaymentExportList, reference to issue:
https://github.com/adempiere/adempiere/issues/1812
Please review it little error.
Best regard
=> #1812, Fixed error with parameter on getBPAccount metod of

base/src/org/compiere/acct/Doc_GLJournal.java, base/src/org/compiere/acct/Fact.java, base/src/org/compiere/acct/FactLine.java, base/src/org/compiere/model/MJournal.java, base/src/org/compiere/model/MJournalBatch.java
Revert #1508 commit by recommendation @adaxa-steven
=> Revert Error with Journal Multi Currency Lines #1508

client/src/org/compiere/apps/form/VGenPanel.java, client/src/org/eevolution/form/VInOutInvoiceGen.java, zkwebui/WEB-INF/src/org/adempiere/webui/apps/form/WGenForm.java
issue https://github.com/adempiere/adempiere/issues/1652
@yamelsenih 
I hope this resolvs the conflict in pull #1655
=> Bugfix #1652 : VGenPanel.generateComplete print result once

base/src/org/spin/model/MADContextInfo.java
issue: https://github.com/adempiere/adempiere/issues/1839
Add old compatibility for context info
=> #1839, Add old compatibility to Context info for window, reference to

zkwebui/WEB-INF/src/org/adempiere/webui/part/WindowContainer.java
Hi everybody, please review it, is a new functionality for close all tabs from ZK ui.
It is from https://github.com/adempiere/adempiere/issues/1711
Best regard
=> #1711 Added popup to close tabs in zk

base/src/org/compiere/util/PaymentExportList.java
https://github.com/adempiere/adempiere/issues/1823
Hi everybody, it is a little change for add helper method to Payment Export List
=> #1823, Add helper method for payment export list, reference to issue:

zkwebui/WEB-INF/src/org/adempiere/webui/panel/AbstractADWindowPanel.java
issue: https://github.com/adempiere/adempiere/issues/1354
Hi giy, please test it, in Swing UI is worked but ZK is not worked.
Now is ok.
Best regard
=> #1354, fixed error with bad zooming from Smart Browser, reference to

zkwebui/WEB-INF/src/org/adempiere/webui/apps/WProcessCtl.java
See issue https://github.com/adempiere/adempiere/issues/1113
The reports were never executed; with the change, they are.
=>  #1113 : The ZK not work jasper report included in print format.

base/src/org/compiere/model/MTable.java
is flagged as Is Document, reference to issue:
https://github.com/adempiere/adempiere/issues/1844
Please see it bug and merge.
best regard
=> #1844, Fixed missing column for automatic generate column when a table

.classpath
https://github.com/adempiere/adempiere/pull/1764
Please review it change for fix classpath of pull request https://github.com/adempiere/adempiere/pull/1764
=> improvement classpath from pull request:

build.xml
https://github.com/adempiere/adempiere/issues/1856
Please review and approve it
=> #1856, Fix permission with dmp file, reference to issue:

base/src/org/compiere/process/DocAction.java, base/src/org/compiere/wf/MWFActivity.java, base/src/org/compiere/wf/MWFNode.java, migration/390lts-391/03950_1875_Add_WF_Message.xml
https://github.com/adempiere/adempiere/issues/1875
Hi everybody this change allows translate workflow activity, all translation are:
- Node Message
- Action Message
- Error Message
- Info Message
Please review it for approval.
Best regard
=> #1875, Add Workflow activity translation, reference to issue:

base/src/org/compiere/model/MProduction.java, base/src/org/compiere/model/MProductionBatch.java
see https://github.com/adempiere/adempiere/issues/1782
prepareIt: check only if MovementDate is in the past 
by the way I added toString-Method
=> bugfix for #1782 Movement Date in MProduction

base/src/org/compiere/model/I_C_DocType.java, base/src/org/compiere/model/I_C_PaySelectionLine.java, base/src/org/compiere/model/MPaySelection.java, base/src/org/compiere/model/MPaySelectionCheck.java, base/src/org/compiere/model/X_C_DocType.java, base/src/org/compiere/model/X_C_PaySelectionLine.java, base/src/org/eevolution/process/BankTransfer.java, base/src/org/eevolution/process/BankTransferAbstract.java, migration/390lts-391/03960_1889_MultipleBankTransfer.xml
reference to issue: https://github.com/adempiere/adempiere/issues/1889
Please review it new feature for make bank transfer from payment selection.
Best regard
=> #1889, Add support for multiple bank transfer from payment selection,

migration/390lts-391/04010_1936_MigrationTableLacksSelectionRecords.xml
Added selection records version, sequence number and name.
=> #1936 Adding selection records to AD_Migration

base/src/org/compiere/model/GridField.java
Fixes: https://github.com/adempiere/adempiere/issues/1943
=> adempiere: #1943 ErrorgetDefault()ForKeyColumns

base/src/org/compiere/acct/Doc.java, base/src/org/compiere/acct/DocTax.java, base/src/org/compiere/acct/Doc_AllocationHdr.java, base/src/org/compiere/acct/Doc_Invoice.java, base/src/org/compiere/model/MAccount.java, base/src/org/compiere/model/MAcctSchema.java, base/src/org/compiere/model/MCharge.java, base/src/org/compiere/model/ProductCost.java, base/src/org/compiere/process/AcctSchemaCopyAcct.java, base/src/org/compiere/process/ImportAccount.java, base/src/org/compiere/process/InvoiceNGL.java, base/src/org/eevolution/model/I_HR_Concept_Acct.java, base/src/org/eevolution/model/X_HR_Concept_Acct.java, migration/390lts-391/03770_1604_AddPayrollForConceptAccount.xml, org.adempiere.asset/src/main/java/base/org/compiere/acct/Doc_AssetAddition.java, org.adempiere.asset/src/main/java/base/org/compiere/acct/Doc_AssetDisposed.java, org.adempiere.asset/src/main/java/base/org/compiere/acct/Doc_AssetReval.java, org.adempiere.asset/src/main/java/base/org/compiere/acct/Doc_AssetTransfer.java, org.adempiere.asset/src/main/java/base/org/compiere/acct/Doc_DepreciationEntry.java, org.eevolution.hr_and_payroll/src/main/java/base/org/compiere/acct/DocLine_Payroll.java, org.eevolution.hr_and_payroll/src/main/java/base/org/compiere/acct/Doc_HRProcess.java, org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/model/MHRConcept.java, org.eevolution.manufacturing/src/main/java/base/org/compiere/acct/DocLine_CostCollector.java
To integrate this pull request please the pull request should be integrate firstly https://github.com/adempiere/adempiere/pull/1966
=> #1690 Bug with database record lock when enabling accounting immediate is enabled.

.classpath
=> #2037 Correct Eclipse classpath

base/src/org/compiere/model/MTax.java
…ithub.com/adempiere/adempiere/issues/2007
(cherry picked from commit 222a92f6e00f51bb76093c23edb78b38b43bbb17)
=> #2007 Avoid to set itself as tax parent

migration/390lts-391/04010_1907_AddDimensionToAccountingReport.xml
…/adempiere/adempiere/issues/1907
(cherry picked from commit e21b3d17361c200b98e48ecd3d84acf43b9f67b5)
=> #1907 Add account dimension for Accounting Report

migration/390lts-391/03970_1869_PayrollMovementReport.xml
Fixes #1869
(cherry picked from commit b5f6039fe3d6e24c2a7026c9f353a50e50750d83)
=> #1869 Add report for Payroll Movement

base/src/org/compiere/model/X_AD_PInstance.java, migration/390lts-391/4060_1953_6720_ADD_CSV_Support_To_Report_View.xml, zkwebui/WEB-INF/src/org/adempiere/webui/apps/ProcessPanel.java, zkwebui/WEB-INF/src/org/adempiere/webui/window/ZkReportViewer.java
Issue: https://github.com/adempiere/adempiere/issues/1953
Original code from Adaxa repository.
=> #1953 Add CSV as report output type

migration/390lts-391/03755_1562_Commission_AllowDaysDueFromInvoices-Correction.xml
Fixes #1562 
"Allow also for days due originated from invoices"
Name of Element, Column and Field now readable.
=> #1562 Commission for complete payments

base/src/org/compiere/model/I_C_Phase.java, base/src/org/compiere/model/I_C_ProjectLine.java, base/src/org/compiere/model/I_C_ProjectPhase.java, base/src/org/compiere/model/I_C_ProjectTask.java, base/src/org/compiere/model/I_C_Task.java, base/src/org/compiere/model/MResource.java, base/src/org/compiere/model/X_C_Phase.java, base/src/org/compiere/model/X_C_ProjectLine.java, base/src/org/compiere/model/X_C_ProjectPhase.java, base/src/org/compiere/model/X_C_ProjectTask.java, base/src/org/compiere/model/X_C_Task.java, base/src/org/eevolution/model/MPPOrder.java, migration/390lts-391/03870_1676_GenerateMOFromProjectLine.xml, migration/390lts-391/03890_1985_GenerateSalesOrderfromProject.xml, org.adempiere.project/src/main/java/org/compiere/model/CalloutProject.java, org.adempiere.project/src/main/java/org/compiere/model/MProjectLine.java, org.adempiere.project/src/main/java/org/compiere/model/MProjectPhase.java, org.adempiere.project/src/main/java/org/compiere/model/MProjectTask.java, org.adempiere.project/src/main/java/org/compiere/process/ProjectGenOrder.java, org.adempiere.project/src/main/java/org/compiere/process/ProjectPhaseGenOrder.java, org.eevolution.manufacturing/src/main/java/base/org/eevolution/process/ProjectGenerateManufacturingOrder.java, org.eevolution.manufacturing/src/main/java/base/org/eevolution/process/ProjectGenerateManufacturingOrderAbstract.java
=> #1985 Add an action in Project Task to generate a Sales Order

base/src/org/compiere/model/MPaySelection.java
…ttps://github.com/adempiere/adempiere/issues/1991
(cherry picked from commit db9641f75167c017aab435ce722d9fbd8595b389)
=>  #1991 Pay Selection not returning getDoc_User_ID, always returns 0

base/src/org/compiere/process/ImportBPartner.java
=> #1638 Import Business Partner when a contact with same email exists

base/src/org/compiere/swing/CTabbedPane.java
Fixes #1955
see [explanation here](https://github.com/adempiere/adempiere/issues/1955#issuecomment-417633283)
=> #1955 Exception in CTabbedPane bugfix

client/src/org/compiere/apps/search/InfoInOut.java, client/src/org/compiere/apps/search/InfoInvoice.java, client/src/org/compiere/apps/search/InfoOrder.java, client/src/org/compiere/apps/search/InfoPayment.java, zkwebui/WEB-INF/src/org/adempiere/webui/panel/InfoInOutPanel.java, zkwebui/WEB-INF/src/org/adempiere/webui/panel/InfoInvoicePanel.java, zkwebui/WEB-INF/src/org/adempiere/webui/panel/InfoOrderPanel.java, zkwebui/WEB-INF/src/org/adempiere/webui/panel/InfoPaymentPanel.java
hi all,
this implements issue #1990
regards EUG
=> #1990 Info windows: show newest order, invoice, ... on top

base/src/org/compiere/wf/MWFActivity.java
of Responsible, reference to issue:
https://github.com/adempiere/adempiere/issues/1993
Hi Everybody, this pull request is a complement of previous pull request merged from issue referenced in it document.
It allows create a mail for Workflow of tables, previously it was impossible from standard EMail like document workflow
fixes #1993
=> #1993, Complement improvement for WF Activity EMail send for Supervisor

base/src/org/compiere/report/FinStatement.java
Fixes #2049
(cherry picked from commit 72fa218725e379544b15bfc67cffff9a6dea0616)
=> #2049 Error Statement Account when sending the account parameters

migration/390lts-391/03811_1656_AddingProcessedOnToA_Asset_Split.xml
…re/adempiere/issues/1656
(cherry picked from commit 1be971a7f77d2081bc53f387c732e2d4d6ebcb0d)
=> #1656 New Asset Split Document

base/src/org/compiere/process/ImportBPartner.java
fixes #2051, false reference to table.
Introduced with #1580
=> #2051 ImportBPartner.java false reference to a table

migration/390lts-391/03605_1532_ProjectProcessorWindow.xml
=> #1925  Deleted migration step 890 from 03605_1532...xml

base/src/org/compiere/model/I_C_LandedCost.java, base/src/org/compiere/model/I_C_LandedCostAllocation.java, base/src/org/compiere/model/I_C_LandedCostType.java, base/src/org/compiere/model/I_M_Product.java, base/src/org/compiere/model/MInvoiceLine.java, base/src/org/compiere/model/X_C_LandedCost.java, base/src/org/compiere/model/X_C_LandedCostAllocation.java, base/src/org/compiere/model/X_C_LandedCostType.java, base/src/org/compiere/model/X_M_Product.java, base/src/org/eevolution/process/GenerateLandedCost.java, base/src/org/eevolution/process/GenerateLandedCostAbstract.java, migration/390lts-391/04020_2031_LandedCostType.xml, migration/390lts-391/04030_2031_LandedCostTypeSB.xml, migration/390lts-391/04040_2031_LandedCostTypeTranslation.xml
fixes 2031
New field LandedCostType in table c_LandedCost.
=> #2031 Field LandedCostType in LandedCost

zkwebui/WEB-INF/src/org/adempiere/webui/apps/ProcessPanel.java
Fixes #1975.
Fixes error where the key listener in the ZK Process Panel remains active when the window is not visible.  Example:
1. In webui, login as GardenAdmin.
2. Open process Generate Invoices, fill in mandatory fields but do not execute.
3. Open window Sales Order, click New, select Business Partner and enter "Joe Block", hit Enter.
4. Generate Invoices process starts
The PR removes the key listener and replaces it by setting the OK button setFocus() method.  This traps the enter key and generates the correct behaviour.  The OK button has the focus when the process window is first opened or when a saved parameter set is selected (user selects an item and hits enters or tab.)
See #1975 for more details.
=> #1975 ZK Process Panel KeyListener remains active when window is not visible.

base/src/org/compiere/model/I_C_Phase.java, base/src/org/compiere/model/I_C_ProjectLine.java, base/src/org/compiere/model/I_C_ProjectPhase.java, base/src/org/compiere/model/I_C_ProjectTask.java, base/src/org/compiere/model/I_C_Task.java, base/src/org/compiere/model/MResource.java, base/src/org/compiere/model/X_C_Phase.java, base/src/org/compiere/model/X_C_ProjectLine.java, base/src/org/compiere/model/X_C_ProjectPhase.java, base/src/org/compiere/model/X_C_ProjectTask.java, base/src/org/compiere/model/X_C_Task.java, base/src/org/eevolution/model/MPPOrder.java, migration/390lts-391/03870_1676_GenerateMOFromProjectLine.xml, org.adempiere.project/src/main/java/org/compiere/model/CalloutProject.java, org.adempiere.project/src/main/java/org/compiere/model/MProjectLine.java, org.adempiere.project/src/main/java/org/compiere/model/MProjectPhase.java, org.adempiere.project/src/main/java/org/compiere/model/MProjectTask.java, org.eevolution.manufacturing/src/main/java/base/org/eevolution/process/ProjectGenerateManufacturingOrder.java, org.eevolution.manufacturing/src/main/java/base/org/eevolution/process/ProjectGenerateManufacturingOrderAbstract.java
=> #1676 Add new action to generate a manufacturing order from a project line

org.adempiere.asset/src/main/java/base/org/compiere/model/MAssetAddition.java
Fixes #1671
(cherry picked from commit 6c13649782dbb22fe5551d1e0444e5568ddb22c1)
=> #1671 Fixed Asset with zero period depreciation cannot be added for control

zkwebui/WEB-INF/src/org/adempiere/webui/panel/AbstractADWindowPanel.java
Fixes #2074
(cherry picked from commit 22708e04f8251b66bea66af1306e4504b8d52405)
=> #2074 Error launching jasper reports print format from any tab

base/src/org/compiere/model/GridField.java, base/src/org/compiere/process/MigrationApply.java, base/src/org/compiere/process/MigrationStepApply.java
https://github.com/adempiere/adempiere/issues/2083
Hi all, this pull request try reduce log for travys CI.
fixes #2083 
Best Regard
=> #2083, change log level for migration apply, reference to issue:

base/src/org/compiere/apps/ProcessController.java
Fixes #2062 .
The Process Controller does not create new process instances when using a saved parameter set. This causes a duplicate key error in the constraints of the temporary table for some processes.  The change ensures process instances are not deleted or reused from the saved parameter instances.  Whenever a saved parameter set is selected, the saved instance is deleted - meaning its name is set to null and it is removed from the list - and a new instance is added using that name.
=> #2062 Prevent duplicate key errors when running processes with saved parameters.

base/src/org/spin/util/GeneratePassword.java
Fixes #2107 
Hi all, please take a minute for test it, is very important this change.
=> #2107 Validate Login User for Password reset

base/src/org/compiere/util/PaymentExportList.java
Fixes #1805
Hi all, this pull request fix a little problem when leftPadding and rightPadding is called with text empty
=> #1805 Fixed left/right padding when text is not mandatory and is empty

base/src/org/spin/util/AbstractExportFormat.java, base/src/org/spin/util/ReportExportHandler.java, client/src/org/compiere/print/Viewer.java, zkwebui/WEB-INF/src/org/adempiere/webui/window/ZkReportViewer.java
Hi everybody, this change allows extends **Report Export Functionality** for send files and may actions that is not necessary download report exported.
Please take a time for see it:
https://github.com/adempiere/adempiere/issues/2137
fixes: #2137
=> #2137, improve report export functionality, reference to issue:

base/src/org/eevolution/process/BankTransfer.java, base/src/org/eevolution/process/BankTransferAbstract.java
Fixes #2114
Please take a time for see it.
=> #2114 Problem with bank transfer process

client/src/org/compiere/apps/APanel.java
This pull request fixes the follow issue
https://github.com/adempiere/adempiere/issues/2150
Fixes: #2150
=> #2150, Fixes error with zoom, reference to issue:

base/src/org/adempiere/model/GenericZoomProvider.java, base/src/org/adempiere/model/ZoomMetaInfo.java
Fixes #2153 
Hi everybody, this pull request removes a hard-code and allows show only linked columns instead SQL columns. Also a cache is added for performance improvement.
Best regards.
=> Fixed error with zoom with column SQL

base/src/org/compiere/process/CopyRole.java, base/src/org/compiere/process/CopyRoleAbstract.java, serverRoot/src/main/servlet/org/compiere/web/AdempiereMonitor.java
Hi @marcalwestf here a change for Copy Role process with a new approach, please take your time for review it.
Best Regard
https://github.com/adempiere/adempiere/issues/2165
Fixes: #2165
=> #2165, Add new approach for Copy role process, reference to issue:

org.adempiere.project/src/main/java/org/compiere/model/MProjectIssue.java, org.adempiere.project/src/main/java/org/compiere/process/ProjectIssue.java
Fixes https://github.com/adempiere/adempiere/issues/2163
=> #2163 Errors in ProjectIssue

migration/390lts-391/03260_1389_AddNewColumnsProject.xml, migration/390lts-391/03760_1615_PriceListEntries.xml
Fixes #2144
(cherry picked from commit d558aca7f7fe9f0b5d9c9feb6b5273a826015df8)
=> Remove orphan records out of migration steps

base/src/org/compiere/model/MTree.java
Fixes #2147
(cherry picked from commit c485780316c870bd0953be78219bedc187824e75)
=> Remove Oracle-incompatible SQL statement for new Tree functionality

migration/390lts-391/04380_2095_KeyColumnsAsID.xml
=> StackOverFlow Error in WAcctViewer

serverRoot/src/main/servlet/org/compiere/web/AdempiereMonitor.java
Hi all, this pull request add support to all OS on Server Manager log
Fixes: #2165
https://github.com/adempiere/adempiere/issues/2165
=> #2165, change separator for support others OS, reference to issue:

base/src/org/compiere/process/ImportBudget.java
Hi everybody this pull request resolve a little error importing budget, the bug was described here: #2198
Fixes: #2198 
https://github.com/adempiere/adempiere/issues/2198
=> #2198, Fixed client filter for import budget, reference to issue:

zkwebui/WEB-INF/src/org/adempiere/webui/apps/form/WTrialBalance.java
Fixes https://github.com/adempiere/adempiere/issues/1688
This pull request replaces the pullrequest https://github.com/adempiere/adempiere/pull/1780, which contains by error the file _adempiere.iml_
=> WTrialBalance ORG_ID should not be mandatory by default

base/src/org/compiere/process/OrderPOCreate.java, base/src/org/compiere/process/OrderPOCreateAbstract.java
Hi Everybody, @homebeaver this pull request make a enhance for process **Create PO from sales Orders**, please take a time for review it.
Best regard.
Fixes: #1649
https://github.com/adempiere/adempiere/issues/1649
=> #1649, Improve PO create from Sales Orders process

migration/390lts-391/04020_2031_LandedCostType.xml, migration/390lts-391/04030_2031_LandedCostTypeSB.xml
https://github.com/adempiere/adempiere/issues/2031
Correction of the XML files
=> adempiere: #2031 Field LandedCostType in LandedCost

base/src/org/compiere/process/OrderPOCreate.java
Remove bad relation for Purchase Order.
This pull request remove bad relation created.
https://github.com/adempiere/adempiere/issues/1649
=> #1649, change bad relation for Order PO create, reference to issue:

migration/391lts-392lts/04410_Change_Browser_Name_Length.xml
Hi everybody, this pull request resolve a little error with Language Maintenance process.
Fixes: #2242
https://github.com/adempiere/adempiere/issues/2242
=> #2242, Change Length of AD_Browser_Trl table, reference to issue:

zkwebui/WEB-INF/src/org/adempiere/webui/window/WTextEditorDialog.java
Hi everybody, this pull request resolve a error reported from issue: #1467 
Best regard
=> #1467 Validate Null in Text Editor Dialog

zkwebui/WEB-INF/src/org/adempiere/webui/component/GridPanel.java
fixes https://github.com/adempiere/adempiere/issues/2360
=> adempiere  #2360 Quicksheet shows all fields

client/src/org/compiere/grid/tree/VTreePanel.java
Fixes #2349 
Trying to add a menu item to the bar in the Swing client caused an error.
=> Fixes #2349.  Restores a needed line that was deleted accidentally.

.classpath
Issue:
https://github.com/adempiere/adempiere/issues/2395
Fixes: #2395
=> #2395 Missing .classpath Declaration

base/src/org/compiere/util/Language.java
Hi everyone this pull request add support to Panamá Language.
Just add **es_PA** as location and date format.
Best regard.
=> Add support to Panama variant for language

zkwebui/WEB-INF/src/org/adempiere/webui/component/GridPanel.java, zkwebui/WEB-INF/src/org/adempiere/webui/panel/ADTabPanel.java
"Field movement cursor not working properly" is resolved for this pull request.
Please take a time for test it, any detail about initial report is here #2329 
Fixes: #2329
=> #2329 Solve error with Field Movement Cursor in Single Record

base/src/org/compiere/model/MInvoice.java
Issue: https://github.com/adempiere/adempiere/issues/2293
Fixes: #2293
=> #2293 Error when completing a "Return to Vendor" Invoice (AP Credit Memo)

base/src/org/spin/process/ExportSurrogateKeyToMigration.java, base/src/org/spin/process/ExportSurrogateKeyToMigrationAbstract.java, migration/391lts-392lts/04420_Add_EntityType_Generate_UUID.xml
Hi everybody, this pull request allows generate Surrogate keys for a specific Entity Type, see Step by Step:
Replace #2284
=> Add Entity Type as parameter for Export UUID process

migration/391lts-392lts/04440_2381_Project_Status_Category_does_not_work.xml
Issue: https://github.com/adempiere/adempiere/issues/2381
Fixes: #2381
=> #2381 Project Status Category doesn't work

base/src/org/compiere/process/RequisitionPOCreate.java
=> #2375 Error on process Generating PO from Requisition

base/src/org/eevolution/model/I_HR_Process.java, base/src/org/eevolution/model/X_HR_Process.java, migration/391lts-392lts/04430_Add_HR_Process_Currency.xml, org.eevolution.hr_and_payroll/src/main/java/base/org/compiere/acct/Doc_HRProcess.java, org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/model/MHRProcess.java
This pull request allows define a payroll process in other curreccy,
Note that just is addeded two collumn: Currency and Conversion Type.
=> Add currency and currency conversion for Payroll process, this change

com.kkalice.adempiere.migrate/src/com/kkalice/adempiere/migrate/DBEngine_Postgresql.java
Add support to latest version of PostgreSQL
Fixes: #2250 
issue: https://github.com/adempiere/adempiere/issues/2250
=> #2250, Fixed error with supported version for postgreSQL, reference to

base/src/org/compiere/db/CConnection.java, base/src/org/compiere/model/PO.java, base/src/org/compiere/util/DB.java, zkwebui/WEB-INF/src/org/adempiere/webui/panel/LoginPanel.java
This pull request resolve a problem with old compatibility for ADempiere difference of versions
Add old compatibility using java UUID, reference to issue:
https://github.com/adempiere/adempiere/issues/2247
Fixes: #2247
=> #2247, Fixed error with getUUID function

migration/391lts-392lts/04430_2382_Project_Next_Status_not_Filtered_by_Category.xml
Issue: https://github.com/adempiere/adempiere/issues/2382
Fixes: #2382
=> #2382 Project Status: Next Status not Filtered by Project Status Category

migration/391lts-392lts/04450_2380_How_to_Re-Open_a_closed_Project.xml, org.adempiere.project/src/main/java/org/compiere/process/ProjectClose.java
Issue: https://github.com/adempiere/adempiere/issues/2380
Fixes: #2380
=> #2380 How to Re-Open a closed Project ?

base/src/org/spin/process/RoleCreateFromWindowProcess.java, base/src/org/spin/process/RoleCreateFromWindowProcessAbstract.java, migration/391lts-392lts/04450_Add_Role_Process_Create_From_Window.xml
This pull request allows add role access to role with a Smart Browse that show window and tab joined to process of tab.
Note that exist a simple step by step as gif:
=> Add Smart Browse for Create process from window and tab on Role

base/src/org/spin/util/SendReportToQueue.java, base/src/org/spin/util/SendReportToQueueAppRegistered.java, base/src/org/spin/util/support/mq/ActiveMQ.java, base/src/org/spin/util/support/mq/PrinterMessage.java
Here a little change for a test case of App Registration with **ActiveMQ**
This is related to: https://github.com/adempiere/adempiere/pull/2376
Here a test with [ActiveMQ](https://hub.docker.com/r/rmohr/activemq)
=> Improve ActiveMQ support from app registration

zkwebui/WEB-INF/src/org/adempiere/webui/window/FindWindow.java
=> Fixing value_to in search window

client/src/org/compiere/grid/VTabbedPane.java
Hi @yamelsenih 
this is the alternative pull to #2425
It will fix the problem in swing-client #2424
Fixes: #2424 
regards EUGen
=> #2424 try+catch in VTabbedPane to fix the problem

zkwebui/WEB-INF/src/org/adempiere/webui/editor/WSearchEditor.java
NPE for Bpartner search see #1892 
Fixed: #1892
=> #1892 Solved NPE in search fields

migration/391lts-392lts/4520_2427_Error_When_Creating_Translations.xml
Issue: https://github.com/adempiere/adempiere/issues/2427
Field AD_Browse_Trl increased both in AD and DB to 255.
=> #2427 Error When Creating Translations

base/src/org/compiere/impexp/BankStatementLoaderInterface.java, base/src/org/compiere/impexp/OFXBankStatementHandler.java, base/src/org/compiere/impexp/OFXFileBankStatementLoader.java, base/src/org/compiere/model/MBankStatementLoader.java, base/src/org/compiere/process/ImportBankStatement.java, base/src/org/spin/util/impexp/BankStatementHandler.java
Hi everybody, this pull request make the following:
Add functional programming for import bank statement
Add getPayeeDescription method for add Bank Statement line Description
from Import statement line
=> Improve Import Bankk Statement

base/src/org/compiere/acct/Doc_InOut.java, base/src/org/compiere/acct/Doc_Order.java
This pull request resolve a bug when a accounting is configured as commitment, here a explain: #2444 
Currently exists PO/SO Commitment, the follow example show a bug for it when a shipment is distinct of order:
Data:
**Sales Order: 50000**
BPartner: Garden Admin
Product: Azalea Bush
Quantity: 25
Price: 23.75
Fact Acct: **25 * 23.75 = 593.75**
**Shipment: 500000**
BPartner: Garden Admin
Product: Azalea Bush
Quantity: 20
Expected Fact Acct: **20 * 23.75 = 475**
Fact Acct: 
A gif
Fixes: #2444
=> #2444, Fixed error with commitment for Sales Orders and Purchase,

base/src/org/compiere/model/MQuery.java, db/ddlutils/oracle/views/T_INVOICEGL_V.sql, db/ddlutils/oracle/views/T_INVOICEGL_VT.sql, db/ddlutils/postgresql/views/T_INVOICEGL_V.sql, db/ddlutils/postgresql/views/T_INVOICEGL_VT.sql, migration/391lts-392lts/04520_Fixed_MultiLanguage_Gain_Loss_Report.xml
Currently **Invoice Not Realized Gain/Loss** report is worked when is running with english language but I wnat to run it with **Español (VE)** and not worked.
Here a explain:
Here a log.
<pre>
===========> DataEngine.loadPrintData: null - ERROR: missing FROM-clause entry for table "t_invoicegl_v"
Position: 8312
SQL=SELECT A.Value||'-'||A.Name AS AName,T_InvoiceGL_vt.Account_ID AS Account_ID,T_InvoiceGL_vt.DateAcct,T_InvoiceGL_vt.AmtAcctCr,T_InvoiceGL_vt.AmtAcctDr,(SELECT NVL(CAST (Fact_Acct.Fact_Acct_ID AS Text),'') FROM Fact_Acct WHERE T_InvoiceGL_vt.Fact_Acct_ID=Fact_Acct.Fact_Acct_ID) AS BFact_Acct_ID,T_InvoiceGL_vt.Fact_Acct_ID AS Fact_Acct_ID,(SELECT NVL(C_AcctSchema.Name,'') FROM C_AcctSchema WHERE T_InvoiceGL_vt.C_AcctSchema_ID=C_AcctSchema.C_AcctSchema_ID) AS …
=> Fixed error with Gain/Loss Report for Multi-Language

migration/391lts-392lts/04540_Request_Subject.xml
This pull request just add Subject for Request
The subject is a new attribute for request, now is possible set fixed values for:
**Document No
Subject
Summary**
=> Add subject for request

org.adempiere.production/src/main/java/base/org/adempiere/process/CalculateReplenishPlan.java, org.adempiere.production/src/main/java/base/org/compiere/process/ReplenishReportProduction.java
fixes https://github.com/adempiere/adempiere/issues/2414
=> adempiere #2414 Replenishplan:CalculateReplenishPlan not creates ReLines

client/src/org/eevolution/form/VBrowser.java, client/src/org/eevolution/grid/Browser.java
Issue: https://github.com/adempiere/adempiere/issues/2467
=> #2467 Error in Smart Browsers when "Value" or "DocumentNo" are query fields

base/src/org/eevolution/model/I_C_SalesHistory.java, base/src/org/eevolution/model/X_C_SalesHistory.java, migration/391lts-392lts/04530_2472_AddSalesRepToGenerateInvoiceHistory.xml, migration/391lts-392lts/04540_2477_AddingInvoiceLinesColumnsIntoSalesHistory.xml, org.eevolution.manufacturing/src/main/java/base/org/eevolution/process/GenerateSalesHistory.java, org.eevolution.manufacturing/src/main/java/base/org/eevolution/process/GenerateSalesHistoryAbstract.java
=> Adding LineNetAmt into Sales history for adding analytics

base/src/org/adempiere/pipo/PackInHandler.java, base/src/org/adempiere/pipo/PoFiller.java, base/src/org/adempiere/pipo/handler/GenericPOHandler.java
Replace: #2488 
- Add PO model to export parent from packout instead id from context
- Add support to validation from default value for mandatory columns
=> Add changes for class for import from packout

org.adempiere.request/src/main/java/org/compiere/model/MMailText.java
From: #2504
Currently exist a MailText for handle templates and replace context keys by object values, a example is **Request window** that change **Result** field when the mail template is changed.
**The Problem:**
I want to write to new user BP with the follow attributes:
User Value: **UserExample**
Business Partner Name: **BP Example**
Business Partner Value: **BPExample**
**The template is:**
Dear **@Name@**, your user was created and you can login in our application with follow data:
User Value: **@Value@**
Business Partner Name: **@Name@**
Business Partner Value: **@Value@**
The result is:
Dear **GardenAdmin**, your user was created and you can login in our application with follow data:
User Value: **UserExample**
Business Partner Name: **GardenAdmin**
Business Partner Value: …
=> Improve mail text formatter for may PO values

base/src/org/compiere/model/MLookupFactory.java
This is a minor change for check role access parameter on lookup
=> Add parameter for validate session on lookup

client/src/org/compiere/apps/ProcessCtl.java, client/src/org/compiere/print/ReportCtl.java, org.adempiere.webservice/WEB-INF/src/com/_3e/ADInterface/ModelADServiceImpl.java, org.adempiere.webservice/WEB-INF/src/com/_3e/ADInterface/Process.java
=> #2512 Problem with ADempiere web service when execute process for jasper report or Adempiere Report Engine 

client/src/org/eevolution/grid/Browser.java
Issue: #2467
Corrects Pull Request https://github.com/adempiere/adempiere/pull/2478
Correction: catch only strings.
Thanks @e-Evolution for the observation.
=> #2467 Error in Smart Browsers when "Value" or "DocumentNo" are query fields.

client/src/org/eevolution/grid/Browser.java
Reverts adempiere/adempiere#2516
=> Revert "#2467 Error in Smart Browsers when "Value" or "DocumentNo" are query fields."

.classpath
Please add this pull request to core for improve eclipse classpath
=> Change classpath

migration/392lts-393lts/04650_536_Add_Keyboard_Validation_POS.xml
Add POLS Key layout validation 
Fixes: #536
=> Add POS keyboard validation

migration/392lts-393lts/04640_535_Add_Validation_Sales_Price_List_POS.xml
This pull request resolve a little error for get price list on POS setup
Fixes: #535
=> Add Validation for Sales price list

migration/392lts-393lts/04630_527_Add_Display_Logic_Quantity_KeyLayout.xml
Fixes: #527
Please approve this pull request..
Best regard
=> Add Display Logic for Quantity column

base/src/org/compiere/model/MPOSKey.java, migration/392lts-393lts/04620_525_Add_DisplayLogic_POS_KeyLayout.xml
Fixes: #525
Add display logic for product on POS key layout
See: #525
=> Add Display logic for product POS key layout

base/src/org/spin/util/ASPUtil.java
Fixes: #2569
Remove bad reference to cache from Window / Tabs / Fields, Browser /
Fields, Process / Parameters
See a gif with a result after apply it:
=> Bufix NPE for field from ASP

base/src/org/compiere/model/I_AD_PInstance.java, base/src/org/compiere/model/MPInstance.java, base/src/org/compiere/model/X_AD_PInstance.java, migration/392lts-393lts/04610_Add_Session_Process_Instance.xml
Fixes: #2581 
This pull request allows link session to process instance.
Now you can see all process running from current session, see video:
=> Add Session reference to process instance

base/src/org/compiere/model/MBrowseCustom.java
Hi, just a little change for save automatically a Custom Browser from Source
Best regard
=> Add saveEx for custom browse

org.eevolution.manufacturing/src/main/java/base/org/eevolution/model/MPPPeriodDefinition.java
Validate null for operational calendar
Fixes: #1637
=> Fixes error with NPE for Operational Calendar when year is null

base/src/org/compiere/model/MSetup.java
=> Add support to create login user for initial setup

base/src/org/compiere/model/I_AD_User.java, base/src/org/compiere/model/X_AD_User.java, migration/392lts-393lts/04670_Add_User_Info_Logo.xml
Allows add User contact info like Logo or Image URL for avatar image, see:
See result:
A little video:
=> Add User info Logo

base/src/org/spin/model/I_AD_UserSocialMedia.java, base/src/org/spin/model/MADUserSocialMedia.java, base/src/org/spin/model/X_AD_UserSocialMedia.java, base/src/org/spin/util/support/GenericAppSupport.java, migration/392lts-393lts/04680_Add_Social_Media_Info.xml
This pull request allows add [Social Media](https://en.wikipedia.org/wiki/Social_media) information for main social network, you can add useful info for contact and it can be used for get more integration with ADempiere using App registration.
See a gif:
=> Add social media infor for user contact

base/src/org/spin/model/MADAppRegistration.java, base/src/org/spin/model/MADAppSupport.java, base/src/org/spin/model/MADAppSupportPara.java, migration/392lts-393lts/04690_Add_User_App_Registration.xml
Add access level for app registration parameters and user link
=> Add Access level for System + Client for App registration parameter and

base/src/org/compiere/model/I_AD_User.java, base/src/org/compiere/model/X_AD_User.java, migration/392lts-393lts/04690_Add_My_Own_Changes_Flag.xml, org.adempiere.project/src/main/java/org/compiere/util/ProjectProcessorUtils.java, org.adempiere.request/src/main/java/org/compiere/model/MRequest.java
This pull request allows notify me when I have a flag for notify me when I make changes myself
Fixes: #2616
Some reference
=> Add feature for include changes to notify for myself

base/src/org/adempiere/model/MViewColumn.java, base/src/org/compiere/model/I_C_Commission.java, base/src/org/compiere/model/I_C_CommissionType.java, base/src/org/compiere/model/MCommissionRun.java, base/src/org/compiere/model/MCommissionType.java, base/src/org/compiere/model/X_C_Commission.java, base/src/org/compiere/model/X_C_CommissionRun.java, base/src/org/compiere/model/X_C_CommissionType.java, migration/392lts-393lts/04661_2173_Add_Dynamic_Commission.xml
Add commission Type for make custom search for commission
Fixes: #2173
=> Add support to commission type

base/src/org/compiere/model/MTab.java
This pull request allows show a field for ASP when it have a ASP_Level as Custom instead restrict
=> Fixed ASP error for fields

org.adempiere.request/src/main/java/org/compiere/model/MMailText.java
This pull request allows create reference to any foreign lookup from PO setted for mail text, a example is a Request:
R_Request have many references like:
- Project
- Phase
- Task
- Resolution
- Group
- Status
... And many external references that is nice to have as variable for parse mail text.
With this change now you can make a Mail template like:
```
Project Name: @C_Project.Name@
Project Value: @C_Project.Value@
Project Phase: @C_ProjectPhase.Name@
Project Task: @C_ProjectTask.Name@
Project Task Description: @C_ProjectTask.Description@
Request Status: @R_Status.Name@
Group Name: @R_Group.Name@
Group Description: @R_Group.Description@
Request Type: @R_RequestType.Name@
Resolution Name: @R_Resolution.Name@
Resolution Description: @R_Resolution.Description@
```
And you can get a some: …
=> Add support to multi-reference for Mail text

zkwebui/WEB-INF/src/org/eevolution/grid/WBrowserListItemRenderer.java
Add support to show date and time for ZK browse row
currently when a row has date value it is showed as blank data
=> Fixed error with date for Browse row from ZK

base/src/org/compiere/process/SynchronizeTerminology.java
This pull request allows syncrhonize terminology for Smart Browser menu
=> Add support to browser translation menu

base/src/org/adempiere/pipo/PackOut.java, base/src/org/compiere/model/I_AD_Package_Exp_Detail.java, base/src/org/compiere/model/X_AD_Package_Exp_Detail.java, base/src/org/spin/model/I_AD_Package_Exp_Custom.java, base/src/org/spin/model/MADPackageExpCustom.java, base/src/org/spin/model/X_AD_Package_Exp_Custom.java, base/src/org/spin/util/impexp/TestPackoutExporter.java, migration/392lts-393lts/04720_Add_Custom_Exporter.xml, migration/392lts-393lts/04730_Add_Custom_Exporter_Test_Data.xml
This functionality allows to create a custom export handler for packout.
I add a gif for example here:
The export functionality is a **Payroll Report** window
```Java
/******************************************************************************
* Product: Adempiere ERP & CRM Smart Business Solution                       *
* This program is free software; you can redistribute it and/or modify it    *
* under the terms version 2 or later of the                                  *
* GNU General Public License as published                                    *
* by the Free Software Foundation. This program is distributed in the hope   *
* that it will be useful, but WITHOUT ANY WARRANTY; without even the implied *
* warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.           * …
```
=> Add Custom Exporter functionality

base/src/org/compiere/model/MLookupFactory.java
Currently when a Table and search view is build from MLookupFactory the return value not have Displaycolumn
=> Add displaycolumn value for Lookup Info

adempiere.iml, tools/build.xml
#2619 Attachment NextCloud Integration https://github.com/adempiere/adempiere/pull/2619
- Update CStool.jar
- Update the IntelliJ library
=> Update Libraries for  Attachment NextCloud Integration

.travis.yml, build.xml
This pull request fixed a build error with travis and oracle jdk, I change it for openJdk8
Fixed: #2686
Best regard.
Note that build from travis is ok: https://travis-ci.org/erpcya/adempiere/builds/563771381
=> Fixed error with travis Continuous Integration for Oracle 8 license

base/src/org/compiere/model/PO.java, migration/392lts-393lts/04750_Add_Filter_Account_Element.xml
Fixed error on creating node for tree user element 1.
see: 
Filter parents elements value by account element.
see:
=> Fixed errors on accounting tree

migration/392lts-393lts/05030_DashboardSettingColumnProportion.xml, zkwebui/WEB-INF/src/org/adempiere/webui/desktop/DefaultDesktop.java
=> #2683 Enable Dashboard column setting proportion

org.eevolution.manufacturing/src/main/java/base/org/eevolution/process/ForecastRunCreate.java
With imported sales history, I had difficulty in creating a forecast run.  The forecast run lines are based on a forecast run master.  The history is linked to the master table via the Product ID.  When creating the forecast lines, if there is no Master entry, there is no way to create a new one.
This pull request creates a new master entry if the query returns no results.
See https://github.com/adempiere/adempiere/issues/2450
Here is the original code in ForecastRunCreate with comments added to show the issue:
private int generateForecastRunMaster(MPPForecastRun run,
MPPForecastDefinition fd, MPPPeriod start, MPPPeriod end) {
int count = 0;
for (MPPForecastDefinitionLine fdl : fd.getLines(true)) {
//  Problem - note that the select statement requires an entry in PP_ForecastRunMaster …
=> #2450 Forecast Run has an issue generating the first run

db/ddlutils/oracle/views/RV_M_TRANSACTION.sql, db/ddlutils/postgresql/views/RV_M_TRANSACTION.sql, migration/392lts-393lts/05080_2717_Add_Product_Transaction_Report_Parameters.xml
Add some parameters to Product Transaction report
Fixes: #2717
=> Add parameters to Product Transaction Report

base/src/org/adempiere/pipo/AttributeFiller.java, base/src/org/adempiere/pipo/IDFinder.java, base/src/org/adempiere/pipo/PackInHandler.java, base/src/org/adempiere/pipo/PackOut.java, base/src/org/adempiere/pipo/handler/GenericPOHandler.java
This pull request allows:
- Make references for parent records from UUID instead ID
- Define additional parameters for export a packout
- Ignore a record if exists a error saving
- Ignore a record if exists a error with missing mandatory references
=> Add changes for packout handler

db/ddlutils/oracle/views/RV_TRANSACTION.sql, db/ddlutils/postgresql/views/RV_TRANSACTION.sql, migration/392lts-393lts/05070_2715_Add_Transaction_Detail_Parameters.xml
This pull request add some parameters to Transaction Detail report
Fixes: #2715
=> Add Transaction Detail Parameters

db/ddlutils/oracle/views/RV_STORAGE.sql, db/ddlutils/postgresql/views/RV_STORAGE.sql, migration/392lts-393lts/05060_1397_Add_New_Parameters_Storage_Detail.xml
This pull request add so,me parameters to Storage Detail report
Fixes: #1397
=> Add parameters for Storage Detail report

base/src/org/compiere/util/MimeType.java
This pull request resolve a issue very old from tha last implementation for Attachment based on extension for files
Fixes #2557
=> Fixed error with validation for extension with attachment

base/src/org/spin/util/ASPUtil.java
=> Fixed error with translation for tabs, reference to issue: #2725

base/src/org/compiere/model/GridFieldVO.java
=> fixed error with field group translation

base/src/org/compiere/model/I_M_RequisitionLine.java, base/src/org/compiere/model/X_M_RequisitionLine.java, base/src/org/spin/process/RFQCreateFromRequisition.java, base/src/org/spin/process/RFQCreateFromRequisitionAbstract.java, migration/392lts-393lts/05110_2728_Add_CreateFromRequisition_RFQ.xml
This Pull request add a new Smart Browser for create from on RFQ
Fixes: #2728 
Here a gif with last functionality
=> Add Create From Requisition for RFQ reference to issue #2728

.classpath, migration/392lts-393lts/05090_2023_Add_Form_GenerateOutBoundOrder.xml, org.eevolution.warehouse/src/main/java/base/org/spin/form/OutBoundOrder.java, org.eevolution.warehouse/src/main/java/ui/zk/org/spin/form/WOutBoundOrder.java
Add a new form for generate outbound order easy from Sales orders and distribution orders
See a image:
Fixes: #2023
=> Add form for outbound order

org.eevolution.warehouse/src/main/java/base/org/eevolution/model/MWMInOutBound.java, org.eevolution.warehouse/src/main/java/base/org/eevolution/model/MWMInOutBoundLine.java
This pull request allows create receipt from express receipt after complete 
Fixes: #2742
=> Generate receipt automatically from Express Receipt

migration/392lts-393lts/05160_Add_Vehicle_Group_Window.xml
This pull request add a window for Vehicle group like a attribute more of vehicles
=> Add Vehicle Group Window

base/src/org/eevolution/process/GenerateCostDetail.java, base/src/org/eevolution/process/GenerateCostDetailAbstract.java, migration/392lts-393lts/05120_Add_ProductCategoryFilter_on_GenerateCost_Process.xml
Add support to filter by Product Category on Generate Cost Process
see:
=> Add filter by Product Category on Generate Cost Process

org.eevolution.warehouse/src/main/java/base/org/spin/form/OutBoundOrder.java, org.eevolution.warehouse/src/main/java/ui/zk/org/spin/form/WOutBoundOrder.java
This pull request add UOM reference to outbound line generated from sales order or distribution
=> Fixed error with uom for outbound order frolm form for generate outbound

migration/392lts-393lts/05190_Column_Processing_Does_Not_Exists.xml
Fixed error when a user try close a Freight order
Step by step:
1. Go to Freight Order
2. Press Document Action button
3. Select close action
This process throw a error: Column **Processing** does not exists hint
The problem is that **Processing** column is missing
=> Fixed error with missing column for Freight Orders

migration/392lts-393lts/05220_Add_Outbound_Detail.xml
Add Outbound order detail report for wath:
- Outbound:
- Delivered
- Invoiced
- Open to Invoice
- Open to Delivered
- All
=> Add Report for Outbound order detail

base/src/org/compiere/process/ImportInvoice.java, migration/392lts-393lts/05170_Add_Columms_To_Import_Invoice.xml
Add columns for search sales representative and price list by name, and support import model validation.
=> Add Columns for search by Sales Representative Name and Price List Name

migration/392lts-393lts/05220_Add_Outbound_Detail.xml
Hi I apologize for push a change with a bad reference, this pull request resolve a failure step for XML pushed on #2765 
Best regard
=> Replace Report view where clause and fix missing reference

migration/392lts-393lts/05120_2747_Add_Generate_Freight_Order_from_Outbound_Order.xml
Related to #2747 generate freight order from outbound #2750
Remove missing column
=> Remove missing column XML

migration/392lts-393lts/05250_Add_Report_View_Storage_Detail.xml
This pull request just add two Report Views for Storage detail report:
- Only Stock: Show All Storage when it have Stock
- Only Available: Show All storage when it have quantity available
=> Add report View for Storage Detail:

base/src/org/compiere/model/I_M_Production.java, base/src/org/compiere/model/I_M_ProductionBatch.java, base/src/org/compiere/model/MProduction.java, base/src/org/compiere/model/X_M_Production.java, base/src/org/compiere/model/X_M_ProductionBatch.java, migration/392lts-393lts/05230_Add_BOM_ProductionBatch.xml
This pull request allows select a BOM of Product for Production batch and production.
Fixes: #2773 
Best regard
=> Add support to BOM for Production Batch Order and production for one

org.eevolution.warehouse/src/main/java/base/org/eevolution/model/MWMInOutBound.java
Add support to reactivate it for Outbound order
Just a little change for implement **setProcessed** method
=> Add Reactivate It support to Outbound

migration/392lts-393lts/05260_Add_Production_Batch_PrintFormat.xml
This pull request add print formats for:
- Production Batch
- Production
See Image:
=> Add Print format for Production Batch

org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/service/HRActionNotice.java, org.eevolution.hr_and_payroll/src/main/java/ui/swing/org/eevolution/form/VHRActionNotice.java, org.eevolution.hr_and_payroll/src/main/java/ui/zk/org/eevolution/form/WHRActionNotice.java
Fixed error with action notice for distinct employee with same concept, see: #2783 
Fixes: #2783
=> Fixed error with reload for movements on action notice

migration/392lts-393lts/05270_Add_Parameters_Shipment_Details_Report.xml
Add parameters for Shipment Details report, see image:
=> Add Parameters for reporte Shipment Details

migration/392lts-393lts/05280_Add_PaymentSelection_PrintFormat.xml
This pull request allows create a print format from payment selection, see image:
=> Add Print format to payment selection

base/src/org/compiere/model/MPaySelection.java
Please approve it, I test it for many customers
Fixes: #2794
=> Fixed error with payment selection bad for account of bpartner

base/src/org/spin/process/PaySelectionReversePayment.java, base/src/org/spin/process/PaySelectionReversePaymentAbstract.java, migration/392lts-393lts/05290_Add_Reverse_Payment_PaySelection.xml
Add process for reverse payments from payment selection
Fixes: #2800
=> Add process for reverse payments from Payment Selection

base/src/org/compiere/model/MPaySelectionCheck.java
Set document no from payment selection check
Fixes: #2802
=> Set document no for payment from payment selection

org.eevolution.warehouse/src/main/java/base/org/spin/process/GenerateInvoiceInOutBound.java
This change add support to print invoices automatically from Outbound orders
=> Add support to print invoices automatically

client/src/org/compiere/print/Viewer.java, zkwebui/WEB-INF/src/org/adempiere/webui/window/ZkReportViewer.java
Fixed error with exporter for report when a print format or report view is changed it don't refresh exporter
=> Fixed error with exporter when a print format is changed

org.eevolution.fleet/src/main/java/base/org/eevolution/model/MDDFreight.java
This pull request allows add document action for freight orders
=> Add document actions for freight order

base/src/org/spin/process/PaySelectionSendRemittance.java, base/src/org/spin/process/PaySelectionSendRemittanceAbstract.java, migration/392lts-393lts/05380_2809_Add_Remittance_Send_Mail.xml
=> Add process for send remittance mail

base/src/org/compiere/model/MProduction.java
Resolve problem with void action for production document
Fixes: #2807
=> fixed error with void action for production in progress

migration/392lts-393lts/05370_2812_Fixed_Synchronize_Terminology.xml
Fixed error with synchronize terminology process and menu Name length
Fixes: #2812
=> Fixed error with Menu field length

client/src/org/spin/apps/form/BankStatementMatchController.java
Fixed error with bank statement match.
The bug is that this process allows reference many bank statement lines to one payment
=> Fixed error with duplicate reference from bank statement match to

base/src/org/compiere/model/I_AD_OrgInfo.java, base/src/org/compiere/model/I_C_Payment.java, base/src/org/compiere/model/X_AD_OrgInfo.java, base/src/org/compiere/model/X_C_Payment.java, base/src/org/compiere/process/BankStatementPayment.java, base/src/org/compiere/process/BankStatementPaymentAbstract.java, migration/392lts-393lts/05390_Add_BankStatement_Create_Payment_SB.xml
This pull request allows create payments from Bank Statement 
Step by Step:
1. Create a Bank Statement
2. Import bank statement
3. Open SB for Create Payments from Bank Statement
4. All records from Bank Statement lines that not exists from payment are showed here
5. Select a Transaction Type
6. Select a Charge if it apply
7. Process
=> Add support to create payment from Bank Statement

org.eevolution.hr_and_payroll/src/main/java/base/org/compiere/acct/Doc_HRProcess.java
https://github.com/adempiere/adempiere/issues/2815
Use the optional filter C_BPGroup_ID in DocHRProcess, to find a concept accounting regarding a business partner group.
=> # 2815 Use filter C_BPGroup_ID MConcept getConceptAcct() in DocHRProcess

client/src/org/compiere/apps/form/TrialBalanceDrill.java
Fixes https://github.com/adempiere/adempiere/issues/2797
=> adempiere  #2797 [Bug Report] Error Trial Balance

base/src/org/compiere/process/ImportBPartner.java
This pull request resolve a bug when a business partner is imported and have two users with the same email
See:
```Java
-------------------------------
===========> ImportBPartner.process: org.postgresql.util.PSQLException: ERROR: more than one row returned by a subquery used as an expression [89]
org.postgresql.util.PSQLException: ERROR: more than one row returned by a subquery used as an expression; State=21000; ErrorCode=0
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
at …
```
=> Fixed error with import bpartner

JasperReports/src/org/compiere/report/ReportStarter.java
This pull request resolve a legacy problem with paper print formats and orientation for print formats maked from iReport.
This problem happens with format like halfletter portrait
=> Resolve problem with printing margin for iReport

base/src/org/spin/process/DepositFromCash.java, base/src/org/spin/process/DepositFromCashAbstract.java, migration/392lts-393lts/05410_Add_DocumentType_Deposit_From_Cash.xml
Add Parameters fro deposit from cash Smart Browser, see image:
=> Add document type for withdrawal and deposit from cash

client/src/org/compiere/apps/form/TrialBalanceDrill.java
Fixes https://github.com/adempiere/adempiere/issues/2834
Related issue https://github.com/adempiere/adempiere/issues/2797
=> adempiere  #2834 [Bug Report] Trial Balance error in line 333

base/src/org/compiere/model/MBankAccount.java, base/src/org/compiere/model/MInvoice.java, migration/392lts-393lts/05400_Msg_BankAccountNotFound.xml
fixes https://github.com/adempiere/adempiere/issues/2823
=> adempiere  #2823  POS Order when using configuration "Cash_As_Payment"

org.adempiere.pos/src/main/java/base/org/adempiere/pos/service/CPOS.java, org.adempiere.pos/src/main/java/ui/zk/org/adempiere/pos/WPOS.java, org.adempiere.pos/src/main/java/ui/zk/org/adempiere/pos/WPOSKeyPanel.java
Fixes  https://github.com/adempiere/adempiere/issues/2819
=> #2819 WPOS PosKeylayout small adjustments

base/src/org/compiere/model/MPayment.java, base/src/org/spin/process/PaymentReturn.java, base/src/org/spin/process/PaymentReturnAbstract.java, migration/392lts-393lts/05420_Add_ProcessForPaymentReturn.xml
This process allow return a payment/receipt, deallocate all documents allocated to original payment and generates payment returned allocated to original payment.
Original Payment:
Process for create Payment Return:
Result of the process:
Open Items after Return Payment:
quick view of the process:
=> Payment Return Process

base/src/org/spin/model/MADContextInfo.java
reference to issue: https://github.com/adempiere/adempiere/issues/2769
Fixes: #2769
=> Fixed error with Sales Order Object Date errors clogging up log files,

base/src/org/spin/model/I_AD_TokenDefinition.java, base/src/org/spin/model/MADTokenDefinition.java, base/src/org/spin/model/X_AD_TokenDefinition.java, migration/392lts-393lts/05460_Change_TokenDefinition_Access_Level.xml
This pull request fixed a error with access level for token definition.
=> Fixed error with Token Definition Access Level

migration/392lts-393lts/05470_Add_Payment_Allocation_Some_Parameters.xml
This pull request add some parameters for **Allocation** report, see:
=> Add parameters for Payment Allocation Report

db/ddlutils/oracle/views/RV_C_PaySelectionDetail_Oracle.sql, db/ddlutils/postgresql/views/RV_C_PaySelectionDetail.sql, migration/392lts-393lts/05490_Add_PaymentSelectionDetail_Report.xml
This pull request add a new report for Payment selection detail:
Fixes: #2867
=> Add Payment Selection Detail report

base/src/org/compiere/model/I_M_MatchInv.java, base/src/org/compiere/model/MMatchInv.java, base/src/org/compiere/model/X_M_MatchInv.java, migration/392lts-393lts/05470_Add_Document_Type_Match_Invoice.xml
Added Document Type Field on Match Invoice, setted document type by default on before save event if don't set.
=> Add Document Type on Match Invoice

org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/model/MHRConcept.java
=> #2870 Error when try accounting payroll, can not get account data

base/src/org/eevolution/model/MDDOrder.java, migration/392lts-393lts/05460_BugFixedTheOutboundOrderFunctionality.xml, org.eevolution.manufacturing/src/main/java/base/org/compiere/acct/Doc_DDOrder.java, org.eevolution.warehouse/src/main/java/base/org/eevolution/engine/warehouse/WMRuleFIFO.java, org.eevolution.warehouse/src/main/java/base/org/eevolution/model/MWMInOutBound.java, org.eevolution.warehouse/src/main/java/base/org/eevolution/model/MWMInOutBoundLine.java, org.eevolution.warehouse/src/main/java/base/org/eevolution/process/GenerateInOutBound.java, org.eevolution.warehouse/src/main/java/base/org/eevolution/process/GenerateShipmentOutBound.java, org.eevolution.warehouse/src/main/java/base/org/eevolution/process/ReleaseInOutBound.java
Fixes #2855
Fixes #2856 
Fixes #2859 
Fixes #2860
=> WMS bug fixed

base/src/org/compiere/model/I_AD_PrintFormatItem.java, base/src/org/compiere/model/X_AD_PrintFormatItem.java, base/src/org/compiere/print/DataEngine.java, base/src/org/compiere/print/MPrintFormatItem.java, base/src/org/compiere/print/PrintDataColumn.java, migration/392lts-393lts/05500_Add_exclude_of_Total_Calculation_PrintFormat.xml
Fixes: #2873 
This pull request allows exclude a column of total calculation for a report, see gif:
=> Add Exclude of total calculation attribute for print format item

base/src/org/compiere/process/FactAcctReset.java
Currently, at reset accounting on a date range it delete the accounting by the date range, but it resets other documents that not in the date range. 
See this example
Reset Accounting Process by Invoice Documents:
Result of the Process:
Document that not must be update:
Then, at run the process for generate accounting, it duplicate the accounting records.
See this example:
Run the Client Accounting Process:
Result of the Process:
Accounting Duplicated:
For fix the bug, it's separated the validation  for accounting and period in the update sql
```
final StringBuilder updateStatement = new StringBuilder();
updateStatement
.append("UPDATE ").append(accountingDocumentTable.getTableName()).append(" SET Posted='N', Processing='N'").append(" WHERE ") …
```
=> Fix on Accounting Reset Process

base/src/org/spin/process/PaymentIdentify.java
This pull request allows compare two payments for identify based on currency precision
=> Apply round mode for identity payment with a existing payment

migration/392lts-393lts/05510_Add_Consolidate_Document_Flag.xml, org.eevolution.warehouse/src/main/java/base/org/spin/process/GenerateInvoiceInOutBound.java, org.eevolution.warehouse/src/main/java/base/org/spin/process/GenerateInvoiceInOutBoundAbstract.java
This PR allows generate a invoice from many Sales Orders from same business partner, note that is added a new flag for consolidate all document.
Is nice for customers with invoices with many orders. See pic:
=> Add consolidate document flag for smart browser "Generate Invoice from

org.eevolution.warehouse/src/main/java/base/org/eevolution/model/MWMInOutBound.java
This pull request allows reverse receipt generated from Express receipt if source express receipt is voided, also allows validate remaining quantity from Order before gebnerate receipt
=> Add reverse receipt from receipt express

base/src/org/compiere/model/MPInstance.java, base/src/org/compiere/model/MPInstancePara.java, base/src/org/eevolution/service/dsl/ProcessBuilder.java
Add support to process parameter To on process builder.
If you use ProcessBuilder and add a parameter with **From** and **To**
=> Fixed error with process parameters for process builder

adempiere.iml
=> Update the IntelliJ libraries

.classpath
Solves Issue: #2900
Change path in .classpath
Link to issue: https://github.com/adempiere/adempiere/issues/2900
=> Adempiere 3.9.3: does not compile under Eclipse

base/src/org/compiere/process/BankStatementPayment.java
Step by Step:
- Go to Bank Statement
- Add Lines
- From Bank Statement Line Tab Press Button "Create Payment" (BOM)
NPE
This pull request fixed the NPE
=> Fixed error with Null Pointer Exception when a payment is created from

base/src/org/spin/process/PaymentIdentify.java
This little change just set date of payment generated from identify process, also allows set flag as true for reconcile column when original payment is reconciled yet
Best regard
=> Set reconcile a generate payment from Identify process

base/src/org/compiere/model/MMigration.java
Fixes #1927 
Adds a parameter to the adds a parameter to the method private int[] getStepIds to flag if all ID's are returned or only the IDs relevant to the rollback parameter.  Then, if a 4000 step migration fails on first step, only one step is returned for rollback rather than 4000.
=> #2912 - Speed up the rollback of a migration

base/src/org/adempiere/engine/CostEngine.java
https://github.com/adempiere/adempiere/issues/2909
Fixes: #2909
=> adempiere #2909 ClearAccounting does not work for Project Issues

base/src/org/spin/util/ASPUtil.java
Currently not exist translatio for commit warning of tab when is called from ASP, this pull request resolve it.
=> Add support to commit warning for Tab ASP

client/src/org/compiere/apps/form/Match.java, client/src/org/compiere/apps/form/VMatch.java, zkwebui/WEB-INF/src/org/adempiere/webui/apps/form/WMatch.java
On matching window for invoice or order and receipt and the quantities for both documents have decimals, the document of matching is register with a different quantity by decimals.
for fix the problem was changed the quantity field from double to BigDecimal.
See this example:
Invoice document with quantity 23.65 and receipt with 36.87
After create the match document, the invoice remains pending for assigned.
On the matched invoice window appear with quantity assigned 23.65
The query sql returns:
Matched invoice, after the change
After create the match document, the invoice is not pending for assigned.
The query sql returns:
=> Changing from double to BigDecimal for major precision on Matching

.travis.yml
Just a little change for travis and ADempiere 393LTS release
=> Add binary for 3.9.3 ADempiere

migration/393lts-394lts/05550_2943_FixTheFilterDocTypeAndParaTargetDocType.xml, org.eevolution.warehouse/src/main/java/base/org/spin/process/GenerateInvoiceInOutBound.java
solve issue #2942
solve issue #2943
=> The incorrect price when an invoice is generated from Generate Invoice From Outbound #2942

base/src/org/adempiere/engine/CostEngine.java
Change get client, on method create cost detail  for use cache and to get better response time
=> Use Cache for get Client on Cost Engine

base/src/org/compiere/model/MProductionBatch.java
This pull request make a validation for production batch when is voided if exists some production not reversed or voided
=> Fixed error with validation for production batch when exists productions

org.adempiere.request/src/main/java/org/compiere/model/MRequest.java
https://github.com/adempiere/adempiere/issues/3002
=> adempiere  #3002 bugfix NPE in MRequest save

base/src/org/spin/util/ASPUtil.java
Step by Step:
- Create a new ASP process (as overwrite)
- Select a inactive parameter of process
- Change values from ASP for parameter
Note that inactive parameters is not overwrite to active
This pull request resolve it
=> Fixed error with overwrite parameters for process and smart browsers

base/src/org/compiere/acct/Doc_Production.java
https://github.com/adempiere/adempiere/issues/2993
=> adempiere #2993 Doc_Production: M_Locator_ID is not updated correctly

.classpath
This pull request add TNA as source folder for eclipse IDE
=> Add source folder for TNA

migration/392lts-393lts/05510_DeactivateUnusedMenu.xml
fixes https://github.com/adempiere/adempiere/issues/2880
=> adempiere #2880 [Bug Report]2880 Not defined process

base/src/org/compiere/util/TimeUtil.java, org.eevolution.hr_and_payroll/src/main/java/base/org/spin/util/TNAUtil.java
This pull request add support to get duration based on Week, currently exists only:
- Month = M
- Day = D
- hour = h
- minute = m
- second = s
=> Add support to duration based on week

base/src/org/compiere/model/MInvoiceLine.java
Fixes https://github.com/adempiere/adempiere/issues/3000
=> Support for LandedCostDistribution

base/src/org/compiere/process/StatementCreateFrom.java
Fixes https://github.com/adempiere/adempiere/issues/3024
=> Process StatementCreateFrom, amount in different currency is calculcated with an error

base/src/org/compiere/model/CalloutInvoice.java, base/src/org/compiere/model/CalloutOrder.java, base/src/org/compiere/model/MInvoiceLine.java, base/src/org/compiere/model/MOrderLine.java
reference to issue: https://github.com/adempiere/adempiere/issues/2975
Fixes: #2975
=> #2975, Fixed error with round for AP / AR documents and Orders,

base/src/org/adempiere/pipo/handler/GenericPOHandler.java
This pull request make reference for table name instead id for packin.
With it pull request a table for import data is finded from table name.
=> Fixed error with reference for table for packin

base/src/org/compiere/model/I_I_BPartner.java, base/src/org/compiere/model/MBPBankAccount.java, base/src/org/compiere/model/MBPartnerLocation.java, base/src/org/compiere/model/X_I_BPartner.java, base/src/org/compiere/process/ImportBPartner.java, migration/392lts-393lts/05550_Add_Support_to_Import_Business_Partner_Bank_Account.xml, migration/393lts-394lts/05570_Add_Support_to_Import_Business_Partner_Bank_Account.xml
Add support to import Business Partner Bank Accounts and support more than one business partner location.
sample:
Currently has not support to import business partner with more than one location, see this example after change:
=> Add support to import Business Partner Bank Account

base/src/org/compiere/process/InOutGenerate.java, base/src/org/compiere/process/InOutGenerateAbstract.java
Minor change add abstract class for generatin InOut class
=> Generate abstract class for process generate in out

base/src/org/compiere/model/CalloutOrder.java, base/src/org/compiere/model/I_C_Invoice.java, base/src/org/compiere/model/I_C_Order.java, base/src/org/compiere/model/MInvoice.java, base/src/org/compiere/model/MOrder.java, base/src/org/compiere/model/X_C_Invoice.java, base/src/org/compiere/model/X_C_Order.java, migration/393lts-394lts/05590_1455_Add_Sales_Region_to_Order_and_Invoice.xml
=> Add support to Sales region for Sales Order and Invoice

base/src/org/spin/model/I_AD_CleanDefinition.java, base/src/org/spin/model/I_AD_CleanDefinitionTable.java, base/src/org/spin/model/X_AD_CleanDefinition.java, base/src/org/spin/model/X_AD_CleanDefinitionTable.java, client/src/org/compiere/apps/form/DeleteEntityControler.java, client/src/org/compiere/apps/form/VDeleteEntity.java, migration/393lts-394lts/05570_Add_Clean_Definition_for_Client.xml, zkwebui/WEB-INF/src/org/adempiere/webui/apps/form/WDeleteEntity.java
This pull request allows define more than one table for delete using Clean Definition window, see gif
=> Add clean definition for delete entities

base/src/org/compiere/model/MPaySelectionCheck.java, base/src/org/compiere/model/MPaySelectionLine.java
Fixes https://github.com/adempiere/adempiere/issues/2995
=> adempiere Payselection for Bank Transfers. Charge is not copied. PayAmt>Open Amount for invoices

base/src/org/compiere/model/CalloutOrder.java, base/src/org/compiere/model/MInvoice.java, base/src/org/compiere/model/MOrder.java, base/src/org/compiere/model/MSalesRegion.java
=> Add support to Sales representative based on sales region

base/src/org/spin/model/MADAppRegistration.java, base/src/org/spin/model/MADAppRegistrationPara.java
This pull request allows reset cache after save or delete a parameter of app registration
=> Reset cache for App registration when a value is changed

zkwebui/WEB-INF/src/org/adempiere/webui/apps/graph/WDocumentStatusIndicator.java, zkwebui/WEB-INF/src/org/adempiere/webui/apps/graph/WDocumentStatusPanel.java
The problem is that a event for open window from row of Dashboard Pending Documents compare distints object
=> Fixed error with event indicator for pending documents

base/src/org/adempiere/pipo/handler/MenuElementHandler.java
This pull request resolve a problem exporting a application or module, the follows are step for reproduce bug:
- Create a Packout
- Create a new line with export type "Application or Module"
- Select a Menu option (no summary, just a menu option like report or new window)
- Export it
- Import package in other database
- Note that is imported report and menu but the menu does not have reference to report or window
=> Fixed error with wrong reference for export menu from application or

base/src/org/compiere/model/I_I_Inventory.java, base/src/org/compiere/model/X_I_Inventory.java, base/src/org/compiere/process/ImportInventory.java, migration/392lts-393lts/05580_Add_Attribute_set_instance_search_for_import_inventory.xml, migration/393lts-394lts/05580_Add_Attribute_set_instance_search_for_import_inventory.xml
This pull request allows add support to Attribute set instance for import inventory, note that you can import and make match for attribute set instance now:
=> Add support to import attribute set instance for import inventory

base/src/org/eevolution/process/ValuationEffectiveDate.java
fixes https://github.com/adempiere/adempiere/issues/1662
Fixes: #1502
=> adempiere  #1662 ValuationEffectiveDate only for costing level warehouse

base/src/org/compiere/process/SvrProcess.java
The problem: I modified a process by ASP:
- Process customization
- Create a new
- Select a process with mandatory parameter
- Go to process parameter and change a attribute from **IsMandatory** = true to **IsMandatory** = false
- As Garden run process and note that the mandatory parameter is now optional
- When run it return a error of validation
This pull request fixed validationparamameter with ASP
=> Fixed error with overwrite parameters for process when they are changed

base/src/org/compiere/model/I_M_DiscountSchemaLine.java, base/src/org/compiere/model/X_M_DiscountSchemaLine.java, base/src/org/compiere/process/M_PriceList_Create.java, base/src/org/compiere/process/M_PriceList_CreateAbstract.java, migration/393lts-394lts/05760_Add_Product_Class_and_Classification_for_Price_List_Calc.xml
This pull request allows define:
- Product Group
- Product Class
- Product Classification
As Query criteria for Price List calculation.
Also the process was improve for minor time of processing... Wow 8.200 records in two seconds.
Note: The main problem was a sub-query for currencyConversion function
=> Add Product Group, Product Class and Product Classification for Price

base/src/org/compiere/process/InvoiceGenerate.java, base/src/org/compiere/process/InvoiceGenerateAbstract.java
Just a minor change for old process, remove save method and change for saveEx, also is improve the use of **Selection** attribute by **IsSelection** from parent process.
Also is added Abstract class for it
=> Remove old implementation for save and selection

migration/393lts-394lts/05730_Add_Tender_Types_for_Payments.xml
This pull request just add more tender type for payment, see:
=> Allows more tender types for payments

base/src/org/adempiere/pipo/PackOut.java
This pull request allows export packout from ZK UI, see gif
=> Allows export Packout from ZK web UI

migration/393lts-394lts/05770_Add_C_ConversionType_C_POS.xml, migration/393lts-394lts/05780_Add_supportto_currency_for_Withdrawal.xml, org.adempiere.pos/src/main/java/base/org/adempiere/pos/process/GenerateWithdrawal.java
This pull request allows define conversion type for POS and make transaction multy-currency for Withdrawal and collets
=> Allows multy-currency for POS Withdrawal

org.adempiere.asset/src/main/java/base/org/compiere/FA/model/ModelValidator.java
Just a little change for code
before
```Java
save();
```
after
```Java
saveEx();
```
=> Remove old implementation for save method

base/src/org/compiere/model/I_A_Asset_Delivery.java, base/src/org/compiere/model/X_A_Asset_Delivery.java, migration/393lts-394lts/05780_3085_Add_Delivery_Asset_Browser.xml, org.adempiere.asset/src/main/java/base/org/compiere/model/MAssetDelivery.java, org.adempiere.asset/src/main/java/base/org/compiere/process/AssetDelivery.java, org.adempiere.asset/src/main/java/base/org/compiere/process/AssetDeliveryAbstract.java
Fixes: #3085
This pull request allows deliver many assets from browser. See Gif:
Best regards
=> Add support to Deliver Asset Browser

base/src/org/spin/process/ExportFormatCreateFromTable.java, base/src/org/spin/process/ExportFormatCreateFromTableAbstract.java, migration/393lts-394lts/05780_Add_SB_Create_From_Table_Export_Format_Replication.xml
This pull request add a Smart Browser for Create Export Fromat Lines from Table selected on header, see gif:
=> Add Smart Browser for Create Export Format Lines from Table selected on

base/src/org/eevolution/model/I_HR_Process.java, base/src/org/eevolution/model/X_HR_Process.java, migration/393lts-394lts/05800_Add_Search_Criteria_for_Employee_from_HR_Process.xml, org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/model/MHREmployee.java, org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/model/MHRProcess.java
This pull request allows define a payroll process for calculate for all employees of all organization, just defina a payroll process as **_*_** and is getted all employees on payroll.
Best regards
=> Add support to calculate payroll process for all organization

base/src/org/eevolution/process/ValuationEffectiveDate.java, base/src/org/eevolution/process/ValuationEffectiveDateAbstract.java, migration/393lts-394lts/05670_Add_Last_Price_PO_For_Valuation_Report.xml
This pull request allow get reference from last PO Price for Valuation report and compare with Price list version
=> Add changes for Valuation report

data/de_DE/AD_Menu_Trl_de_DE.xml, data/de_DE/AD_Window_Trl_de_DE.xml
Hi @yamelsenih , @marcalwestf 
this is an update with de_DE translations based on adempiere-3.9.3
regards EUGen
=> de_DE translation update for Menu and Window

base/src/org/spin/util/AttachmentUtil.java
This pull request allows get a resource from a attachment reference id
=> Get Resource from Attachment reference

base/src/org/adempiere/engine/CostEngine.java, base/src/org/compiere/acct/Doc_Invoice.java, base/src/org/compiere/model/MLandedCostAllocation.java
Reverts adempiere/adempiere#3094
I revert temporality to try other implementation @carlosaparadam , @marcalwestf  , @yamelsenih
=> Revert "Fix Landed Costs Accounting, when Vendor invoice is in another currency"

base/src/org/compiere/model/MAttachment.java, base/src/org/compiere/model/MImage.java, base/src/org/spin/model/I_AD_AttachmentReference.java, base/src/org/spin/model/X_AD_AttachmentReference.java, base/src/org/spin/util/AttachmentUtil.java, migration/393lts-394lts/05820_Add_File_Size_to_Attachment_Reference.xml
This is a pull request for add information about file on Attachment reference. The file size is very important for know how long is the download file or resource from external API
=> Add support to File Size for Attachment reference

org.eevolution.hr_and_payroll/src/main/java/base/org/spin/process/PayrollProcessReport.java
This pull request implement ProcessBuilder for Payroll Process Report, also allows get report as file from generated report
=> This change allows return report as file for get this on any UI

base/src/org/compiere/process/ProcessInfo.java, base/src/org/compiere/process/ServerProcessCtl.java, base/src/org/eevolution/service/dsl/ProcessBuilder.java, client/src/org/compiere/apps/ProcessCtl.java, org.eevolution.manufacturing/src/main/java/ui/swing/org/eevolution/form/OrderDistribution.java
=> Fixed error with duplicated key for ServerProcessCtl

base/src/org/compiere/model/MFieldCustom.java, base/src/org/spin/process/ASPCopyFromTab.java, base/src/org/spin/process/ASPCopyFromTabAbstract.java, migration/393lts-394lts/05840_Add_ASP_Copy_from_Customized_Tab.xml
Just a process that allows copy values from all fields of a custom tab. this process is very useful when a user want to define changes for a tab based on other tab that already exist andwas customized.
See gif:
=> Add process for copy custom fields from other custom tab

org.eevolution.hr_and_payroll/src/main/java/base/org/spin/process/PayrollProcessReport.java
The last change for Payroll process report was for return a PDF file, I missing print preview for report
I apologize for this omission
Related to: #3139
=> Fixed print preview for reports

base/src/org/spin/model/MADAppRegistration.java
Add method for get all application registration parameters 
```
public Map<String, MADAppRegistrationPara> getAllParameters(){
if (parameters== null)
loadParameters();
return parameters;
}
```
=> Add method for get all parameters for application registration

base/src/org/spin/process/CopyWindowFromRole.java, base/src/org/spin/process/CopyWindowFromRoleAbstract.java, migration/393lts-394lts/05860_Add_Role_Copy_From_Window.xml
Just a little change, now you can copy windows from other role... Very easy, see the gif:
=> Add new Smart Browser for Copy Window from Role

db/ddlutils/oracle/views/RV_INOUTDETAILS.sql, db/ddlutils/postgresql/views/RV_INOUTDETAILS.sql, migration/393lts-394lts/05920_Fixed_Return_Quantity_for_Shipment_Details_report.xml
This pull request resolve a little error with **Shipment Details** report.
- Generate a Shipment for customer with a product with 10 quantities 
- Generate a Return from customer with a product with 3 quantities the same product
- Run Shipment Detail Report
| Document No | Product | Quantity |
| --- | --- | --- |
| D-001 | Back Support | 10 |
| R-001 | Back Support | -3 |
| Document No | Product | Quantity |
| --- | --- | --- |
| D-001 | Back Support | 10 |
| R-001 | Back Support | 3 |
=> Fixed error with return material for Shipment Details report

db/ddlutils/oracle/views/RV_C_INVOICE.sql, db/ddlutils/oracle/views/RV_C_INVOICELINE.sql, db/ddlutils/postgresql/views/RV_C_INVOICE.sql, db/ddlutils/postgresql/views/RV_C_INVOICELINE.sql, migration/393lts-394lts/05910_Add_Document_Base_Type_Invoice_View.xml
This pull request just add some parameters for:
- Invoice Line, Detil & Margin
- Invoice Summary
=> Add some parameters for Invoice summary and detail

base/src/org/eevolution/service/dsl/ProcessBuilder.java, serverRoot/src/main/server/org/compiere/server/Scheduler.java
Step for reproduce:
- Create a new Scheduler
- Set a report like Invoice Summary (Doc)
- Set Parameters:
- DateInvoiced: @#Date@
- IsSOTrx = Y
- DocStatus = CO
- Save
When it is running the default value for DateInvoiced is send without parse to parameter.
I just change it for **ProcessBuilder** instead and is ok
Before change:
After change:
=> Fixed error with default values for scheduler parameters

base/src/org/adempiere/pipo/handler/GenericPOHandler.java
- Create a Smart Browser
- Add Browser fields
- Add a new Element and set it in a browser field
- Export it with Packout
After it in a clear install:
- Import Browser from packin
- Note that it can't import
The elements never are exported
=> Fixed error with export element from Smart Browser

base/src/org/spin/process/CopyBrowserFromRole.java, base/src/org/spin/process/CopyBrowserFromRoleAbstract.java, migration/393lts-394lts/05870_Add_Role_Copy_From_Browser.xml
A simple Smart Browser for allows copy Smart Browsers from other role. Very easy and useful, see:
=> Add support to copy role from other for Browser

base/src/org/spin/grid/BrowseAxisColumnSelection.java, base/src/org/spin/grid/BrowseCreateFromDocumentAction.java, base/src/org/spin/process/CreateRoleFromDocumentAction.java, base/src/org/spin/process/CreateRoleFromDocumentActionAbstract.java, migration/393lts-394lts/05890_Add_Document_Actions_to_Role.xml
This is a great functionality for add document actions easy to role, see gif:
Please approve this first: #3164
=> Add new Smart Browser for add document Actions to Role easy

base/src/org/compiere/model/MInvoice.java, migration/393lts-394lts/05930_Add_Conversion_Rate_Message.xml
This pull request just add message to currency conversion of documents
=> Add Conversion message for dictionary

base/src/org/compiere/model/MProcessCustom.java, base/src/org/compiere/model/MProcessParaCustom.java, base/src/org/spin/process/ASPCopyProcessFrom.java, base/src/org/spin/process/ASPCopyProcessFromAbstract.java, migration/393lts-394lts/05940_Add_Copy_Process_From_ASP.xml
This feature allows copy many customized process from other ASP Level, see the gif:
=> Feature for allows copy process from other ASP

base/src/org/compiere/model/MBrowseCustom.java, base/src/org/compiere/model/MBrowseFieldCustom.java, base/src/org/spin/process/ASPCopyBrowserFrom.java, base/src/org/spin/process/ASPCopyBrowserFromAbstract.java, migration/393lts-394lts/05950_Add_Copy_Browser_From_ASP.xml
This feature allows copy many customized browser from other ASP Level, see the gif:
Note: this Pull Request depends of: #3168
=> This feature allows copy a browser from other ASP Level

base/src/org/compiere/model/MTabCustom.java, base/src/org/compiere/model/MWindowCustom.java, base/src/org/spin/process/ASPCopyWindowFrom.java, base/src/org/spin/process/ASPCopyWindowFromAbstract.java, migration/393lts-394lts/05960_Add_Copy_Window_From_ASP.xml
This feature allows copy many customized window from other ASP Level, see the gif:
Note: this Pull Request depends of: #3168
=> Add Smart Browser for copy window from ASP

base/src/org/compiere/model/MSession.java, base/src/org/compiere/model/PO.java, base/src/org/spin/process/CloseExpiredSessions.java, base/src/org/spin/process/CloseExpiredSessionsAbstract.java, migration/393lts-394lts/05960_Close_Expired_Session_Process.xml
A simple process that can be used for closed expired sessions:
=> Close Expired Session

base/src/org/spin/process/DeleteTemporaryTables.java, base/src/org/spin/process/DeleteTemporaryTablesAbstract.java, migration/393lts-394lts/05970_Delete_Temporary_Table_Process.xml
Just a maintenance process for delete temporary tables:
=> Add process for delete temporary tables

base/src/org/compiere/model/PO.java
from session and changelog, this pull request prevent this behavior
This pull request fix  a error introduced on #3174 for change role functionality.
=> After chage done on #3174 is possible that can exists a recursive call

base/src/org/adempiere/util/ProcessUtil.java, base/src/org/compiere/wf/DocWorkflowManager.java, base/src/org/compiere/wf/MWFActivity.java, base/src/org/compiere/wf/MWFProcess.java, base/src/org/compiere/wf/MWorkflow.java, base/src/org/compiere/wf/WFActivityManage.java, base/src/org/compiere/wf/WFActivityManageAbstract.java, base/src/org/compiere/wf/WFProcessManage.java, base/src/org/compiere/wf/WFProcessManageAbstract.java, extend/src/test/functional/WorkflowTest.java
=> Bug Report The workflow engine is not correctly handling transactions when processing documents 

migration/393lts-394lts/05910_Add_Document_Base_Type_Invoice_View.xml
Just a simple change for remove step failed from import based on previous Pull Request #3158
=> Fixed error with constraint for column name of sequence no

base/src/org/adempiere/pipo/PackIn.java, base/src/org/adempiere/pipo/PackInHandler.java, base/src/org/adempiere/pipo/handler/GenericPOHandler.java, base/src/org/compiere/model/I_AD_Package_Imp_Proc.java, base/src/org/compiere/model/X_AD_Package_Imp_Proc.java, base/src/org/compiere/util/ImpExpUtil.java, migration/393lts-394lts/06410_Add_Attribute_for_synchronize_columns_from_Packout.xml
This pull request allows define if a packing synchronize columns or not. Is very useful when a packing is used for generate XML with develop mode:
=> Add support to new attribute for packing import without synchronize

db/ddlutils/oracle/functions/C_Currency_Base_Type.sql, db/ddlutils/postgresql/functions/C_Currency_Base_Type.sql, migration/393lts-394lts/06200_Fixed_conversion_base_function.xml
Currently the currencyBase function don't allows set the conversion type from document.
=> Fixed error with currencyBase function

base/src/org/spin/process/DepositFromCash.java
When a cash have collects with multiple currencies, the deposits from cash are always in bank currency. This is a bug because all collets can be in many currencies.
The withdrawal and deposit should be depending of currency and conversion type.
After this change the cash detail reposrt should be like it:
Deposit based on complete collects:
Deposit based on Split for collects
ma
=> Fixed error with deposit from cash when exist collects with

org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/process/SendPayrollReceiptByEmail.java
This pull request allows the folow:
- Search eMail by location (Currently)
- Search eMail by Bank Account of business partner selected from payment
- Search eMail by default bank account
- Search eMail by default user with EMail Notification or EMail Notification + Notice Type
close #3202
=> Allows send mail to employee from bank account email and user

client/src/org/compiere/grid/VPanel.java
Hi @marcalwestf : this is a patch for bug issue #3124
Pls review & commit
regards EUGen
=> #3124 - bug in VPanel.getMnemonic resolved

base/src/org/eevolution/process/GenerateInvoiceFromPayment.java
Open https://github.com/adempiere/adempiere/issues/3046
=> #3046 Process to Create Invoice from Payment online

base/src/org/spin/model/I_FM_Batch.java, base/src/org/spin/model/X_FM_Batch.java, migration/393lts-394lts/06510_Add_Accounting_Date_to_FM_Batch.xml, org.spin.finance_management/src/main/java/base/org/compiere/acct/Doc_FMBatch.java
Just add **DateAcct** column to **FM_Batch** table
=> Add Date Acct to Financial Batch

migration/393lts-394lts/06490_Increase_Business_Partner_Name_and_Name_2.xml
The business partner name have just 60 characters as length, this pull request aloows increase it to 255
Changes:
- Name: to 255
- Name 2: to 255
=> Increase Business Partner Name and Name2 to 255

migration/393lts-394lts/06560_Add_Report_View_for_Cash_waiting_for_Deposit.xml
This new Report view allows show all cash collect waiting for a Deposit from cash, is very useful for find open collects from cash
=> Add Report View for show Cash waiting for Deposit

base/src/org/compiere/model/I_T_Aging.java, base/src/org/compiere/model/MAging.java, base/src/org/compiere/model/X_T_Aging.java, base/src/org/compiere/process/Aging.java, base/src/org/compiere/process/AgingAbstract.java, migration/393lts-394lts/06490_Add_some_columns_for_Aging_report.xml
Jus add two for Aging report: Days Due 8-14 ~ 15-30 and Past Due 8-14 ~ 15-30
=> Add support to Days Due 8-14 ~ 15-30 and Past Due 8-14 ~ 15-30

db/ddlutils/oracle/views/RV_OPENITEM.sql, db/ddlutils/postgresql/views/RV_OPENITEM.sql, migration/393lts-394lts/06490_Add_Parameter_Sales_Region_Open_Item.xml
Jus add sales region for Open Item report
=> Add support to sales region for Open Item

base/src/org/spin/report/OpenItemToDate.java, base/src/org/spin/report/OpenItemToDateAbstract.java, migration/393lts-394lts/06500_Add_Parameter_SalesRegion_Open_Item_To_Date.xml
Just add some columns to Open Item to Date
=> Add columns to Open Item to date

org.spin.store/src/main/java/org/spin/process/ExportCatalog.java
Just a bufix for Store from ADempiere
=> Rename table for implementations of W_Catalog

base/src/org/compiere/model/MInvoice.java
- Create a Sales Order POS
- Complete it
A error is generated: No Cash Book
- Change System configurator flag "CASH_AS_PAYMENT" to Y
- Try one more time
A error is generated: No Cash Book
- Create a Bank As Cash
- Add a default account (same organization)
- Try one more time
A error is generated: No Cash Book
Always is validate Cash Journal instead
=> Fixed error with Sales Orders with cash as payment rule

base/src/org/compiere/wf/MWFActivity.java
=> Fixed error with transaction for Workflow approval

base/src/org/compiere/model/MTable.java
This functionality allows create Element based on tablename instead tablename + id
=> Remove ID for Reference of Element created automatically

JasperReports/src/org/compiere/report/ReportStarter.java
- Add support to AD_Org_ID as standard column
- Add <ColumnName>_Info_To value for parameters report
=> Add standard values for iReport

base/src/org/compiere/model/Query.java
Just add a new method for get ids from query
```
getIDsAsList()
```
The return value is a List<Integer>
=> Minor change: Allows get ids of query as list instead array

base/src/org/spin/process/rpl/exp/TestReplicationStrategy.java
Add implementation of getIDsAsList() method
A first implementation for #3255
=> Improve speed for test replication strategy

base/src/org/eevolution/process/BankTransfer.java, base/src/org/eevolution/process/BankTransferAbstract.java, base/src/org/spin/process/DepositFromCash.java, base/src/org/spin/process/DepositFromCashAbstract.java, migration/393lts-394lts/06950_Add_Tender_Type_for_Bank_Transfer.xml
Just add support to tender type (optional) for bank transfer
=> Add support to tender type for bank transfer

base/src/org/compiere/model/MConversionRate.java
A little change but allows validate Conversion rates for **IsActive** flag
=> Fixed error with conversion rate based on is active value

base/src/org/spin/util/ThirdPartyAccess.java
Just add random UUID for Token based on third party access
=> Just generate token based on random UUID

base/src/org/compiere/process/M_PriceList_Create.java, base/src/org/compiere/process/M_PriceList_CreateAbstract.java, migration/393lts-394lts/07050_Add_Filter_values_for_Price_List_Create.xml
Just add some parameters for Price List Create From process
=> Add parameters for create price list

base/src/org/spin/process/DepositFromCash.java, base/src/org/spin/process/DepositFromCashAbstract.java, migration/393lts-394lts/07080_Add_Is_Auto_Reconcile_flag_for_deposit_from_cash.xml
Add support to autoreconcile payment for deposit from cash
=> Add autoreconcile support for deposit from cash

base/src/org/compiere/model/MBankStatement.java, base/src/org/compiere/model/MPayment.java
Thyis pull request validate duplicated lines for bank statement
=> Fixed error with duplicated lines for bank statement

base/src/org/adempiere/util/rpl/EntityWrapperFactory.java
When a export format line is **Referenced Format** based it never return value to main object. This pull request allows return value if it have some
=> Fixed error with reference id when a export format is referenced

base/src/org/compiere/model/I_C_OrderLine.java, base/src/org/compiere/model/MInvoiceLine.java, base/src/org/compiere/model/MOrder.java, base/src/org/compiere/model/MOrderLine.java, base/src/org/compiere/model/X_C_OrderLine.java, base/src/org/spin/process/OrderRMACreateFromInvoice.java, base/src/org/spin/process/OrderRMACreateFromInvoiceAbstract.java, migration/393lts-394lts/05770_Add_Support_to_Reference_Invoice_Line_for_Return_Order.xml
This pull request allows define a process for create Return Material Order from a invoice using **Ref_InOutLine_ID** from Invoice, also allows create Return order for POS when it are not delivered.
The use, just calling from source code with role authorization
=> A new process for create RMA from Invoice instead delivery

base/src/org/compiere/print/layout/ImageElement.java
Resize image before load for improve memory consumption
=> Just resize image for reduce memory consumption

migration/393lts-394lts/06490_Add_Parameter_Sales_Region_Open_Item.xml
Fixes #3298 
Simply adds a release number to migration script 06490 Add Parameter Sales Region in Open Item.
=> 3298 Add Release No to migration script serial 06490

base/src/org/compiere/model/MPayment.java, base/src/org/spin/process/DepositFromCash.java, migration/393lts-394lts/07240_Change_Deposit_from_Cash_References.xml
- Remove null validation for cash
- Prevent unseteable value for Ref_Payment_ID
=> Prevent unseteable value for Ref_Payment_ID

base/src/org/spin/model/I_AD_SetupDefinition.java, base/src/org/spin/model/I_AD_SetupLog.java, base/src/org/spin/model/MADSetupDefinition.java, base/src/org/spin/model/MADSetupLog.java, base/src/org/spin/model/X_AD_SetupDefinition.java, base/src/org/spin/model/X_AD_SetupLog.java, base/src/org/spin/process/FunctionalitySetupProcess.java, base/src/org/spin/process/FunctionalitySetupProcessAbstract.java, base/src/org/spin/setup/SpinContributionTestSetup.java, base/src/org/spin/util/ISetupDefinition.java, base/src/org/spin/util/SetupUtil.java, migration/393lts-394lts/07230_Add_Setup_Definition_for_client.xml, migration/393lts-394lts/07240_Add_Test_data_for_Functionality_Setup.xml
- Setup Definition
- Setup Log
- Setup Process
A example using **org.spin.setup.SpinContributionTestSetup**
- Allows define initial setup for a new functionality
- Allows create test data for testing 
This process allows define many setup similar to **Initial Client Setup** but more dynamic
Replace: #3250
=> Add functionality setup for based on testing class

migration/393lts-394lts/07240_Add_Tab_for_Social_Media_to_Business_Partner.xml
=> Add tab for Social Media to Business Partner

base/src/org/compiere/model/MPaySelectionLine.java, base/src/org/compiere/process/PSCreateFromHRMovement.java
- Create a new Payment Selection header
- Go to process Create from Invoice
- Select a Invoice
- Press Ok
=> Prevent NPE for Create From on Payment Selection

base/src/org/compiere/model/MTable.java
This pull equest implement cache for **MTable.getTable_ID(String tableName)** method
=> Just Implement Cache for get Table ID based on table name

base/src/org/compiere/model/MConversionRate.java
Currently the conversion rate does not have search criteria for isActive
value, also the rate not support big values using double instead
BigDecimal object
=> Fixed error with conversion rate for isActive search and decimal

base/src/org/spin/model/I_AD_UserSocialMedia.java, base/src/org/spin/model/MADUserSocialMedia.java, base/src/org/spin/model/X_AD_UserSocialMedia.java
Just a improve for add helper method to social media model class
=> Add helper method for Social Media Model Class

base/src/org/compiere/acct/Doc.java
Currently when it has more than one accounting schema and any document with the flag reversal with original accounting is reversed, the reversal document posted with the records duplicated.
- [Create a new Accounting Schema](#created-a-new-accounting-schema)
- [Create a element on the new Accounting Schema for the Accounting Element](#created-a-elementon-the-new-accounting-schema-for-the-accounting-element)
- [Copy setting for the new accounting schema](#copy-setting-for-the-new-accounting-schema)
- [Copy account from Accounting Schema](#copy-account-from-accounting-schema)
- [Find the Business Partner Group "Vendors" and copy accounts to related Business Partner for the new Accounting Schema](#copy-accounts-for-related-business-partner-for-the-new-accounting-schema)
- [Find the Product …
=> Fixed duplicate posting using document type flag with reversal with original accounting

migration/393lts-394lts/06870_Add_Third_Party_Access_Token_Generator.xml
The problem is that exist a step updating a field that is inserted after
it.
This pull request just reorder the wrong step
=> Reorder step sequence for XML

migration/393lts-394lts/06730_Add_references_to_Financial_Management.xml
This pull request just resolve a wrong reference for validation rule on
Financial Management for resolve the "Partially Applied" status for XML
06730_Add_references_to_Financial_Management.xml
=> Fixed error with wrong reference for validation rule

migration/393lts-394lts/07250_Fixed_translation_for_summary_menu.xml
Some summary menu was not exported when translation is exported
This pull request just change Is Centrally Maintained for these menu
=> Minor change fixed error with summary translation

base/src/org/compiere/model/MStorage.java, migration/393lts-394lts/07010_Add_ID_for_Storage.xml
Juas add **M_Storage_ID** column for **M_Storage** table
=> Add ID for M_Storage Table

base/src/org/compiere/model/I_M_ProductPrice.java, base/src/org/compiere/model/MProductPrice.java, base/src/org/compiere/model/X_M_ProductPrice.java, migration/393lts-394lts/07000_Add_ID_for_Product_Price.xml
Just add **M_ProductPrice_ID** for **M_ProductPrice** table
=> Add ID for Product Price

migration/393lts-394lts/07260_Add validation for Agreement on Documents.xml
Just add a validation for agreement of business partner on documents:
- Invoice
- Order
- Payment
=> Add Validation for Business Partner to Agreement on document

base/src/org/compiere/model/I_AD_Scheduler.java, base/src/org/compiere/model/X_AD_Scheduler.java, migration/393lts-394lts/07380_Add_Support_to_Run_one_time_for_Schedule.xml, serverRoot/src/main/server/org/compiere/server/AdempiereServer.java, serverRoot/src/main/server/org/compiere/server/AdempiereServerMgr.java
This pull request add support to the follows frequencies to Scheduler
- Second
- Does Not Repeat
- Weekly
- Monthly
- Yearly
Also allows define custom Date Next Run for a Schedule
A example for only a run of schedule
=> Scheduler Add support to frequency type:

migration/393lts-394lts/07390_Add_Financial_Transaction_Detail_Report.xml
Just add a report for FM_Transaction table, this report allows show all
transaction by account
=> Add Financial Transaction Detail Report

base/src/org/compiere/util/DB.java
Just add support to generate UUID from source when getUUID() function is
missing
=> Add support to generate UUID from source

base/src/org/compiere/model/MTabCustom.java, base/src/org/compiere/model/MWindowCustom.java
This pull request allows create fields automatically on custom tabs when
a new custom tab is added
=> Allows create fields automatically when a custom tab is created

db/ddlutils/oracle/views/RV_M_Replenish.sql, db/ddlutils/postgresql/views/RV_M_Replenish.sql, migration/393lts-394lts/07130_UpdateReplenishView.xml, migration/393lts-394lts/7130_UpdateReplenishView.xml
Fixed error on quantities to replenish on Smart Browser Warehouse Replenish
=> Fix error on quantities when exist multiple organizations

tools/RUN_build.bat, tools/RUN_build.sh, utils_dev/RUN_build.bat, utils_dev/RUN_build.sh, utils_dev/RUN_build2.bat, utils_dev/RUN_build2.sh
Ant was upgraded to 1.10.9.  I forgot to update these build files.  Also refactored the dos code to make the error color go away when retrying after an error.
=> Update build files that reference the ant version.  

base/src/org/spin/model/I_FM_Transaction.java, base/src/org/spin/model/X_FM_Batch.java, base/src/org/spin/model/X_FM_Transaction.java, migration/393lts-394lts/07650_Add_Order_Line_Reference_for_Financial_Transaction.xml
Just add the follow references for **FM_Transaction** table
- C_Order_ID
- C_OrderLine_ID
=> Add Order reference to financial transaction

org.eevolution.hr_and_payroll/src/main/java/base/org/spin/util/TNAUtil.java
Just add criteria based on really dates for get leave list
=> Fixed error with search for leave

migration/393lts-394lts/07660_Change_Access_Level_for_Generate_Token_Process.xml
This pull request just change Third Party Access Access Level as
**System + Client**
=> Change Access Level for Generate Token

base/src/org/compiere/model/MProduction.java, base/src/org/compiere/model/MProductionBatchLine.java
https://github.com/adempiere/adempiere/issues/3397
=> Adempiere  #3397 Error of qtyreserved and qtyordered in MProduction

base/src/org/compiere/model/MInvoiceTax.java
Reverts adempiere/adempiere#3391
=> Revert "Feature/#3390 rounding problem calculate tax"

base/src/org/adempiere/pipo/handler/RoleElementHandler.java
Just add a flag for export role without error when is exported from
packout functionality
=> Ignore error when export role from packout

migration/393lts-394lts/07650_Add_Order_Line_Reference_for_Financial_Transaction.xml
Just remove bad step from XML
Fixes: #3372
=> Fixed error with wrong XML

base/src/org/adempiere/pipo/handler/ASPModuleElementHandler.java
Just allows export inactive ASP based on packout
=> Allows inactive records for ASP packout handler

.vscode/settings.json, base/src/org/compiere/model/MColumn.java, base/src/org/compiere/util/DisplayType.java
=> fix #3363: Field length with 0 value.

org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/model/MHRMovement.java, org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/model/MHRProcess.java
- Remove translation for message (this was changed to log with english
language)
- Add cache for agregate functions like SUM, AVG on current running
Currenlty when a payroll is running exist many conditions that make it more slow:
- Translations
- Unnecessary Query's
- Bad calling
I add some homogeneus methods:
```Java
// For amount and Quantity
getLastConcept (concept, payroll); // Get Payroll Document Date and search a Valid To
getLastConcept (concept, payroll, date); // Search with Valid To
getLastConcept (concept, payroll, date, useValidFrom); // true for search based on Valid From and false for search based on Valid To
// For Service Date
getLastConceptDate (concept, payroll); // Get Payroll Document Date and search a Valid To
getLastConceptDate (concept, payroll, date); // Search …
```
=> Improve performance for running payroll process:

base/src/org/adempiere/model/MDocumentStatus.java
Currently the document status indicator does not make query based on
role access and can show locked record
=> Add role access to document status indicator

base/src/org/compiere/model/MDistributionLine.java
…rom the account statement and immediate posting https://github.com/adempiere/adempiere/issues/3430
=>  #3430 [Bug Report] Transaction blocking error when creating account distribution and immediate posting

base/src/org/compiere/model/MPayment.java
- Create a Payment and complete: Amount **USD 1500**
- Add payment to bank statement: Account balance **USD 1500**
- Reverse payment
- See the account balance: **USD 1500**
- See Payment Details (parameter Is Reconciled true) report: **USD
1500**
After reverse it is created other payment as reversal (it is ok) the
problem is that the original payment and reversal is flagged as un
reconciled.
- The Account balance is of **USD 1500**
- The Payment Details with flag Is Reconciled as true: **USD 0**
Both must match but is not really
Both (Bank Balance and Payment details as reconciled) must be **USD
1500**, the reversed payment will should be flagged as not reconciled
instead and it can be available for reconciled with a new bank
statement.
the allocate flag is not set after reversed for both …
=> Fixed error with inconsistency of payment

base/src/org/adempiere/util/rpl/EntityWrapperFactory.java
Having configured an export format with reference to the c_location table, it did not import the registry.
Example: Create business partner location export format add a line with C_Location_ID type Referenced. Run Test Import Processor.
=> Remove Hard Code for C_Location in Replication Data 

.classpath
Just remove bad reference on classpath
=> Minor change for classpath

migration/393lts-394lts/07780_Add_Purchasing_Tab_to_Business_Partner.xml
Just a little change for add reference to **M_Product_PO** in Business
Partner when it is flagged as vendor
Here a gif
=> Add Purchasing Tab to Business Partner

db/ddlutils/oracle/views/RV_C_RFQRESPONSE.sql, db/ddlutils/postgresql/views/RV_C_RFQRESPONSE.sql, migration/393lts-394lts/07710_Add_columns_to_RV_C_RFQResponse_View.xml
Just add the follow columns to view **RV_C_RFQResponse**:
- **C_RfQResponseLine_ID**
- **C_RfQLine_ID**
- **C_RfQLineQty_ID**
=> Add some columns for RV_C_RFQResponse

migration/393lts-394lts/07830_Fixed_error_with_link_reference_for_Web_category.xml
When a product is added to Web **Store Product Category**, the record is
created with other **Store Product Category**.
- Go to **Store Product Category** window
- Go to second tab
- Add a product
Fixes: #3393
=> Fixed error with parent link for W_Category

base/src/org/spin/util/ASPUtil.java
This pull request allows merge the ASP for a role when this is part of
other role as include roles
Data:
- Role: **A**
- Role: **B**
- Just create a window custom or process custom or browser custom using
the role **A**.
- Add the role **A** as included role of **B** role
- Login as role **B**
The login with role **B** should will show the changes from
customization
=> Add support to included role for ASP

base/src/org/compiere/model/I_R_StandardRequest.java, base/src/org/compiere/model/X_R_StandardRequest.java, base/src/org/compiere/util/TimeUtil.java, migration/393lts-394lts/07690_Add_Subject_for_Standard_Request_Type.xml, org.adempiere.request/src/main/java/org/compiere/model/MStandardRequestType.java, org.adempiere.request/src/main/java/org/compiere/model/RequestModelValidator.java
- Add Subject field for predetermine on request
- Add support to **Year** as time unit
- Allows generate a Request with a document event without document type
and document status filter
- Add support to DateDoc column for set current date of request
- Add support to sales representative based on document
Please use **Squash and Merge**
=> Improve Standard Request Type

base/src/org/compiere/model/MOrder.java
Just a minor change removing deprecated method for Order business model
=> Remove deprecated methods for Order

base/src/org/spin/util/TokenGeneratorHandler.java, base/src/org/spin/util/support/AppSupportHandler.java
Just remove unnecessary import for class
=> Minor change imports

client/src/org/eevolution/grid/Browser.java, migration/393lts-394lts/07860_Fixed_error_with_string_value_for_axis_browser.xml
The problem is that for crosstab based on List not exist a cast from
String to value, it is when try compare a string without **'**
- Go to POS Cash Closing Smart Browser
- Run it
Best Regards
=> Fixed error with Crosstab for Smart Browser

org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/model/MHRProcess.java
Fixes https://github.com/adempiere/adempiere/issues/3004
=> MHRProcess periodNo is set to context with name period

base/src/org/compiere/model/I_I_Product.java, base/src/org/compiere/model/X_I_Product.java, base/src/org/compiere/process/ImportProduct.java, migration/393lts-394lts/07930_Add_support_to_Class_Group_and_classification.xml
- Add Name for product group
- Add Name for product class
- Add Name for product classification
-
=> Add support to group, class and classification names

client/src/org/compiere/grid/ed/VLocator.java, zkwebui/WEB-INF/src/org/adempiere/webui/window/WLocatorDialog.java
Hi @yamelsenih - patch for bug #3143
pls review & merge 
regards
=> #3143 fixes bug in (swing) VLocator grid table editor

base/src/org/compiere/model/MColumn.java, base/src/org/compiere/model/MMigration.java
=> Fixed error with SQLException for Migration

migration/393lts-394lts/06380_Improvements_for_Fleet_Management.xml
=> Fixed error with mandatory columns for Freight improvement

migration/393lts-394lts/07960_Add_Tree_definition_for_Web_Store_Category.xml
Step by Step for test and implement:
- Go to Tree window
- Create a new Tree
- Tree Type: Custom Tree
- Table: W_Category
- Parent column name: W_Category_Parent_ID
- Order By: Name
- All Nodes
=> Add tree definition for Web Store Product Category

base/src/org/compiere/model/MMovement.java
https://github.com/adempiere/adempiere/issues/3514
Reverse Accrual and Reverse Correct it should have the same behaviour as the other documents
=> Adempiere  #3514 MMovement reverse Accrual does nothing

migration/393lts-394lts/06570_Add_Web_Store_Integration_from_Spin_Contribution.xml
=> Fixed error with duplicated primary key

.github/workflows/main.yml, .github/workflows/release.yml
Just remove build and keep create-seed for CI
=> Remove Unnecessary step

serverRoot/src/main/server/org/compiere/server/AcctProcessor.java
=> Fix NPE on get server info for Accounting Processor

.github/workflows/main.yml
This pull request allows add artifacts for each action runned:
Here a example: https://github.com/erpcya/adempiere/actions/runs/1034137716
=> Add support to artifact for each building

migration/393lts-394lts/08040_Remove_Autocomplete_feature_for_Migration_Data.xml
Remove autocomplete feature for migration data on **NewValue**, this is
unnecessary for application
=> Remove autocomplete feature for migration data

.classpath
To fix an Eclipse compile error
=> Correct ANT library to version 1.10.10

migration/393lts-394lts/09210_Change_name_for_Text_element.xml
Just change the text translation and name to:
- English: Text Message
- Spanish: Mensaje de Texto
Related to: https://github.com/adempiere/adempiere/pull/3536
=> Change element "Text" translation

base/src/org/compiere/model/MRole.java, base/src/org/spin/util/ASPUtil.java, migration/393lts-394lts/07970_Add_ASP_Access_by_Role.xml
Currently you can define a Window, Process and Smart Browser by role.
This pull request allows define levels by role, then the role can have
many levels allocated instead only from client. See the gif
=> Add support to ASP by role

base/src/org/compiere/model/I_AD_User.java, base/src/org/compiere/model/MUser.java, base/src/org/compiere/model/X_AD_User.java, base/src/org/spin/model/I_AD_AppRegistration.java, base/src/org/spin/model/I_AD_AppSupport.java, base/src/org/spin/model/I_AD_UserSocialMedia.java, base/src/org/spin/model/MADUserSocialMedia.java, base/src/org/spin/model/X_AD_AppRegistration.java, base/src/org/spin/model/X_AD_AppSupport.java, base/src/org/spin/model/X_AD_UserSocialMedia.java, base/src/org/spin/queue/model/X_AD_QueueType.java, base/src/org/spin/queue/notification/DefaultNotifier.java, migration/393lts-394lts/09220_Add_Flag_for_receive_notification_on_Social_Media.xml
This pull request allows add support to flag on Social Media for receive
notifications.
Also add more options for notification type:
- All Possible Means
- EMail+Notice
- EMail
- EMail+Social Media
- Notice+Social Media
- Notice
- Social Media
- None
=> Add support to flag for receive notification

org.adempiere.pos/src/main/java/base/org/adempiere/pos/process/ReverseTheSalesTransaction.java
=> Reverse the Sales Transaction from POS does not include the Reverse Payment in Bank Statement

base/src/org/compiere/model/MOrderLine.java
Currently is impossible change a warehouse for a sales order line if it
is invoiced
The problem is that the warehouse just change the reserved quantity and
delivery, the invoice is not affected for it.
=> Minor change for validation SO

migration/393lts-394lts/09250_Add_Payment_Method_on_Payment.xml
Currently only exist Tender Type for payment, this pull request allows
add a payment method reference to payment
=> Add payment method reference for payment

base/src/org/spin/queue/model/I_AD_QueueType.java, base/src/org/spin/queue/model/X_AD_QueueType.java, base/src/org/spin/queue/process/FlushSystemQueue.java, base/src/org/spin/queue/util/QueueManager.java, migration/393lts-394lts/09250_Add_duration_for_queue_type.xml
Just add a waiting time for queue type, this allows define a waiting
time and duration unit for process queue items.
Now a queue item can be processed when it was expected a waiting time afgter the last process
=> Add Waiting Time for Queue Type

base/src/org/compiere/util/EMail.java
https://github.com/adempiere/adempiere/issues/3629
Fixed #3629
=> Wrong cached context on EMailSender

base/src/org/compiere/util/Language.java
=> #3641 [Feature Request] Add es_CL language for Chilean location 

serverRoot/src/main/server/org/compiere/server/ProjectProcessor.java
Remove old implementation of ProjectProcessor Class
- `org.compiere.server.ProjectProcessor`
=> Refactory: Project Processor By Email based on new notification queue

base/src/org/compiere/model/I_M_MovementLine.java, base/src/org/compiere/model/MOrderLine.java, base/src/org/compiere/model/X_M_MovementLine.java, base/src/org/eevolution/model/I_PP_Cost_Collector.java, base/src/org/eevolution/model/X_PP_Cost_Collector.java, migration/393lts-394lts/09270_Fix_TheSmartBrowserToGenerateShipment.xml, org.eevolution.warehouse/src/main/java/base/org/eevolution/model/MWMInOutBoundLine.java, org.eevolution.warehouse/src/main/java/base/org/eevolution/process/GenerateShipmentOutBound.java
When the shipment is generated from InOutBound Order, the remaining quantity is subtracted two times. This Pull Request resolve it
=> Fixed error with Remaining Quantity InOutBound

org.adempiere.asset/src/main/java/base/org/compiere/process/AssetDelivery.java
Remove old implementation of Payment Servlet Class
- `org.compiere.process.AssetDelivery`
=> Refactory: Asset Delivery By Email based on new notification queue

base/src/org/compiere/model/MPayment.java
=> Error when reversing an assignment already reversed or canceled

base/src/org/compiere/process/ImportOrder.java
…der https://github.com/adempiere/adempiere/issues/3704
=> [Bug Report] Possible leak resource into the process Import Order

base/src/org/compiere/process/ImportOrder.java
… import process https://github.com/adempiere/adempiere/issues/3712
=> #3712 [Bug Report] Incorrect handling of DB transactions in the order

base/src/org/compiere/model/MSession.java
…andling in Adempiere Session https://github.com/adempiere/adempiere/issues/3717
=> #3717 [Bug Report] Leak transaction caused by incorrect transaction in Adempiere Session

base/src/org/adempiere/process/ASPGenerateLevel.java, base/src/org/adempiere/process/CreateCustomizationFromASP.java, base/src/org/compiere/model/MAcctSchema.java, base/src/org/compiere/model/MClient.java, base/src/org/compiere/model/MClientInfo.java, base/src/org/compiere/model/MPeriod.java, base/src/org/compiere/model/MRole.java
…andling in MRole and MClientInfo https://github.com/adempiere/adempiere/issues/3719
=> #3719 [Bug Report] Leak transaction caused by incorrect transaction MRole and MClientInfo 

client/src/org/compiere/apps/EMailDialog.java, migration/393lts-394lts/09230_Add_refactory_for_WEMailDialog.xml, zkwebui/WEB-INF/src/org/adempiere/webui/window/WEMailDialog.java
Remove old implementation of send mail
- `org.adempiere.webui.window.WEMailDialog`
- `org.compiere.apps.EMailDialog`
=> Refactory: EMail Dialog based on new notification queue

base/src/org/compiere/util/WebEnv.java, migration/393lts-394lts/09250_Add_message_for_server_start.xml
Remove old implementation of send mail
- `org.compiere.uti.WebEnv`
=> Refactory: Web Enviroment based on new notification queue

serverApps/src/main/servlet/org/compiere/wstore/PaymentServlet.java
Remove old implementation of Payment Servlet Class
- `org.compiere.model.PaymentServlet`
=> Refactory: Payment Servlet By Email based on new notification queue

serverRoot/src/main/server/org/compiere/server/WorkflowProcessor.java
Remove old implementation of WorkflowProcessor Class
- `org.compiere.server.WorkflowProcessor`
=> Refactory: Workflow Processor By Email based on new notification queue

migration/393lts-394lts/09300_Add_IsIncludeNotAvailable_parameter_for_generate_Invoice.xml, org.eevolution.warehouse/src/main/java/base/org/spin/process/GenerateInvoiceInOutBound.java, org.eevolution.warehouse/src/main/java/base/org/spin/process/GenerateInvoiceInOutBoundAbstract.java
Just add the same behavior that Generate Shipment from OutBound Order for Generate Invoice from Outbound Order.
This change allows generate invoices with quantities over ordereds.
=> Add support to Is Include Not Available flag for generate invoice

base/src/org/compiere/util/CLogger.java, base/src/org/compiere/util/Login.java, base/test/src/org/compiere/util/IT_Login.java
=> Login Remove the Result Set and Adding Integration Test 

base/src/org/compiere/model/MRefList.java
=> Add cache to MRefList #3745 

base/src/org/adempiere/process/MigrationLoader.java
=> Fixed #3760

serverRoot/src/main/server/org/compiere/server/Scheduler.java
Remove old implementation of Scheduler Class
- `org.compiere.server.Scheduler`
=> Scheduler By Email based on new notification queue

migration/393lts-394lts/09380_Fixed_error_with_product_price_for_product.xml
https://user-images.githubusercontent.com/20288327/155904741-18358eb7-0e0d-40d7-bcba-ee1a6492d305.mp4
fixed #3748
=> fix: #3748 Smart Browse Invoice Create From.

base/src/org/adempiere/util/EMailOAuth2Provider.java, base/src/org/compiere/model/X_AD_EMailConfig.java, base/src/org/compiere/util/EMail.java, install/src/org/compiere/install/ConfigurationData.java, migration/393lts-394lts/09370_Add_support_for_Outlook_email_configuration.xml
Add outlook email support 
https://user-images.githubusercontent.com/20288327/149007039-c4bd362b-43dd-4a27-9138-680cc1bfe826.mp4
**Let devices and apps use POP.** in outlook account.
See: https://support.microsoft.com/en-us/office/pop-imap-and-smtp-settings-for-outlook-com-d088b986-291d-42b8-9564-9c414e2aa040
=> feat: Add support for Outllook email configuration

base/src/org/adempiere/controller/PaymentFormController.java, base/test/src/org/compiere/util/IT_PaymentFormController.java
Just a refactory for:
`org.adempiere.controller.PaymentFormController`
=> Change PaymentFormController from ResultSet to new way for get data

base/src/org/compiere/db/DB_MariaDB.java, base/src/org/compiere/db/DB_MySQL.java, base/src/org/compiere/db/DB_Oracle.java, base/src/org/compiere/db/DB_PostgreSQL.java
=> Increase the maximum connection pool parameter in swing mode so that simultaneous processing is possible

base/src/org/compiere/wf/MWFActivity.java
- Remove old implementation of send mail
- Add new queue notification
=> Refactory: Workflow Activity based on new notification queue

base/src/org/compiere/acct/Fact.java
GL Distribution: Copy c_Tax_ID from original factLine to new factLines
https://github.com/adempiere/adempiere/issues/3777
=> adempiere #3777 FR: Copy C_Tax_ID for valid distribution Lines

utils/functions.bat
1. Install Java 11 and set `JAVA_HOME`.
2. Set `ADEMPIERE_HOME`.
1. Start `RUN_setup.bat` with PowerShell.
- Your OS: Microsoft Windows 10 Pro x64.
- Java version: OpenJDK Temurin-11.0.14
- ADempiere version: Develop branch
- DB Provider: Postgres 14
=> fix: RUN_setup.bat on Windows.

org.adempiere.crm/build.gradle
- org.adempiere.crm:
- build.gradle
```Shell
gradle build
```
```Java
```
=> This pull request just add support to gradle builder to crm source folder

tools/build.gradle
folder. The gradle structure is the follow:
- tools:
- build.gradle
Now you can run the follow command to tools source folder:
```Shell
gradle build
```
=> This pull request just add support to gradle builder to tools source

org.adempiere.asset/build.gradle
Just add support to unit test to asset source folder
=> Add Unit Test to Assets

base/src/org/adempiere/model/GenericZoomProvider.java
Fix bugs generated in closers
Fixes #3812
=> Fix bugs generated in closers

org.eevolution.warehouse/build.gradle, org.eevolution.warehouse/src/main/java/base/org/eevolution/process/ReleaseInOutBound.java
- org.eevolution.warehouse:
- build.gradle
```Shell
gradle build
```
```Java
api 'io.github.adempiere:base:3.9.4-develop-1.1'
api 'io.github.adempiere:manufacturing:3.9.4-develop-1.0'
```
https://repo1.maven.org/maven2/io/github/adempiere/warehouse/
=> This pull request just add support to gradle builder to org.eevolution.warehouse source folder

base/src/org/compiere/print/ReportEngine.java
Fixes https://github.com/adempiere/adempiere/issues/3840
=> Catch query NPE when trying to print Component Check

base/src/org/compiere/acct/Doc.java, base/src/org/compiere/acct/DocLine.java
This pull request allows define the account class from other package distinct of `org.compiere.acct`, whit the new functionality ["Add Support to Accounting by Document Base Type"](https://github.com/adempiere/adempiere/pull/3418) all account documents can be defined dynamically instead a fix package
=> Allows extend Doc and Doc Line

org.eevolution.manufacturing/src/main/java/ui/swing/org/eevolution/form/VPrintDocument.java, zkwebui/WEB-INF/src/org/eevolution/form/WPrintDocument.java
Currently adempiere can send document from a process to print. All is ok but if you try send a document and avoid the ask for printing, it always ask if you want print document instead print directly. A example for it can be it:
Note that the follow gif show always the dialog but it the method was called with "askPrint" parameter as false
```Java
getPrintFormatId("Manufacturing_Order_Workflow_Header ** TEMPLATE **", "PP_Order_Workflow_Header_v"), false);
```
=> Just resolve the problem for print a document

base/src/org/compiere/model/MBankAccount.java, base/src/org/compiere/model/MBankAccountDoc.java, client/src/org/compiere/apps/form/PayPrint.java, client/src/org/compiere/apps/form/VPayPrint.java, zkwebui/WEB-INF/src/org/adempiere/webui/apps/form/WPayPrint.java
=> Add support to update sequence on Pay Print/Export option

base/src/org/compiere/print/ReportEngine.java, migration/393lts-394lts/09410_Set_default_report_view_to_manufacturing_reports.xml, org.eevolution.manufacturing/src/main/java/base/org/eevolution/process/CompletePrintOrder.java, org.eevolution.manufacturing/src/main/java/base/org/eevolution/process/PrintBOM.java, org.eevolution.manufacturing/src/main/java/base/org/eevolution/process/PrintBOMAbstract.java, org.eevolution.manufacturing/src/main/java/base/org/eevolution/process/SimulatedPickList.java, org.eevolution.manufacturing/src/main/java/base/org/eevolution/process/SimulatedPickListAbstract.java
- org.eevolution.manufacturing:
- build.gradle
```Shell
gradle build
```
```Java
implementation fileTree(
dir: '../tools/lib/testing',
include: [
'SuperCSV-with_src-1.52.jar'
]
)
// https://mvnrepository.com/artifact/com.github.lbordowitz.openforecast/openforecast
api 'com.github.lbordowitz.openforecast:openforecast:0.5.0'
api 'io.github.adempiere:adempiere.test:3.9.4-develop-1.0'
// https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api
testImplementation 'org.junit.jupiter:junit-jupiter-api:5.7.0'
```
Note that the library **SuperCSV-with_src-1.52.jar** is very very old
and should be …
=> This pull request just add support to gradle builder to manufacturing source folder

base/src/org/compiere/model/MOrder.java, migration/393lts-394lts/09470_3830_Close_Order_Does_Not_Update_Taxes.xml
=> Close Order does not update Total Lines Amount and total amount

.classpath
Just add discord and telegram dependences to eclipse IDE classpath
=> Add dependences to classpath

base/src/org/compiere/db/DB_MariaDB.java, base/src/org/compiere/db/DB_MySQL.java, base/src/org/compiere/db/DB_Oracle.java, base/src/org/compiere/db/DB_PostgreSQL.java, base/src/org/compiere/util/Ini.java
Reverts adempiere/adempiere#3835
[yamelsenih](https://github.com/yamelsenih) I revert these changes, it is causing problems with Wildfly https://github.com/adempiere/adempiere/issues/3862
The problem is that Ini.java takes the values from Adempiere.properties when these settings are in AdempiereEnv.properties so the change is not working. so since the AdempiereEnv.properties variables are set by myEnvironment.sh taking the value directly from the system is correct, each deployment takes the current configuration
=> Revert "Add P_ADEMPIERE_APPS_TYPE support to Ini loader"

migration/393lts-394lts/09500_Notification_Add_Message_Type.xml, migration/393lts-394lts/09510_Notification_Add_Message_Type_for_WF.xml, migration/393lts-394lts/09520_Notification_Add_Response_handler_for_Notification.xml, migration/393lts-394lts/09530_Notification_Add_Account_ID_for_Updates.xml, migration/393lts-394lts/09550_Telegram_Add_Implementation_for_Telegram.xml, migration/393lts-394lts/09560_Telegram_Add_Setup_for_Telegram_Notifier.xml, migration/393lts-394lts/09570_Telegram_Add_Chat_ID_as_Parameter_for_Registration.xml
Just change al version of XML's inserted from [this](https://github.com/adempiere/adempiere/pull/3864) pull request
The pull request was wrote with **1.0** version instead **3.9.4**
=> Change XML's version from 1.0 to 3.9.4

base/src/org/spin/queue/notification/DefaultNotifier.java
=> Fixed [Bug Report] The Scheduler throw AdempiereException: Notification Recipient Mandatory

tools/src/org/adempiere/legacy/apache/ecs/ECSDefaults.java
=> Fixed Class not found java.lang.NoClassDefFoundError when use adempiereMonitor #3896

base/src/org/adempiere/process/YearEndClosing.java, base/src/org/adempiere/process/YearEndClosingAbstract.java, migration/393lts-394lts/09400_YearEndClosing.xml
https://github.com/adempiere/adempiere/issues/3873
A new process _YearEndClosing_ which balances the Expense/Revenue accounts at the end of the year.
I tested this process in combination with the pull request https://github.com/adempiere/adempiere/pull/3817, so you do not have to change the property _document controlled_  in the definition of the accounts.
In this case the period 13 at the end of the year is of type _adjustment period_
=> adempiere #3873  Year End Closing

base/src/org/spin/queue/notification/support/EMailSender.java
new improvement described in **https://github.com/adempiere/adempiere/issues/3899#issuecomment-1148822450**
Fixes #3899
=> Disable NotificationRecipient on error

migration/393lts-394lts/09740_3925_Adding_Reconciled_To_Window_Payment.xml
=> #3925 [Feature Request] Adding Reconciled to Window Payment

base/src/org/compiere/model/MBPartnerLocation.java, zkwebui/WEB-INF/src/org/adempiere/webui/editor/WLocationEditor.java, zkwebui/WEB-INF/src/org/adempiere/webui/window/WLocationDialog.java
=> Adding URL Map to a location map to Business Partner Location 

db/ddlutils/postgresql/functions/altercolumn.sql, db/ddlutils/postgresql/functions/viewsDependencies.sql, migration/393lts-394lts/06415_Resize_MigrationStep_SQL_Statement.xml, migration/393lts-394lts/06420_Fixed_Error_with_Dependences_Alter_Column.xml
…with the t_alter_column function causing nested casting making recreated views slower by applying nested casting https://github.com/adempiere/adempiere/issues/3989
=> #3989 [Bug Report] Error when re-creating a view by altering a table

.github/workflows/main.yml, .github/workflows/release.yml
Just fixed error with asset with a wrog data:
For this relase the asset is not pushed with real size, see a example [here](https://github.com/erpcya/adempiere/releases/tag/3.9.4-rc-1.0.6)
Other action like **build** is ok the asset, see it [here](https://github.com/adempiere/adempiere/actions/runs/3695507065)
=> Fixed error with backup for asset

.github/workflows/main.yml, .github/workflows/release.yml
=> Update ubuntu version for postgresql 15 version support

base/src/org/adempiere/process/ASPGenerateLevel.java, base/src/org/adempiere/process/CreateCustomizationFromASP.java, base/src/org/compiere/acct/Doc_Invoice.java, base/src/org/compiere/model/MAcctSchema.java, base/src/org/compiere/model/MClient.java, base/src/org/compiere/model/MClientInfo.java, base/src/org/compiere/model/MPeriod.java, base/src/org/compiere/report/FinReport.java, base/src/org/spin/process/SetupFileStorageSystem.java, base/src/org/spin/util/AttachmentUtil.java
fixed #4038
Create new company
=> #4038 [Bug Report] Error when creating the Client

.github/actions/adempiere-build/action.yml, .github/workflows/main.yml, build.xml, utils/PostgreSQL/DBRestore.sh, utils/RUN_DBRestore.sh
Solves #4050
And also 
1.- Making sure backward compatibility of database restore (https://github.com/adempiere/adempiere/issues/4050)
2.- Suggestions by Edwin Betancourt concerning which files are eligible for launching a Github restore action
(https://github.com/adempiere/adempiere/pull/3972#issuecomment-1217379515)
=> Database Restore Backward Compatibility and Github Actions

base/src/org/compiere/model/MTable.java
=> Fix path to class for Import Table

base/src/org/compiere/util/TimeUtil.java
Just add the follow methods as public
- `public static int getDaysBetweenWithCalendar (Timestamp start, Timestamp end, boolean onlyMatchWithCalendar, int... includeDay)`
- `public static Timestamp addDays(Timestamp day, int offset, boolean onlyMatchWithCalendar, int... includeDay)`
=> Change modifier to public to TimeUtil methods

base/src/org/compiere/model/MPaySelection.java
This pull request resolve a problem when a payment is in progress or invalid and it is included in a validation of payment selection.
=> Fixed error with validate payment amount

base/src/org/adempiere/util/GenerateModel.java, base/src/org/adempiere/util/ModelClassGenerator.java, base/src/org/adempiere/util/ModelInterfaceGenerator.java
=> [Bug Report] Error the compiled project after the generate model for all tables.

.idea/workspace.xml, base/ADempiere-all.launch, base/ADempiere.launch, client/build.xml, extend/CostingEngine/adempiereLiberoCE.launch, extend/SmartBrowser/adempiereLiberoSB.launch, install/ADempiere-Setup.launch, install/Adempiere/build.xml, launch/Adempiere.xml, org.adempiere.pos/.idea/workspace.xml, org.adempiere.pos/ADempierePOS.launch, org.adempiere.production/build.xml, org.adempiere.test/src/test/scala/org/eevolution/test/AdempiereStartup.scala, org.adempiere.webservice/deploy/build.xml, org.eevolution.cashflow/build.xml, org.eevolution.hr_and_payroll/adempiereLiberoHR.launch, org.eevolution.manufacturing/adempiereLiberoMFG.launch, org.eevolution.warehouse/adempiereLiberoWM.launch, serverRoot/src/web/adempiere.jnlp, tools/launchers/Adempiere Setup GUI.launch, tools/launchers/Adempiere.launch, tools/launchers/GenerateModel-general.launch, tools/launchers/Load XML Migrations.launch, tools/launchers/ModelClassGenerator.launch, tools/launchers/ModelInterfaceGenerator.launch, tools/launchers/adempiere-GenerateModel-prompt.launch, utils/adempiereDirectTemplate.jnlp
Fixes: #4060
References to: https://github.com/adempiere/adempiere/issues/4060
=> Fixed error with laucher for ADempiere Swing UI

base/src/org/compiere/model/CalloutOrder.java
=> Bugfix #3933

base/src/org/compiere/model/PO.java, migration/394lts-395lts/09940_Fixed_Deletion_of_records_form_another_client.xml
https://github.com/adempiere/adempiere/assets/20288327/fef0147e-1f13-4567-a041-66ad06946ff9
fixes https://github.com/adempiere/adempiere/issues/4000
=> fix: #4000 Deletion of records from another `Client`.

base/src/org/compiere/model/GridField.java, base/src/org/compiere/model/GridTable.java, base/src/org/compiere/util/DisplayType.java
Before this changes
https://user-images.githubusercontent.com/20288327/126553635-cbb76c42-0732-470a-a656-7f954f8221ab.mp4
After this changes
https://github.com/adempiere/adempiere/assets/20288327/b3f9ecba-bbe6-4850-aaef-699480d2b05d
fixes https://github.com/adempiere/adempiere/issues/3576
=> fix: Currency Rate change `C_Currency_ID_To` value.

base/src/org/compiere/model/MDunningRunLine.java
=> Bugfix #4114

client/src/org/spin/apps/form/BankStatementMatchController.java
=> Default charge on bank statement

base/src/org/compiere/acct/Fact.java, base/src/org/compiere/model/MDistribution.java
Reverts adempiere/adempiere#3963
=> Revert "#3920 GL Distribution doesn't work for any account  https://github.co…"

base/src/org/compiere/model/PO.java
When you have many element values like User1, User2 and account schema for a same client, the tree node used for insert it is wrong because is not search with a correct criteria.
This pull request resolve it
=> Fixed error with element value insert for tree

base/src/org/compiere/dbPort/Convert_PostgreSQL.java
It can be reproduced by forcing the code, specifically by adding a `LIMIT 2 OFFSET 0` after the line https://github.com/adempiere/adempiere/blob/develop/base/src/org/compiere/util/Login.java#L401
[org.compiere.util.Login.java.zip](https://github.com/adempiere/adempiere/files/12446946/Login.java.zip)
Wihtout `LIMIT` clause
With `LIMIT` clause
Login with `LIMIT` to records length
```log
-----------> DB_PostgreSQL.getDataSource: Starting Client Hikari Connection Pool [1]
===========> Login.lambda$5: SELECT u.AD_User_ID, r.AD_Role_ID,r.Name, u.ConnectionProfile FROM AD_User u INNER JOIN AD_User_Roles ur ON (u.AD_User_ID=ur.AD_User_ID AND ur.IsActive = 'Y' ) INNER JOIN AD_Role r ON (ur.AD_Role_ID=r.AD_Role_ID AND r.IsActive = 'Y' ) WHERE u.AD_User_ID = ? AND u.IsActive = ?  AND EXISTS (SELECT …
```
=> fix: Postgres `LIMIT` clause and omit `"limit"` column name.

base/src/org/compiere/model/MProduction.java
- Remove validation by zero when a production is reversed
- Create a production batch
- Se target quantity to 10
- Set "Automatic Production" flag to false
- Complete batch
- Go to Production window
- Create a new record and select the previous batch created
- Complete production
- Go to production batch
Note that the target quantity is kept instead of being set to "0"
This is because when the production is completed, a cache for class MProductionBatch and the target is updated to the previous quantity instead
- Fixed error with production target quantity
- Create a production batch
- Se target quantity to 10
- Set "Automatic Production" flag to true
- Complete batch
- Go to Production window
- Complete production generated from batch
- Now reverse production
Note that an exception is …
=> Fix Error On Production Light

migration/394lts-3.9.4.001/09990_Fix_Lenght_for_Employee_Validation_Code.xml, migration/394lts-3.9.4.001/10000_4086_Add_Garden_World_Test_Data.xml, migration/394lts-3.9.4.001/10010_4086_Add_Attendance_Import_Format.xml, migration/394lts-3.9.4.001/10020_TNA_Add_Standard_Button_to_Import.xml
This pull request add the file `09990_Fix_Lenght_for_Employee_Validation_Code.xml` to `394lts-3.9.4.001` folder and fix construction error
Related to: https://github.com/adempiere/adempiere/pull/4229
=> Just change sequence to XML and remove 394lts-395lts folder

base/src/org/compiere/model/MChartDatasource.java
related changes https://github.com/adempiere/adempiere/pull/4184
fixes https://github.com/adempiere/adempiere/issues/4183
=> fix: #4183 Chartdatasource and table without keys.

org.adempiere.asset/src/main/java/base/org/compiere/asset/model/validator/FixedAsset.java
=> Validate product for receipt inside

base/src/org/compiere/model/PaymentProcessor.java
=> Extend scope of payment processor variable for implementation

base/src/org/spin/process/SetupFileStorageSystem.java
=> Fixed error with bad transaction for Setup File Storage

zkwebui/WEB-INF/src/org/adempiere/webui/panel/AbstractADWindowPanel.java
=> Fixed error with duplicated session

zkwebui/WEB-INF/src/org/adempiere/webui/panel/AbstractADWindowPanel.java
=> Fixed error with Printing report from Payroll Process

base/src/org/compiere/model/MOrderLine.java
=> Fixed error with price calculation for RMA

base/src/org/compiere/wf/MWFProcess.java
=> Bug Fix Missing trx in workflow query outdated PO data
