- client/src/org/compiere/apps/ASearch.java
- client/src/org/compiere/apps/search/Find.java
Also remove the mandatory save warning.  Fixed ASearch handling of YesNo fields in the UserQuery code.  This change is incomplete and the pull request is for review.  Similar functionality needs to be ported to ZK and messages added via xml so a follow-on commit will be required.
> Change behavior of the combobox to display a hint to the user.  

- base/src/org/compiere/model/MCostDetail.java
This is a quick fix to ADEMPIERE-420.  Not sure if it should be invoice line ASI or if the ASI should be removed from the query parameters.
> ADEMPIERE-420 Add attribute set instance to the query parameters.

- client/src/org/compiere/grid/ed/VLookup.java
- zkwebui/WEB-INF/src/org/adempiere/webui/editor/WSearchEditor.java
The array of values returned by the info windows needs to be passed to the event listener.  Only the first value was being returned in WSearchEditor.  Some code cleanup in both files to test for changes to the field where the possible array was tested rather than the single value.
> Fix the multi-selection in WSearchEditor to match VLookup.  

- client/src/org/compiere/apps/ProcessParameterPanel.java
In smart browsers, this change will set the size of the process parameter panel so that it will resize as the window is resized and a horizontal scrollbar will appear if the width is less than 400px.  The vertical size is set by the number of rows of parameters.  TODO - account for rows with hidden parameters.
> Correct the behaviour of the Process Parameter Panel in horizontal mode.

- base/src/org/compiere/model/MColumn.java
Also avoid validation of lookups if direct load or if the system element is changing.
> Remove unnecessary tests of environment.  

- base/src/org/compiere/process/SvrProcess.java
Adds a simple null test in case the process returns a null string,
> #285 Prevent potential NPE in SvrProcess

- client/src/org/compiere/grid/GridController.java
When processing a change in the Swing interface, the vetoableChange checks for vetos and then sets the value of the field.  If the new value is null, it is not set.
This fix simply adds a line to set the value to null when the new value is null.
>  #283 GridController in swing will not set value to null 

- client/src/org/compiere/grid/VTable.java
A simple fix that will allow immediate editing for most fields in the SWING client.  It makes the table view act like a spreadsheet.
> #271 Allow immediate editing of GridTable cells in multi-row view.

- client/src/org/compiere/apps/search/Find.java
If a VLookup field used as a selection column ahead of a range, the multiple columns can get out-of-sync.
This fix ensures the second set of editors remains in sync.
>  #221 Find fails with index out of range

- client/src/org/compiere/grid/GridController.java
- client/src/org/compiere/grid/ed/VMemo.java
#283, #341, #342 - These changes should fix the behavior of the text and memo fields when dealing with text and null values.  Tested with mandatory, read-only and normal fields of type text, string, memo, date, amount, filename.  The behavior for mandatory fields is:
1. Red (error) when initially null
2. Blue when there is a value
3. Red when the field value is deleted
The value is bound when the field looses focus.
> Hotfix/3.8.0#002 #283 grid controller set null

- base/src/org/adempiere/process/MigrationLoader.java
- base/src/org/compiere/model/MProcess.java
Update MigrationLoader to use class names and correct getProcessByClass.  Set mandatory parameter for Role Access Update.
> Hotfix/3.8.0#002 #325 #363 process param

- zkwebui/WEB-INF/src/org/adempiere/webui/component/StringBox.java
- zkwebui/WEB-INF/src/org/adempiere/webui/editor/WStringEditor.java
The WStringEditor class needs to set the attributes for the ZK component to support sahi testing.  The StringBox class defines a testbox and then resets it as a new textbox later in the code.  This initial call is unnecessary.
> Add changes to StringBox and WStringEditor to enable SAHI testing.

- base/src/org/eevolution/model/MPPOrderBOMLine.java
This pull request fixes issue #426 and allows modified Manufacturing Order documents to correctly reserve/unreserve stock for their components.
> #426 Bugfix MPPOrderBOMLine release stock reservation

- base/src/org/compiere/apps/ProcessParameter.java
- client/src/org/compiere/apps/ProcessParameterPanel.java
- client/src/org/compiere/grid/ed/VLookup.java
- client/src/org/eevolution/form/VBrowserSearch.java
- client/src/org/eevolution/grid/BrowserSearch.java
If using fields and gridFields together, the change event process is
field editor -> vetoable change ->gridField.setValue() -> field.setValue() -> property change
Changed the vetoableChange listeners to set the gridField value and added a
propertyChange listener to respond to the field changes to provide dynamic display.
In VLookup, if a veto is received, abort the change.
> #495 Correct handling of field/gridField updates in ProcessParameterPanel and VBrowserSearch

- base/src/org/compiere/process/FactReconcile.java
- migration/380lts-390lts/90460-AddAcctDateToAutoFactRecon.xml
- migration/380lts-release/01740-AddAcctDateToAutoFactRecon.xml
A simple addition of a date range to the automatic acct fact reconciliation process to allow the user to limit the date range performed.  This helps limit the reconciliations to the periods under investigation and prevents matching with future accounting facts.  For example, the sum of unreconciled facts in Accounts Payable should match the AP aging report at the end of the last period.  However, if the auto matching process is run, it will reconcile facts in the current period as well, changing the unreconciled fact list in the last period.  This can be fixed by resetting the match manually.  The date range on the auto process just saves some time.
> Hotfix/3.8.0#002 #773 add date range to auto fact reconciliation

- client/build.xml
- client/src/JNLP-INF/APPLICATION_TEMPLATE.JNLP
- serverRoot/src/web/adempiere.jnlp
Secures the JNLP file by including a matching APPLICATION_TEMPLATE.JNLP in Adempiere.jar.  See https://docs.oracle.com/javase/8/docs/technotes/guides/deploy/signed_jnlp.html.  Alone, this won't remove the security warning but it does prevent security errors visible in the console.
> #1481 JNLP file is not secure. Security warning appears.

- base/src/org/compiere/apps/ProcessController.java
- client/src/org/compiere/apps/APanel.java
- client/src/org/compiere/apps/ProcessModalDialog.java
- client/src/org/compiere/apps/ProcessPanel.java
- zkwebui/WEB-INF/src/org/adempiere/webui/apps/ProcessDialog.java
- zkwebui/WEB-INF/src/org/adempiere/webui/apps/ProcessModalDialog.java
- zkwebui/WEB-INF/src/org/adempiere/webui/apps/ProcessPanel.java
- zkwebui/WEB-INF/src/org/adempiere/webui/desktop/TabbedDesktop.java
clled from window, reference to issue:
https://github.com/adempiere/adempiere/issues/1730
Please review it pull request, currently exist a bug when a process is executed from a window and it is configured as silent process
Best Regard
> #1730, Fixed running as silent process with modal dialog for process

- migration/390lts-391/03790_1625_Zooming_of_Operational_Period_not_possible_in_Forecast_window.xml
Solving the small bug "Zooming of Operational Period not possible in Forecast window" 
https://github.com/adempiere/adempiere/issues/1625
> adempiere:#1625 Zooming of Operational Period not possible in Forecast

- base/src/org/adempiere/util/ProcessUtil.java
this conforms to ad-processes written in java. Error messages have to start with "@Error@".
> patch in ProcessUtil.startScriptProcess when error msg startsWith "@Error@"

- base/src/org/compiere/model/MRecentItem.java
- client/src/org/compiere/grid/tree/VTreePanel.java
- zkwebui/WEB-INF/src/org/adempiere/webui/dashboard/DPRecentItems.java
#1741: Deleted recent items causes NPE (only in Swing), reference to https://github.com/adempiere/adempiere/issues/1741
Improvement from
#1426: Null Pointer Exception at Adempiere start, reference to https://github.com/adempiere/adempiere/issues/1426
> #1741: Deleted recent items causes NPE (only in Swing), reference to

- base/src/org/eevolution/model/I_HR_Payroll.java
- base/src/org/eevolution/model/I_HR_Process.java
- base/src/org/eevolution/model/X_HR_Payroll.java
- base/src/org/eevolution/model/X_HR_Process.java
- migration/390lts-391/03630_1552_HHRR_FlagPostIndividually.xml
- org.eevolution.hr_and_payroll/src/main/java/base/org/compiere/acct/Doc_HRProcess.java
issue: https://github.com/adempiere/adempiere/issues/1552
Hi guys, it is a old discussion about definition of flag **IsPostingPerEmployee**, here a little change for improve definition. Let me explain:
The old change allows posting for employee on payroll process however, it was defined on **HR_Process** table instead **HR_Payroll** table, it change just:
- Change Column from **HR_Process** table to **HR_Payroll**
- Add a display logic for field: **@#ShowAcct@=Y**
- Improve element name definition
See before and after:
- Before: ![screenshot_20180728_134524](https://user-images.githubusercontent.com/2333092/43359309-025dc0ca-9266-11e8-942b-979a70bc5654.png)
- After:
> #1552, Change Dictionary definition for posting employee, reference to

- migration/390lts-391/03930_1088_Add_Column_IsQuickEntry.xml
Fixes #1088
- The migration script never use the schema into the SQL sentence , so that script should work in any schema.
(cherry picked from commit 385c4bbd3715e012b5954a205074739e0cfa0569)
> #1088 XML Script and Fix Sequence number

- base/src/org/adempiere/controller/SmallViewController.java
- client/src/org/eevolution/grid/Browser.java
Hi verybody, i find a error with Smart Browser for ZK UI that affect:
- Default values
- Search field changes
- Search result for SB
A little example of it behavior is emulated with follow steps:
- Go to POS
- Create a new POS order
- Collect it order
- Into the POS, go to process **POS Statement Close**:
- Note that exist a **Transaction Date** field with current date
- If you try change date, it not have effect over search.
The problem is that ZK UI don't know the listener for changes over search field on SmallViewController class and any change over field not have effects over values for query
fixes #2030 
reference to issue: https://github.com/adempiere/adempiere/issues/2030
> #2030 Listener missing from ZK ui for Small View Controller

- base/src/org/compiere/process/LandedCostDistribute.java
LandedCostDistribute should not create cost detail entries
https://github.com/adempiere/adempiere/issues/1912
**Status for working with landed Costs and landedCostAllocation:**
**Window Purchase Invoice, Line InvoiceLine**
Step 1: Generate a Landed Cost entry with the button _Generate Landed Cost_
Result: depending on the parameter create by product one or several LandedCost entries are generated
Now you can distribute the costs and generated the corresponding landed cost allocation entries with the button _distribute Costs_. This is preliminary because when the invoice is completed all landed cost allocations will be deleted and generated again.
The process generates also the Costdetail entries for the calculation of the new costs of the corresponding products.
Step 2: Complete the …
> #1912 Bug fixes for landedCost and LandedCostAllocation

- base/src/org/adempiere/process/MigrationLoader.java
- base/src/org/compiere/process/MigrationFromXMLAbstract.java
Fixes #2053.  Adds the FileName parameter to the MigrationLoader to address the required parameters before and after the parameter name is changed in another commit.  Fixes the problem where RUN_MigrationXML fails with an unfilled required parameter.
> Fix for #2053. Add FileName parameter to MigrationLoader.

- base/src/org/compiere/model/GridTable.java
Fixes #1944
When a record is being edited with a value in that field there is a problem.  When the comparison of the old value in the model where null = 'N' and the database where null = null don't match, the PO save fails.  Have to account for the fact that null='N' in the database as well and allow the mismatch.
> #1944 Deal with special case where a Y/N field has been added to a populated table.

- base/src/org/adempiere/engine/AbstractCostingMethod.java
https://github.com/adempiere/adempiere/issues/1916
**Problem:**
When you cancel a shipment with method reverse accrual the new reverse document is generated with the current date.
The new cost detail entry is also generated with the current date, but with a sequence number following the original document.
As the following cost detail have dateAcct< current date, they are not updated in quantity and value.
This problems exists for all documents which are cancelled with reverseaccrual and generate entries in cost detail.
**Solution:**
Include the new cost detail at the end of the current date.
> #1916 ReverseAccrual generates wrong seqNo in costdetail

- zkwebui/WEB-INF/src/org/adempiere/webui/editor/WSearchEditor.java
Fixes #2059
In WbUI process parameters with the reference Search create a NPE.
Solution: Class WSearchEditor, line 705
replace `
if(tabPanel.getQuickPanel() != null) {`
with `
if(tabPanel != null && tabPanel.getQuickPanel() != null) {`
Result:
> #2059 Process Parameters: NPE for reference type Search

- client/src/org/compiere/grid/GridController.java
Fixes #421.
In a window tab that has an embedded tab, like the Bill of Materials & Formula window, its possible to have the embedded tab and header record out of sync when there are several header records.  This happens when the header is put in grid view and then sorted differently by clicking on a column. On switching back to the form view, the embedded tab will show records associated with the original header, not the currently displayed header.
The fix is simply to refresh the tab data when the switch from grid to form view is made.
> #421 Ensures embedded tabs are updated

- base/src/org/compiere/print/DataEngine.java
- base/src/org/compiere/print/PrintDataColumn.java
- base/src/org/compiere/print/PrintDataGroup.java
Fixes #431.
Groupings were originally done in the order of display not the order of sorting/grouping.  This change adds a recursive method that checks the groupings in the correct order and adds the summary functions, if any.  Groups can be displayed in any column and the summaries will respect the sort order/groupings.
To see the effects, try these steps before and after the code changes:
1. In GardenWorld, add an invoice to the tree farm for a plum tree and set the project on the invoice header to standard.  Complete the invoice.  (You only need do this once to create the project dimension).
2. Open the aging report and select the current date, account date, not sales transactions and show invoices.
3. Modify the print format to show the currency, business partner group, business …
> #431 Fixes the way totals are grouped in the report dataengine.

- org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/model/MHREmployee.java
Fixes: #2130
Hi everyone, here a pull request for validate active employee for payroll, a example:
I have two employees:
- Garden Admin
- Joe Block
Joe Block also is a customer, currently if Joe Block is not from payroll then I must change flag **IsActive** to **N**, it is not good if we need use Joe Block as a customer.
This change just make a validation from **Employee Status** (if it is setted) and sort by **Start Date** field instead **HR_Employee_ID**
> #2130 Enhanced validation for active employee

- base/src/org/compiere/util/PaymentExportList.java
- zkwebui/WEB-INF/src/org/adempiere/webui/apps/form/WPayPrint.java
Fixes #2120 
Hi all, this pull request will be allows create a file for export payment with custom name, see a example:
> #2120 Add custom name for export file from payment print form

- base/src/org/compiere/model/MAttachment.java
- base/src/org/compiere/util/MimeType.java
- client/src/org/compiere/apps/Attachment.java
- migration/390lts-391/04405_2167_Allows_FileTypes.xml
Hi all, this issue allows define if a file can be attached to record or not.
Now you can configure the allowed files and restricted files with a little change on **System Configurator** window:
The follow is variable used for allowed files and restricted
<pre>
ATTACHMENT_FILE_TYPES_ALLOWED
ATTACHMENT_FILE_TYPES_RESTRICTED
</pre>
The format for add new files for allows and restrict is simple, just use comma separed value:
<pre>
.pdf, .png, .jpg, .jpeg, .xls, .xlsx, .doc, .docx, .txt, .log, .properties
</pre>
Here a pic of result for restricted files:
Fixes: #2167
> #2167, Add enhancement for allows file types, reference to issue:

- base/src/com/akunagroup/uk/postcode/AddressLookup.java
- base/src/org/adempiere/pipo/PackIn.java
- base/src/org/adempiere/pipo/PackInHandler.java
- base/src/org/adempiere/process/rpl/XMLHelper.java
- base/src/org/compiere/model/MArchive.java
- base/src/org/compiere/model/MAttachment.java
- base/src/org/compiere/process/MigrationFromXML.java
- base/src/org/compiere/util/ImpExpUtil.java
- base/src/org/spin/util/XMLUtils.java
- org.adempiere.webservice/WEB-INF/src/com/_3e/ADInterface/ADServiceImpl.java
- webCM/src/main/servlet/org/compiere/cm/xml/XSLTProcessor.java
Hi everybody, this issue allows create a standard for default features on XMLParser and Builders, is nice to have this enhancement inside ADempiere core.
I hope that it can be useful.
Best regard.
Fixes: #2169
> #2169, Improve default feature for XML parser and builder, reference to

- migration/390lts-391/04420_2069_Drop_Bad_Constraint.xml
Hi Everybody, this issue remove a bad constraint in **M_Movement** table, the problem is that the column **M_Movement.C_BPartner_Location_ID** have a constraint that make reference to **C_Location.C_Location_ID** instead **C_BPartner_Location.C_BPartner_Location_ID**
Fixes: #2069 
reference to issue: https://github.com/adempiere/adempiere/issues/2069
> #2069, Remove bad constraint for C_BPartner_Location on M_Movement,

- .classpath
Hi, this pull request remove missing references for oracle library on Eclipse IDE
Fixes: #2186 
https://github.com/adempiere/adempiere/issues/2186
> #2186, fix classpath for project on Eclipse IDE, reference to issue:

- client/src/org/compiere/grid/GridController.java
Fixes #421.  
The refresh of data on the switch from grid to form view causes an error when the table model has not been opened.  A test to check that the table is open is required.
> #421 Prevent unnecessary error on switch from grid to form view

- base/src/org/compiere/model/MInvoiceLine.java
https://github.com/adempiere/adempiere/issues/2031
**error:**
For the case _various Landedcosts for one Invoiceline_ the fields _c_Landedcosttype_ID_ and _m_Inoutline_ID_ are not updated.
> adempiere #2031 Field LandedCostType in LandedCost

- zkwebui/WEB-INF/src/org/adempiere/webui/panel/UserPanel.java
Fixes #2320.
Makes it look like this.
> Add Vertical Separator to the User Panel between Context and Preference

- zkwebui/WEB-INF/src/org/adempiere/webui/panel/LoginPanel.java
Fixes #2318.  Changes the "Forgot Password?" label to a button that appears as a link.  Its more intuitive.
> Change the "Forgot Password?" lable to a link.

- base/src/org/adempiere/util/ProcessAbstractClassGenerator.java
Hi everyone this pull request resolve a error when a abstract class is generated from ADempiere.
When a parameter is created as **Table** and it make reference to table with a key column as String, the parameter is called from process like ID instead String, see:
<pre>
===========> ExportSurrogateKeyToMigration.process: java.lang.NumberFormatException [32]
java.lang.NumberFormatException
at java.math.BigDecimal.<init>(BigDecimal.java:494)
at java.math.BigDecimal.<init>(BigDecimal.java:383)
at java.math.BigDecimal.<init>(BigDecimal.java:806)
at org.compiere.process.ProcessInfoParameter.getParameterAsInt(ProcessInfoParameter.java:123)
at org.compiere.process.ProcessInfo.getParameterAsInt(ProcessInfo.java:1106)
at org.compiere.process.SvrProcess.getParameterAsInt(SvrProcess.java:609)
at …
> Fixed error with Table lookup when it is referenced with key column as

- base/src/org/adempiere/controller/RecordInfoController.java
Fixes #2387.
Some column names and labels, like "Name" include ampersands in the original English message.  Need to clean the ampersands from the text.
> #2387 Remove ampersands in Record Info dialogs

- zkwebui/WEB-INF/src/org/adempiere/webui/editor/WDateEditor.java
- zkwebui/WEB-INF/src/org/adempiere/webui/editor/WDatetimeEditor.java
- zkwebui/WEB-INF/src/org/adempiere/webui/editor/WTimeEditor.java
Fixes #2383.
Overrides the getPopupMenu() method which returns null by default.
> #2383 Override the getPopupMenu method() in webui date / time editor.

- migration/391lts-392lts/04440_2340_ImproveDocumentStatusIndicators.xml
- zkwebui/WEB-INF/src/org/adempiere/webui/apps/graph/WDocumentStatusIndicator.java
Fixes #2340.
Fixes #1243 
Changes the component used in the dashboard Document Task panel to a ToolBarButton which appears as a link.  This is better than a label with underlined text as the cursor turns to a "finger" rather than a text I-bar when hovering over the field.  
The change also sets all fields in the Document Status Indicator window to "Is Displayed in Grid"="Y".
> Turns the Doc Status Indicator text into a link and shows all fields in grid.

- zkwebui/WEB-INF/src/org/adempiere/webui/component/CWindowToolbar.java
- zkwebui/WEB-INF/src/org/adempiere/webui/panel/ADWindowPanel.java
Fixes #2373.
Adds Shift+F2 as a shortcut key for copy record in the webui.  This is the same key used in the Java Client.
See https://adempiere.gitbook.io/docs/v/develop/introduction/getting-started/opening-and-using-windows/shortcut-keys
> #2373 Add shortcut key Shift+F2 to copy record in webui.

- base/src/org/spin/process/GenerateDocsFromMenu.java
- base/src/org/spin/process/GenerateDocsFromMenuAbstract.java
- base/src/org/spin/util/docs/AbstractDocumentationSource.java
- base/src/org/spin/util/docs/AbstractTextConverter.java
- base/src/org/spin/util/docs/FunctionalDocsForForm.java
- base/src/org/spin/util/docs/FunctionalDocsForMenu.java
- base/src/org/spin/util/docs/FunctionalDocsForProcess.java
- base/src/org/spin/util/docs/FunctionalDocsForSmartBrowse.java
- base/src/org/spin/util/docs/FunctionalDocsForWindow.java
- base/src/org/spin/util/docs/IIndex.java
- base/src/org/spin/util/docs/MarkdownConverter.java
- base/src/org/spin/util/docs/ReStructuredTextConverter.java
- base/src/org/spin/util/docs/TableTextConverter.java
- migration/391lts-392lts/04420_1934_Process_Generate_Docs.xml
Hi guys, this pull request allows generate documentation from ADempiere Application Dictionary, the documentation can be generated for:
- [Markdown](https://en.wikipedia.org/wiki/Markdown)
- [reStructuredText](http://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html)
The result for it documentation can be some like here: [https://adempiere.github.io/](https://adempiere.github.io/) 
See this video for know what is step by step
Fixex: #1934
> Add Documentation Generator from ADempiere

- base/src/org/compiere/model/MBankStatement.java
- base/src/org/compiere/model/MBankStatementLine.java
- base/src/org/compiere/process/StatementCreateFrom.java
This pull request add conversion from payment to bank statement, currently exists the follow method:
<pre>
MBankStatement.addPayment(paymentCash);
</pre>
**Bank Account Detail**:
- Currency: USD
**Current Behavior:**
- Payment:
- Payment Amount: 100
- Payment Currency: EUR
- Bank statement:
- Trx Amount: 100
- Currency: USD (This is bad)
**After change:**
- Payment:
- Payment Amount: 100
- Payment Currency: EUR
- Bank statement:
- Trx Amount: 124.90
- Currency: USD
The previous method add automatically a payment to current bank statement, the problem is that if payment is created with other currency, it is not converted for bank statement.
Best regard
> Add conversion for bank statement helper method

- base/src/org/compiere/model/MSession.java
- base/src/org/compiere/model/PO.java
Hi everybody, this pull request resolve a error with UUID for migration:
Currently and after 3.9.1 ADempiere version is added **UUID** column for all tables. For now this worked but when I try generate a migration from PO the **UUID** is not added to migration step.
Please review it.
> Fixed error with UUID for Migration from model

- zkwebui/WEB-INF/src/org/adempiere/webui/apps/ProcessPanel.java
Fixes #2445 
A simple change to the north panel to allow the user to select the size.
> #2445 Make the ZK process panel message draggable in size.

- base/src/org/compiere/process/ProcessInfoUtil.java
Fixes #2453 
See #2453 https://github.com/adempiere/adempiere/issues/2453
Prevents the duplication of the process log when displayed in the post-process dialogs.
> #2453 Prevent duplication of process logs in dialogs

- base/src/org/compiere/model/Tax.java
Fixes #2434
When determining if a tax is a child tax or summary tax, Tax.java uses the test  ```tax.getParent_Tax_ID()!=0```  instead of testing ```!tax.isSummary()```.  In the gui, the parent tax field is hidden if the Is Summary checkbox is selected so there is no way for the user to know that Parent_Tax_ID is non-zero.  
See https://github.com/adempiere/adempiere/issues/2434
To test, create a parent and child tax rate pair.  On the parent tax, deselect the Is Summary checkbox and set the parent tax rate to some other tax rate.  Then reselect the Is Summary check box.  Note the parent tax field is hidden.
Set up an order that would use that tax.  An error occurs as no tax is found.
> #2434 Tax.java

- base/src/org/compiere/process/ImportBankStatement.java
The process of importing the statement of accounts is suspended, because the statement 'save' is not performed using the transaction.
Openup Solutions
Nicolás Sarlabós
> Import process hangs

- base/src/org/compiere/model/Tax.java
Reverts adempiere/adempiere#2452
Please review it.
If a product have a Tax Category with tax:
Tax 1:
SO: Yes
IsSummary = False
The result is that is not finded from a sales order.
<pre>
ProjectPhaseGenOrder.process: No se pudo encontrar el impuesto - Categoría del Impuesto:IVA Básico, Transacción de Ventas:Si, Entrega (04/04/2019, , ,  location  -> location 1, State,  State ), Factura (04/04/2019, Address 1: Address , Address,  Address  -> Address2  ) [136]
org.adempiere.exceptions.TaxNotFoundException: No se pudo encontrar el impuesto - Categoría del Impuesto:IVA Básico, Transacción de Ventas:Si, Entrega (04/04/2019, , ,  Location  -> Address ), Factura (04/04/2019, Address 1  -> Address 2 )
at org.compiere.model.Tax.get(Tax.java:610)
at org.compiere.model.Tax.getProduct(Tax.java:346)
at …
> Revert "#2434 Tax.java"

- base/src/org/adempiere/controller/SmallViewController.java
- zkwebui/WEB-INF/src/org/eevolution/form/WBrowser.java
Just now exist a big problem when a process parameter have a default value that are updated from browse search parameters, a example of it is the Smart Browse for **POS Close Statement** see gif:
This pull request fixed default value for:
- Value From
- Value To
- Numeric
Smart Browse with process
Se result:
> Default values from SQL of process parameter not worked

- zkwebui/WEB-INF/src/org/adempiere/webui/util/BrowserToken.java
Hi all,
this is a small change in `BrowserToken` class : `sun.misc.BASE64Encoder` is replaced by `java.util.Base64.Encoder`, see issue #1328
regard EUGen
> #1328 use java.util.Base64.Encoder in BrowserToken

- migration/391lts-392lts/04550_2306_CorrectMissingOperatorPostgres.xml
Fixes #2251.
Fixes #2306.
This migration has a single step with a postgres specific SQL as provided by Victor (@e-Evolution).  It won't affect other database types.
> #2306 Add the missing operator to Postgres.  

- migration/391lts-392lts/04530_Mail_Template_for_Event.xml
- org.adempiere.request/src/main/java/org/compiere/model/MMailText.java
- org.adempiere.request/src/main/java/org/compiere/model/MRequest.java
- org.adempiere.request/src/main/java/org/spin/model/I_R_NoticeTemplate.java
- org.adempiere.request/src/main/java/org/spin/model/I_R_NoticeTemplateEvent.java
- org.adempiere.request/src/main/java/org/spin/model/MRNoticeTemplate.java
- org.adempiere.request/src/main/java/org/spin/model/MRNoticeTemplateEvent.java
- org.adempiere.request/src/main/java/org/spin/model/X_R_NoticeTemplate.java
- org.adempiere.request/src/main/java/org/spin/model/X_R_NoticeTemplateEvent.java
- serverRoot/src/main/server/org/compiere/server/RequestProcessor.java
This pull request add a mail template for each event type, note that you can have distints templates by events like transfer a request, new request or request state change.
A simple video of setup is:
The list of default mail template is:
Event Type | Name | Active | Subject | Mail Text
-- | -- | -- | -- | --
Automatic Task: Default Template | Automatic Task: Default Template | Yes | @DocumentNo@ - @Subject@  Default Template | Default template for notification
Automatic Task: Expired Task Alert | Automatic Task: Expired Task Alert | Yes | @DocumentNo@ - @Subject@  Expired Task Alert | Notice sent to the agents of old or expired tasks.
Automatic Task: Inactivity Alert | Automatic Task: Inactivity Alert | Yes | @DocumentNo@ - @Subject@  Inactivity Alert | Send inactivity alerts
Automatic …
> Add support to request mail template for event type

- base/src/org/adempiere/controller/form/BOMDropController.java
- base/src/org/adempiere/controller/form/BOMDropForm.java
- base/src/org/compiere/swing/CRadioButton.java
- client/src/org/compiere/apps/form/VBOMDrop.java
- client/src/org/compiere/grid/ed/VRadioButton.java
- migration/391lts-392lts/04530_2435_BOMDrop.xml
- zkwebui/WEB-INF/src/org/adempiere/webui/apps/form/WBOMDrop.java
- zkwebui/WEB-INF/src/org/adempiere/webui/component/Radio.java
- zkwebui/WEB-INF/src/org/adempiere/webui/editor/WRadioEditor.java
Fixes #2435 
This pull request fixes and improves the BOM Drop functionality.  The swing and ZK BOM Drop forms are equivalent and can be accessed from the menu or from an Order, Invoice or Project as a button/process.  A new radio button editor was added to support the optional/variant features.  A Plant Starter Kit product was added to Garden World, along with some subproducts to provide a test of the optional and variant features.
Note that a Role Access Update is required to access the BOM Drop process from the Order, Invoice or Project window/tab.
Draft documentation:  https://mckayerp.gitbook.io/adempiere/v/contrib_2435/introduction/products-and-material-management/bom-drop
See https://github.com/adempiere/adempiere/issues/2435
> BOM Drop form improvments.  

- base/src/org/compiere/model/I_C_Project.java
- base/src/org/compiere/model/I_C_ProjectPhase.java
- base/src/org/compiere/model/I_C_ProjectProcessorChange.java
- base/src/org/compiere/model/I_C_ProjectProcessorQueued.java
- base/src/org/compiere/model/I_C_ProjectTask.java
- base/src/org/compiere/model/X_C_Project.java
- base/src/org/compiere/model/X_C_ProjectPhase.java
- base/src/org/compiere/model/X_C_ProjectProcessorChange.java
- base/src/org/compiere/model/X_C_ProjectProcessorQueued.java
- base/src/org/compiere/model/X_C_ProjectTask.java
- base/src/org/eevolution/model/I_C_ProjectProcessor.java
- base/src/org/eevolution/model/I_C_ProjectStatus.java
- base/src/org/eevolution/model/X_C_ProjectProcessor.java
- base/src/org/eevolution/model/X_C_ProjectProcessorLog.java
- base/src/org/eevolution/model/X_C_ProjectStatus.java
- migration/390lts-391/04410_2202_Add_Support_Project_Processor.xml
- org.adempiere.project/src/main/java/org/compiere/model/MProjectProcessorChange.java
- org.adempiere.project/src/main/java/org/compiere/model/MProjectProcessorQueued.java
- org.adempiere.project/src/main/java/org/compiere/model/ProjectProcessorModelValidator.java
- org.adempiere.project/src/main/java/org/compiere/util/ProjectProcessorUtils.java
- org.adempiere.project/src/main/java/org/eevolution/model/MProjectProcessor.java
- org.adempiere.project/src/main/java/org/eevolution/model/MProjectProcessorLog.java
- org.adempiere.project/src/main/java/org/eevolution/model/MProjectStatus.java
- serverRoot/src/main/server/org/compiere/server/AdempiereServer.java
- serverRoot/src/main/server/org/compiere/server/AdempiereServerMgr.java
- serverRoot/src/main/server/org/compiere/server/ProjectProcessor.java
Fixes: #2202 
This pull request add support to Project Processor, for notifications via email or Adempiere Notice and changes on project status automatically.
The Project Processor, send notifications when has changes on Project, Phases and Task.
In the Project Processor Setting it can defined an Project Processor for Project Type or Project Task Category and setting different Mail Templates for every one, or only one Project Processor Setting for all notifications.
Email Example when add Project Manager on Project Standard:
> Add Support to Project Processor, remplace #2530 

- base/src/org/compiere/model/MTable.java
- base/src/org/compiere/model/MTree.java
When the table is not translated and the windows associated is tree type the window stay finding translation.
> Fixed error missing translation on Custom Tree when the table is not translated

- base/src/org/compiere/model/GridWindowVO.java
Currently after add [ASP functionality](https://github.com/adempiere/adempiere/pull/2438) I find a error with Document Action, the problem is:
A Sales Order with **Completed** status can be: **Re-Activate** / **Void** / **Close**. The problem is that now just show **Close** action, see the gif
The bug is because I get a tab ID isntead table ID for GridWindowVO
See:
<pre>
if (mWindowVO.AD_Table_ID == 0)
mWindowVO.AD_Table_ID = tab.getAD_Tab_ID();
</pre>
After fix it now is ok:
I apologize for add this bug for trunk
Best regard
> Fixed error with BaseTable_ID from context

- base/src/org/spin/process/ExportSurrogateKeyToMigration.java
- base/src/org/spin/process/ExportSurrogateKeyToMigrationAbstract.java
- migration/392lts-393lts/04670_2564_Add_Parameter_Export_Surrogate_Key.xml
This pull request allows generate only missing UUID from ADempiere seed, note that just need set a flag named **Only UUID Missing** 
See: 
Related: #2564
> Add support to parameter on export surrogate key for missing UUID

- base/src/org/adempiere/model/MView.java
Currently exists a helper method for get dynamically a SQL from Browser View named **getSQLFromView(int AD_View_ID, String trxName)** if it is called with a example like Requisition View the result is:
```SQL
SELECT r.AD_OrgTrx_ID as Trx Organization,r.AD_Client_ID as Client,r.C_Project_ID as Project,r.User1_ID as User List 1,r.IsActive as Active,r.Processed as Processed,r.DocAction as Document Action,r.DocumentNo as Document No,r.DocStatus as Document Status,r.Processing as Process Now,r.Posted as Posted,r.IsApproved as Approved,r.Updated as Updated,r.Created as Created,r.TotalLines as Total Lines,r.C_DocType_ID as Document Type,r.Help as Comment/Help,r.PriorityRule as Priority,r.DateRequired as Date Required,r.DateDoc as Document Date,r.Description as Description,r.ProcessedOn as …
```
> Fixed error with alias for generated SQL for Smart browser

- base/src/org/adempiere/pipo/handler/ReferenceElementHandler.java
When a packout is generated for reference with validation type table, it does not export the reference table record.
Example: 
```
<GenericPO_AD_Reference AD_ReferenceUUID="3b56cf00-66d9-11e9-97d0-0242ac140008" TableNameTag="AD_Reference" TableIdTag="102" IsActive="true" ValidationType="T" Help="" IsOrderByValue="false" VFormat="" Name="R_Request ReferenceNo" Description="" EntityType="CUST" UUID="3b56cf00-66d9-11e9-97d0-0242ac140008"/>
```
Now:
```
<GenericPO_AD_Reference AD_ReferenceUUID="3b56cf00-66d9-11e9-97d0-0242ac140008" TableNameTag="AD_Reference" TableIdTag="102" IsActive="true" ValidationType="T" Help="" IsOrderByValue="false" VFormat="" Name="R_Request ReferenceNo" Description="" EntityType="CUST" UUID="3b56cf00-66d9-11e9-97d0-0242ac140008"/>
<GenericPO_AD_Ref_Table …
```
> #2612 Solve error for Reference Validation Type Table

- base/src/org/compiere/wf/MWFNextCondition.java
- migration/392lts-393lts/04710_Increase_WF_Condition_Column_Size.xml
Currently is very useful when a client want to use workflow approval for ADempiere, however is nice to have a way for get SQL values to compare for condition of node.
A simple example is that a requisition must be add to approval level when **TotalLines** > **ApprovalAmt** of user.
Note that **ApprovalAmt** is  only a example of column.
The current problem is that if you want to compare values is allowed only values of PO or fix values, example:
**TotalLines** > **100**
or
**DateRequired** <> **DateDoc**
I want to compare **TotalLines** with **ApprovalAmt** of User table and need make a query to AD_User:
```SQL
@SQL=SELECT ApprovalAmt FROM AD_User WHERE AD_User_ID = @SalesRep_ID@
```
After change is possible compare values with SQL
> Add support to SQL values on Workflow node condition

- base/src/org/adempiere/pipo/PoFiller.java
- base/src/org/adempiere/pipo/handler/GenericPOHandler.java
The problem is that when a table is multy-key (Expample AD_Ref_Table), it throw a error importing with packing.
The error is duplicate key for **AD_Reference_ID**.
This pull request resolve the error and allows import multy-key tables finding by **UUID** or **parent keys**
> Add support to multy-key tables

- base/src/org/compiere/model/MPaySelectionCheck.java
Currently exists a flag named **Payroll Account** on BP Bank account that should set as default account for pay from payroll.
This pull request add support to get **payroll account** of employee when payment selection is created from payroll process.
> Add support to payroll account for payment selection from payroll

- org.adempiere.request/src/main/java/org/compiere/model/MMailText.java
Currently I have follow Mail text Header 
```Shell
@Subject@ Mail Text Example
```
Using previous mail text for a request I noticed that my mail text header is unparsed:
The problem is that is not exists a parse value for User / BP or current PO then is unparseable.
I fix it here
> Fixed error with Mail text for values

- client/src/org/compiere/apps/APanel.java
- client/src/org/eevolution/form/VBrowser.java
- org.adempiere.pos/src/main/java/ui/swing/org/adempiere/pos/POSActionMenu.java
- zkwebui/WEB-INF/src/org/eevolution/form/WBrowser.java
Currently if I want to overwrite a Where clause for a Smart Browser it not work, a example:
Original Browser: Create Payment Selection (From Invoice)
Original Where Clause: 
```SQL
inv.DocStatus IN('CO')
```
Custom Where Clause from Smart Browser Customization window: 
```SQL
inv.DocStatus IN('CO') AND inv.DateInvoiced = now()
```
The new Custom **Where Clause** should overwrite original where clause according with https://github.com/adempiere/adempiere/pull/2438 
The problem is that Smart Browse calling from Windows not have a calling with **ASPUtil**
With this pull request it worked
> Fixed error with overwrite Smart Browser for Where clause

- base/src/org/adempiere/pipo/AbstractElementHandler.java
- base/src/org/adempiere/pipo/IDFinder.java
- base/src/org/adempiere/pipo/handler/GenericPOHandler.java
The problem is that when a tree node is exported the parent node UUID exported is wrong. It is because not exist a filter by Tree and Parent Node ID
> Fixed Error with parent UUID reference for packout

- base/src/org/compiere/model/PO.java
Fixed error with new value as null.
Test case (As Garden World):
- Go to Business Partner
- Select a BP with a language configured
- Unselect language
- Save
The result is that language is not setted as null
This was introduced by myself here: https://github.com/adempiere/adempiere/pull/2628 I apologize by it
> Fixed problem with new value as null, this bug was introduced by myself

- base/src/org/compiere/model/I_AD_Tree.java
- base/src/org/compiere/model/MTree.java
- base/src/org/compiere/model/PO.java
- base/src/org/compiere/model/X_AD_Tree.java
- base/src/org/compiere/print/ServerReportCtl.java
- base/src/org/compiere/process/TreeMaintenance.java
- client/src/org/compiere/grid/GridController.java
- client/src/org/compiere/grid/tree/AdempiereTreeModel.java
- client/src/org/compiere/grid/tree/VTreePanel.java
- migration/392lts-393lts/04720_Add_Support_to_Tree_Search_Field.xml
- zkwebui/WEB-INF/src/org/adempiere/webui/component/ADTreeOnDropListener.java
This pull request, add support to parent identities and order columns for tree windows. In the tree definition add sort and parent Columns, for setting parent record and order column for the tree. 
On this example i setting ParentElementValue_ID for parent and Value for sort column:
for test parent setting i add a new accounting element value with parent account 14-Inventory:
on save this element value this is regrouped inside 14-Inventory branch on the tree:
for test sort setting i add a new accounting element value with value 13.1:
on save this element value this is regrouped inside 13-Investments branch on the tree:
> Add support to parent column and order column for tree window

- zkwebui/WEB-INF/src/org/adempiere/webui/panel/AbstractADWindowPanel.java
Add support to overwrite Browser from ASP for Create From calling
the problem is that Smart Browser is overwrite from ASP when are called from menu but for Create from called is not overwrite
> Fixed error with Smart Browse for ASP on ZK UI

- base/src/org/adempiere/pipo/handler/ViewElementHandler.java
Currently if a Smart Browser is exported the order for export it:
- View
- View Definition
- Vew Definition Column
- Process
The problem is that if the tables linked to View Definition no exists then the packin is wrong
> Add table to Smart Browser export

- base/src/org/adempiere/pipo/PoFiller.java
The problem is that if you try export a timestamp like **Valid From** is exported as long value but when is imported is taked as String
See:
Here a log:
```Shell
java.lang.IllegalArgumentException: Timestamp format must be yyyy-mm-dd hh:mm:ss[.fffffffff]
at java.sql.Timestamp.valueOf(Timestamp.java:204)
at org.adempiere.pipo.PoFiller.getValueFromType(PoFiller.java:136)
at org.adempiere.pipo.PoFiller.setAttribute(PoFiller.java:105)
at org.adempiere.pipo.handler.GenericPOHandler.startElement(GenericPOHandler.java:176)
at org.adempiere.pipo.PackInHandler.startElement(PackInHandler.java:365)
at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
at …
```
> Fixed error with timestamp values

- base/src/org/adempiere/pipo/handler/GenericPOHandler.java
The problem:
Now is possible import packing with validation for update column, example:
- First test case: 
**Current Element:** Name
**Current Lenght:** 30
**Current Updated:** 2019-01-01 : 01:50
**Imported Element:** Name
**Imported Length:** 60
**Imported Updated:** 2019-01-01 : 01:51
**Result:** Imported is applied
- Second test case:
**Current Element:** Name
**Current Lenght:** 30
**Current Updated:** 2019-01-01 : 01:51
**Imported Element:** Name
**Imported Length:** 30
**Imported Updated:** 2019-01-01 : 01:51
**Result:** Imported is unaplied
- Third test case:
**Current Element:** Name
**Current Lenght:** 30
**Current Updated:** null
**Imported Element:** Name
**Imported Length:** 60
**Imported Updated:** 2019-01-01 : 01:51
**Result:** Imported is unaplied (Here is a bug)
This pull …
> Add support to updated values for overwrite local changes

- base/src/org/compiere/model/MPInstance.java
Hi everibody, this pull request resolve a little bug with ASP for process name, the step for reproduce it is follow:
- Make login as System Administrator using es_MX language:
- Go to Role Access Update
- Run process
- Now make login as System Adminitrator using en_US (Base Language):
- Note that Role Access Update now is showed like: **Actualizar Rol** 
See this gif:
See the process name, description and help changed:
The problem is that tha cache object is used for change process statistics instead loaded object.
After change you can see the same test with cache reset:
Previous pull request: https://github.com/adempiere/adempiere/pull/2651
> fixed error with translation overwrite for process

- base/src/org/compiere/util/TimeUtil.java
Currently exists a helper method for get days between two dates:
```Java
TimeUtil.getDaysBetween(Timestamp, Timestamp, int...);
```
Start Date: 2019-06-16
End Date: 2019-06-30
Count Day: Sunday
Result: 2 (exists two sundays between two dates)
Note that begin date is a sunday
I want to add a flag (with keep back compatibility) for count the first day
```Java
TimeUtil.getDaysBetween(Timestamp, Timestamp, boolean, int...);
```
After change:
Start Date: 2019-06-16
End Date: 2019-06-30
Count Day: Sunday
Result: 3 (exists three sundays between two dates including first sunday)
> Add helper method for get days between including current day

- org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/model/MHRProcess.java
This add more info to #761
Currently, the payroll processing have the follow values:
- By Run:
- **process**: MHRProcess Object
- **_Process**: HR_Process_ID int
- **_Period**: HR_Period_ID int
- **_Payroll**: HR_Payroll_ID int
- **_Department**: HR_Department_ID int
- **_From**: StartDate (Payroll) Timestamp
- **_To**: EndDate (Payroll) Timestamp
- **_HR_Payroll_Value**: Current Payroll Value String 
- By Employee run:
- **_DateStart**: StartDate (Employee) Timestamp
- **_DateEnd**: EndDate (Employee) Timestamp
- **_Days**: Days between StartDate (Payroll) and EndDate (Payroll) int
- **_C_BPartner_ID**: C_BPartner_ID int
- **_HR_Employee_ID**: HR_Employee_ID int
- **_C_BPartner**: MBPartner Object
- **_HR_Employee**: MHREmployee Object
- **_HR_Employee_ValidFrom**: (Employee valid from): …
> Add contract for Employee information

- migration/392lts-393lts/05030_2674_Fixed_Validation_for_BankStatementMatcher.xml
Fixed error woth validation for bank statement matcher
see gif
Fixes: #2674
> Add validation for field level instead column level for Bank Statement

- base/src/org/adempiere/engine/AverageInvoiceCostingMethod.java
- base/src/org/adempiere/engine/AveragePOCostingMethod.java
- base/src/org/adempiere/engine/IDocumentLine.java
- base/src/org/adempiere/engine/StandardCostingMethod.java
- base/src/org/compiere/model/MInOutLine.java
- base/src/org/compiere/model/MInventoryLine.java
- base/src/org/compiere/model/MLandedCostAllocation.java
- base/src/org/compiere/model/MMatchInv.java
- base/src/org/compiere/model/MMatchPO.java
- base/src/org/compiere/model/MMovementLine.java
- base/src/org/compiere/model/MOrderLine.java
- base/src/org/compiere/model/MProductionLine.java
- base/src/org/eevolution/model/MPPCostCollector.java
- org.adempiere.project/src/main/java/org/compiere/model/MProjectIssue.java
When one inventory document is reversed and generate cost transaction the process delete the cost transaction but don't generate again.
see this example:
see this example with the fixes:
> Fix error on generate cost detail with reversed inventory documents

- base/src/org/compiere/process/StatementCreateFrom.java
Occasionally on the swing view in create from bank statement when ordering columns the payments is created with incorrect amounts.
This change ensures that the amount of lines created correspond to the payments.
> Change for get payment amount from Payment Object Selected

- client/src/org/compiere/print/Viewer.java
- zkwebui/WEB-INF/src/org/adempiere/webui/window/ZkReportViewer.java
This pull request fix a error with ASP with NPE for search inside reports:
Step by Step
1. Configure ASP for a customer
2. Open A window like product
3. Go to Report and show it
4. Make click on **find** button
```Java
===========> zkoss.handleError:1130: >>java.lang.NullPointerException
>>	at org.adempiere.webui.window.ZkReportViewer.launchProcessPara(ZkReportViewer.java:1268)
>>	at org.adempiere.webui.window.ZkReportViewer.cmd_find(ZkReportViewer.java:1233)
>>	at org.adempiere.webui.window.ZkReportViewer.actionPerformed(ZkReportViewer.java:767)
>>	at org.adempiere.webui.window.ZkReportViewer.onEvent(ZkReportViewer.java:745)
>>	at org.zkoss.zk.ui.impl.EventProcessor.process0(EventProcessor.java:197)
>>	at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:141)
```
> Fixed error with NPE for search from report

- base/src/org/compiere/model/MPayment.java
- migration/392lts-393lts/05410_Add_Reverse_Collect_Validation.xml
This pull request just add a validation for collects.
1. Create a collect from Cash Journal (as bank)
2. Make a cash closing
3. Make a deposit from cash selecting the collect created
4. Reverse collect from cash
The problem is that a collect when is transfered for bank should not will be reversed if deposit is completed or closed.
> Add validation for Collect when it alreasy exist for deposit

- base/src/org/compiere/acct/Doc.java
- base/src/org/compiere/acct/Doc_AllocationHdr.java
- base/src/org/compiere/acct/Doc_Payment.java
- base/src/org/compiere/model/I_AD_OrgInfo.java
- base/src/org/compiere/model/MOrgInfo.java
- base/src/org/compiere/model/MPayment.java
- base/src/org/compiere/model/X_AD_OrgInfo.java
- base/src/org/compiere/model/X_C_Payment.java
- base/src/org/compiere/process/BankStatementPayment.java
- base/src/org/compiere/process/LoadBankStatement.java
- base/src/org/compiere/process/LoadBankStatementAbstract.java
- base/src/org/spin/process/PaymentIdentify.java
- base/src/org/spin/process/PaymentIdentifyAbstract.java
- db/ddlutils/oracle/views/RV_PAYMENT.sql
- db/ddlutils/postgresql/views/RV_PAYMENT.sql
- migration/392lts-393lts/05400_Add_Unidentified_Payment_Support.xml
This pull request allows define a flow from the folow:
1. Load Bank statement
2. Create Match from Imported payment and Current movements
3. Create Payment / Bank Charge / Unidentified Payments from Bank Statement
4. Complete Bank Statement
5. Identify a Payment / Receipt
Is very nice for a complete wotk of financial operator, see gif
The result is using **Bank Unidentified Receipts** for all generated payments as Unidentified with a flag **Unidentified Payment**
Test case:
- I watch a bank receipt for 50 USD
- The bank statement is loaded and is generate a collect by 50 USD with a BP Unidentified
- When I can identify it then is generate a collect with -50 USD with the same BP that origin Collect 
- Also is generate a new collect with real BP instead and ready for allocate
> Add support to unidentified payments for Bank

- org.eevolution.warehouse/src/main/java/base/org/spin/form/OutBoundOrder.java
- org.eevolution.warehouse/src/main/java/ui/zk/org/spin/form/WOutBoundOrder.java
Step by Step:
1. Generate a Sales Order with 10 units for a product
2. Generate a outbound order from Form for generate Outbound order (From Sales Order / Distribution Orders) with 10 units for product
3. Generate Shipment from Outbound order with 10 units of generated outbound order
4. Try generate other outbound order for 5 units remaining of sales order
Note that the order line is missing, this because the validation for generate order is:
QtyOrdered - QtyDelivered - QtyInTransit (Quantity on Outbound Order not shipped)
The problem is that QtyInTransit have quantities that was shipped then the result si bad.
QtyOrdered = 15
QtyDelivered = 10
QtyInTransit = 10
Result = 15 - 10 - 10 = -5
The correct behavior is:
QtyOrdered = 15
QtyDelivered = 10
QtyInTransit = 0
Result = 15 - 10 - 0 = 5 …
> Fixed error with transit quantity when a Outbound order is delivered

- base/src/org/compiere/model/MBankStatement.java
Hellow this pull request resolve a critical bug with bank statement when is voided with unprocessed document.
Fixed: #2841
> Fixed error with bank statement voided

- org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/model/MHRMovement.java
When a rule return a NaN (Not a Number) error this is not showed to user and is very hard identify what is the source error.
This pull request resolve this error and improve parse from object to double.
> Fixed error with know error

- base/src/org/compiere/model/MBPGroup.java
- base/src/org/compiere/model/MBPartner.java
Currently when a business partner is saved is called a BP group from it but transaction name is not used for it.
> Add transaction name for business partner on beforeSave method

- base/src/org/compiere/model/MPayment.java
fixes https://github.com/adempiere/adempiere/issues/2876
Result:
The line before last was created by a POS payment, the last by a cash payment, tendertype cash
> adempiere #2876 Duplicate BankstatementLine for Pos Payments

- base/src/org/compiere/model/MCommission.java
- org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/model/MHRProcess.java
Currently exists a method for get commission amount from payroll process
```Java
getCommissionAmt
```
This method allows get commission from employee from payroll, the problem is that transaction name is null and can be keep a transaction for long time while payroll process is processed.
This pull request just add transaction name for method.
> Fixed error with long time for commission when is called from payroll

- base/src/org/compiere/model/MCommissionRun.java
Step by Step
- Create a new Commission Run
- Select Document Base Type "Receipt"
- Select flag "List Detail"
- Prepare commission
This show the follow error:
```Shell
caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "C_Payment"
Position: 324; State=42601; ErrorCode=0
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
at …
```
> Fixed error with syntax error for commission paid when list details is flagged

- base/src/org/compiere/model/MPaySelectionCheck.java
The problem:
When is created a collect from Payment / Collect window ADempiere automatically create a payment selection when is printed the payment.
The payment selection is ok and allows show a detail from collect, the problem is that if is selected a invoice with open amount the column "Open Amount" is setted with payment amount instead real open amount and report is wrong.
> Fixed error with open amount for receipt created directly on payment / Colect

- utils/RUN_ImportAdempiere.bat
- utils/RUN_ImportAdempiere.sh
Updates the RUN_ImportAdempiere.bat/sh scripts to take an argument "silent" which will cause the script to run without pause.  This is useful when using the script in another script such as when creating a docker container.  
The scripts will currently accept any number of arguments and, if any are found, will import the reference database instead of the seed.  This change has no impact on the current use of the scripts.
> #2926 Add a silent mode to the RUN_ImportAdempiere scripts.

- base/src/org/compiere/model/MMigrationStep.java
Fixes #2914 
During rollback of a migration, its not enough to use deleteEx with force set to true.  For Entity Types, the flag .setIsDeleteForced must be set to true prior to the delete.
> #2914 - During rollback of a Migration Step, force delete of an entity type.

- base/src/org/compiere/process/InOutCreateFrom.java
When the receipt is create form an invoice allocated an sales order the sales order line is not referenced.
> Add Sales Order line reference on create Receipt from Invoice

- migration/393lts-394lts/05560_2968_ShowOppositeSignForALineCalculated.xml
Fixes #2968
Now the Show Opposite Sign is displayed.
> #2968 Enable Sign Change for Calculated Lines in Financial Reports

- base/src/org/compiere/process/ImportInventory.java
- base/src/org/compiere/process/ImportInventoryAbstract.java
The problem: if you try import a physical inventory from ADempiere importer currently not exists a validation for duplicate key before import then the error throw when physical inventory line is saved but the user can't see the error, a console log from debugger can show the problem but import inventory line don't have error:
```Shell
org.adempiere.exceptions.AdempiereException: ERROR: duplicate key value violates unique constraint "m_inventoryline_productlocattr"
Detail: Key (m_inventory_id, m_locator_id, m_product_id, m_attributesetinstance_id)=(1000554, 1000048, 1000401, 0) already exists.
``` 
This change allows see the error line by line and validate before import, is very beautiful for end user
See a gif after fix it:
> Fixed error with duplicate key for inventory import

- base/src/org/compiere/model/MCommissionRun.java
Currently exist a problem for commission calculation:
Step for reproduce
- Create a new commission with monthly frequency
- Set date for Start a End Date
- Note that when is processed the document is change dates for Start Date and End Date
This pull request resolve it
> Fixed error with date for commission run

- org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/process/LeaveCreditManual.java
Fixed error with Date validation for create leave manual from employee window.
The problem is that when is validate the last run or the valid from for employee exist a wrong validation.
This pull request resolve it.
> Fixed error with validation for dates on Create Leave Manual

- base/src/org/adempiere/model/GenericZoomProvider.java
The zoom Across is a dynamic way for get reference from a record to other, currently exists a class for resolve all business model for it.
The problem: if You need implement it for multiples tables joined not exist a way for differenciate tables from zoom, a example of current behavior is that a Zoom from Business Partner to Valid combination is the follow:
```SQL
SELECT COUNT(*) FROM C_ValidCombination WHERE (C_BPartner_ID=113)
```
This change propose the follow query:
```SQL
SELECT COUNT(*) FROM C_ValidCombination WHERE (C_ValidCombination.C_BPartner_ID=113)
```
Just add Table name before column name and it worked ok 
Note: this change already exists for Zoom based on reference but for zoom dynamic PO does not exist
> Fixed error with ambiguous reference for zoom across

- base/src/org/compiere/report/FinStatement.java
Currently, at generating Financial Statement report and filter by Organization, generate an error by a ambiguous column.
See Parameters filter:
Errors with PostgreSQL database:
Errors with Oracle database:
Also, the query for Beginning Balance is generating response times very high, by the subqueries in the select clause.
see current method:
see the proposed method:
> Fix ambiguous column and optimize previous balance query in Financial Statement Report

- base/src/org/compiere/model/MCommissionRun.java
This pull request resolve a problem with commission for calculation based on invoices totally paid, the problem is that search criteria is based on date ranges **>** and **<** but the correct search criteria should be **>=** and **<=**
> Fixed error with last month day for commission totally paid

- org.adempiere.request/src/main/java/org/compiere/model/MRequest.java
Step for reproduce:
- Create a new user without email or pass
- login wth new user
- Create a new request
- save (here is the error)
```Java
-----------> GridTable.saveWarning: Error -  [52]
-----------> GridTable.saveWarning: Error -  [52]
-----------> MRequest.saveFinish: afterSave [51]
java.lang.NullPointerException
at org.compiere.model.MRequest.sendNotices(MRequest.java:1146)
at org.compiere.model.MRequest.afterSave(MRequest.java:993)
at org.compiere.model.PO.saveFinish(PO.java:2352)
at org.compiere.model.PO.saveNew(PO.java:2951)
at org.compiere.model.PO.save(PO.java:2236)
at org.compiere.model.GridTable.dataSavePO(GridTable.java:2192)
at org.compiere.model.GridTable.dataSave(GridTable.java:1516)
at org.compiere.model.GridTab.dataSave(GridTab.java:997)
at …
```
> Fixed error with NPE for request when sender not have mail

- base/src/org/spin/util/support/AppSupportHandler.java
The problem:
Currently the App registration instance is loaded when not exists this but after loaded instance always keep the same registration ID, it is a error because never is changed for distints applications
> Fixed error with reload registration ID

- migration/393lts-394lts/05610_Fixed_document_flag_for_tables.xml
After issue #94 each table can be flagged as **Document**, the change is nice for add defult columns to document.
This pull request set default **IsDocument** as true when a document have **DocAction** column and is not a view:
```SQL
A simple SQL:
SELECT TableName, Name FROM AD_Table WHERE IsView = 'N' AND TableName NOT LIKE 'I_%' AND EXISTS(SELECT 1 FROM AD_Column c WHERE c.AD_Table_ID = AD_Table.AD_Table_ID AND c.ColumnName IN('DocStatus', 'DocAction'));
tablename       |             name              
-----------------------+-------------------------------
M_InOut               | Shipment/Receipt
M_Inventory           | Phys.Inventory
M_Movement            | Inventory Move
C_Cash                | Cash Journal
WM_InOutBound         | In & Out Bound Order
M_Production          | …
```
> Add document Flag by default

- base/src/org/spin/util/ASPUtil.java
- migration/393lts-394lts/05600_Fixed_error_with_browse_key.xml
The problem: currently if a browse field is hidden and is flagged as **IsKey** should be showed like all fields flagged as **IsQuery**, **IsDisplayed** or **IsIdentifier**. This problem cause that if a field flagged as **IsKey** and **IsDisplayed** is set to IsDisplayed = false the result is a key that is not exist a way for see if the browser have more than one key.
I just change the browse field condition from:
```SQL
(IsDisplayed='Y' OR IsQueryCriteria='Y' OR IsIdentifier = 'Y')
```
To
```SQL
(IsDisplayed='Y' OR IsQueryCriteria='Y' OR IsIdentifier = 'Y' OR IsKey = 'Y')
```
Also add a validation for isActive for ASPUtil class
> Fixed error with not displayed browse key

- base/src/org/compiere/model/MColumn.java
This pull request resolve a problem with StackOverFlow when a column is inserted from XML Migration.
The problem is that by default the column attributes is created from element definition, if a column is created as new and the element is defined like Search in reference the reference value on column is setted from element and it generate a recursive search for reference.
> Fixed error with StackOverFlow for MColumn

- base/src/org/compiere/model/GridField.java
when a Smart Browse have a default value for Date Field, the default value is taked as **Date + Time** instead **Date**.
A simple example:
For Bank Statement Closing of POS the filter is based on **DateTrx (Date)** the current behavior is that all date fields are **2020-03-20 00:00:00**.
When default value is loaded on gridfield have time also, then the value for **DateTrx (Date)** is **2020-03-20 23:13:00** and **DateTrx_To (Date)** is **2020-03-20 23:13:00** instead **2020-03-20 00:00:00** and filter is:
```SQL
DateTrx (**2020-03-20 00:00:00**) BETWEEN '2020-03-20 23:13:00' AND '2020-03-20 23:13:00'
```
Here some more graphic before change:
After change:
> Fixed error with default value when a field is Date instead Date + Time

- base/src/org/compiere/model/I_C_DocType.java
- base/src/org/compiere/model/MOrder.java
- base/src/org/compiere/model/X_C_DocType.java
- migration/393lts-394lts/05620_Add_Invoice_Order.xml
- migration/393lts-394lts/05620_Add_Pre_Invoiced_Order.xml
- migration/393lts-394lts/05630_Add_Invoice_Order_Example_Data_for_Garden_World.xml
Currently exists many Sub-Document Type for handle order:
- Standard = **SO**: Standard order for generate invoices and shipment
- Quotation = **OB**: Quotation (with reserve)
- Proposal = **ON**: Proposal (without reserve)
- Prepay = **PR**: Validate prepay before complete
- POS = **WR**: Generate Invoice and shipment after complete
- Warehouse = **WP**: Used for make a picking
- OnCredit = **WI**: Credit Order
- RMA = **RM**: Return Order Authorization
This pull request allows add a new Sub Document Base for Order **invoiced automatically** used for generate invoiced after complete order, is nice because you can generate invoice and collect it after complete.
The warehouse manager can get order for deliver it. This order is very usefull for Retail where is invoiced and collect a product …
> Add Invoice Order support

- base/src/org/compiere/process/ReplenishReport.java
This pull request resolve a issue with a AND condition unnecessary for query of replenish report
Fixes: #2721 
```SQL
or at or near "AND" Position: 312, SQL=SELECT QtyToOrder,C_DocType_ID,Updated,ReplenishType,QtyOnHand,Order_Pack,QtyReserved,QtyOrdered,ReplenishmentCreate,M_WarehouseSource_ID,Order_Min,Level_Min,Level_Max,AD_Org_ID,AD_Client_ID,AD_PInstance_ID,M_Warehouse_ID,M_Product_ID,UpdatedBy,UUID,C_BPartner_ID FROM T_Replenish WHERE (AD_PInstance_ID=? AND AND C_BPartner_ID > 0 AND M_WarehouseSource_ID IS NULL) ORDER BY M_Warehouse_ID, M_WarehouseSource_ID, C_BPartner_ID
```
> Fixed error with AND condition for replenish report

- base/src/org/compiere/model/MCommissionGroup.java
- base/src/org/compiere/model/MCommissionRun.java
Step by Step:
- Create a Commission Group
- Create (N) commission definition fromCommission group
- Create a commission Run
- Select previous commission group selected
- Run Document action to prepare
This pull request resolve a error when I try process a commission run based on commission group instead commission, the error is:
```SQL
===========> Query.list: SELECT Name,Processing,IsDaysDueFromPaymentTerm,Updated,Created,IsTotallyPaid,IsActive,IsAllowRMA,FrequencyType,CreateFrom,DateLastRun,Description,ListDetails,DocBasisType,C_CommissionGroup_ID,AD_Org_ID,C_Commission_ID,AD_Client_ID,C_BPartner_ID,C_Currency_ID,CreatedBy,UpdatedBy,C_Charge_ID,UUID,C_CommissionType_ID FROM C_Commission WHERE (C_CommissionGroup_ID=? IsActiveY) ORDER BY C_BPartner_ID [63] …
```
> Fixed error with commission group for commission run

- client/src/org/eevolution/grid/Browser.java
This problem just sucess with axis columns for Smart Browse, the problem is that axis column does not search by **ColumnSQL** or **ColumnName**, only search by **ColumnName**, see a definition:
Note that exist a **Column SQL** value
The result before change:
The result after change:
> Fixed error with axis column for Smart Browser

- base/src/org/eevolution/process/BankTransfer.java
- base/src/org/eevolution/process/BankTransferAbstract.java
- migration/393lts-394lts/05650_Add_POS_Open_process.xml
This process allows a Cash Opening for POS using standard bank transfer and just add **POS** reference and **Conversion Type** see a gif:
> Add Process for Open POS cash

- base/src/org/compiere/model/MBankStatementLine.java
The problem:
The convrsion rate is finded but never is allocated to payment amount:
```Java
maybeCurrencyRate.ifPresent(currencyRate -> paymentAmount.multiply(currencyRate)
.setScale(currency.getStdPrecision(), BigDecimal.ROUND_HALF_UP));
```
then a payment with a distint currency of bank account never is converted, this pull request change it
> fixed error with conversion rate for bank statement from payment

- base/src/org/compiere/model/MBankStatementLine.java
Currently if a payment is with 0 amount and is added to bank statement line the reference is removed, this pull request allow keep reference with payment
> Allows a payment reference with payment amount as Zero

- migration/393lts-394lts/05790_Fixes_error_with_POS_Cash_Closing.xml
The problem:
The cash closing for POS is very useful, however, exists many problem with amounts from Smart Browser rows and process parameters values, see before change:
Note that now is same values from query and parameters:
Please this pull request have multi-currency related to #3071 pull request, should see first #3071
Best regard
> Add cash closing correct values

- base/src/org/adempiere/process/ApplyMigrationScripts.java
- base/src/org/adempiere/process/MigrationLoader.java
- base/src/org/compiere/process/MigrationFromXML.java
- utils/RUN_MigrateXML.bat
- utils/RUN_MigrateXML.sh
This pull request allows define a new parameter for custom migration path, for now exists the follow parameters:
```Java
clean
force
```
**clean**: remove all files after import
**force**: apply without rollback
The change allows define a filepath
```Java
clean
force
/tmp/migration/
```
> Add support to FileName or path for Migration Loader and change log

- base/src/org/compiere/model/PO.java
**What is the bug?**
the try used for save a simple PO only validate SQLException instead any exception, then when exists a error that is not a SQL Exception the change is saved instead rollback, see old code:
```Java
try
{
// Call ModelValidators TYPE_NEW/TYPE_CHANGE
String errorMsg = ModelValidationEngine.get().fireModelChange
(this, newRecord ? ModelValidator.TYPE_NEW : ModelValidator.TYPE_CHANGE);
if (errorMsg != null)
{
log.warning("Validation failed - " + errorMsg);
log.saveError("Error", errorMsg);
if (localTrx != null)
{
localTrx.rollback();
m_trxName = null;
}
else
{
trx.rollback(savepoint);
}
return false;
}
//	Save
if (newRecord)
{
boolean b = saveNew();
if (b)
{
if (localTrx != null)
return localTrx.commit();
else
return b;
}
else
{
if (localTrx != null)
localTrx.rollback(); …
```
> Fixed error with Save from PO when a error is created from a model

- base/src/org/compiere/model/M_Element.java
- base/src/org/compiere/model/PO.java
This pull request resolve a critical error with copy values method from **GridTab**. The problem is that it does not use UUID for compare column names and exclude.
The result is that if you use copy action button from a window then the **UUID** is copied also.
> Fixed error with Copy values for UUID

- base/src/org/compiere/model/MProcess.java
- base/src/org/compiere/model/MTab.java
- base/src/org/compiere/model/MWindow.java
- base/src/org/spin/util/ASPUtil.java
The problem is that ASP get values without distingue language, the follow is a step by step for replicated;
1. Open ADempiere with Garden and **en_US** language
2. Open a window
3. Go to Logout option
4. Login with Garden and **es_MX** language
5. Open the same window of previous session
6. See all field are on **en_US** language instead **es_MX**
The problem is that return the same object for **en_US** and **es_MX**
> Fixed error with language for ASP

- zkwebui/WEB-INF/src/org/adempiere/webui/apps/AEnv.java
This is a old error from ZK UI:
Previous setup:
- Create **Role 1** with Acces to **Invoice Vendor (Read Only)**
- Create **Role 2** with Acces to **Invoice Vendor (Full)**
Step by Step:
- Login on ZK with **Role 1**
- Open Window **Invoice (Vendor)**
- Now open ADempiere from other browser
- Login on ZK with **Role 2**
- Open Window **Invoice (Vendor)**
Now see window toolbar for **Role 2** (Full Access) but is read only
> Fixed error with Window cache for ZK UI

- org.eevolution.warehouse/src/main/java/base/org/eevolution/model/MWMInOutBound.java
Currently when a delivery is generated from Smart Browser for Generate Shipment from Outbound Order the shioment is closed instead complete.
This problem is because processIt method is called two times.
See PR
> Fixed error with delivery closed generated from outbound order

- base/src/org/adempiere/model/ExportModelValidator.java
- base/src/org/adempiere/process/rpl/exp/ExportHelper.java
- base/src/org/compiere/model/I_AD_ReplicationDocument.java
- base/src/org/compiere/model/I_AD_ReplicationTable.java
- base/src/org/compiere/model/MReplicationStrategy.java
- base/src/org/compiere/model/X_AD_ReplicationDocument.java
- base/src/org/compiere/model/X_AD_ReplicationTable.java
- migration/393lts-394lts/05790_Add_Optional_Export_Format_for_Table_and_Document.xml
Just a simple change for Replication Strategy that allows select a export format by default on Table and Document, see image:
- By default and for old compatibility if a export format is not setted then the search is by Client / Table / Version
- If a export format is setted then the search is by Export Format
> Add support to Optional Export Format for Table and Documents of

- base/src/org/compiere/model/PO.java
The problem: 
When exists a error committing a change from database the user only can see a bad message "saveError", it is because the original error is not propagate to end user. A example is saving a product with a M_AttributeSetInstance_ID without reference.
The current message:
**saveError**
The real Message:
```SQL
ERROR: insert or update on table "m_product" violates foreign key constraint "mattrsetinst_mproduct"%0A Detail: Key (m_attributesetinstance_id)=(21545) is not present in table "m_attributesetinstance".%0AERROR: insert or update on table "m_product" violates foreign key constraint "mattrsetinst_mproduct"%0A Detail: Key (m_attributesetinstance_id)=(21545) is not present in table "m_attributesetinstance".
```
> Remove saveError and throw exception

- base/src/org/compiere/wf/MWorkflow.java
- base/src/org/spin/util/test/WFTestCase.java
The problem: if a process is run with batch mode == false then the transaction should be handled locally but it is not applied for **start(ProcessInfo, String)** method. 
Then when the execution is finished the transaction is not committed or rolled back, this bug cause a big problem with database because a statement is loaded without confirm, a example is the update for **Processing** column:
```SQL
UPDATE C_Order SET Processing = 'N' WHERE C_Order_ID = 1000000;
```
Note that batch mode is validated from previous method:
```Java
public static MWFProcess startWorkFlow(Properties ctx, ProcessInfo pi, int AD_Workflow_ID) {
MWorkflow wf = MWorkflow.get (ctx, AD_Workflow_ID);
MWFProcess wfProcess = null;
if (pi.isBatch())
wfProcess = wf.start(pi, pi.getTransactionName());		//	may return null …
```
> Fixed error with transaction without commit or rollback

- base/src/org/adempiere/engine/CostEngine.java
- base/src/org/compiere/acct/Doc_Invoice.java
- base/src/org/compiere/model/MLandedCostAllocation.java
Currently, when you create a vendor invoice with associated costs in a different currency of purchase receipt, this generate an difference on costing amount and accounting amount.
Show this example:
**_Invoice Vendor info_**
|**_Invoice Currency:_** EUR|
|:---|
|**_Currency Rate:_** 1.249|
|**_Costing Precision:_** 4|
|**_Invoice Amount Allocation:_** 987.63|
**_Invoice Landed Cost Allocation_**
|**Amount**|**Quantity Receipt**|
|---:|---:|
|123.45 €|27,653.00|
|123.45 €|30,000.00|
|123.45 €|30,000.00|
|123.45 €|29,986.00|
|123.45 €|26,780.00|
|123.45 €|28,632.00|
|123.45 €|6,949.00|
|123.48 €|30,000.00|
|**987.63€**|**210.000,00**|
**_Cost Generated_**
When generated costing at completing Invoice, this set current cost price   (costing amount / quantity receipt ), rounding to costing …
> Fix Landed Costs Accounting, when Vendor invoice is in another currency

- base/src/org/compiere/process/M_PriceList_Create.java
Fixed error with price list conversion when it does not exist on map
Just a little change bus is a bug:
```Java
BigDecimal conversionRate = null;
if(!conversionRateMap.containsKey(conversionRateKey)) {
conversionRate = MConversionRate.getRate(productPurchasing.getC_Currency_ID(), 
priceList.getC_Currency_ID(), 
priceListVersion.getValidFrom(), 
discountSchemaLine.getC_ConversionType_ID(), 
getAD_Client_ID(), 
priceListVersion.getAD_Org_ID());
if(conversionRate == null) {
conversionRate = Env.ZERO;
}
//	Set
conversionRateMap.put(conversionRateKey, conversionRate);
} else {
conversionRate = conversionRateMap.get(conversionRateKey);
}
```
> Fixed error with price list conversion when it does not exist on map

- base/src/org/compiere/model/MRole.java
Just a minor change but is a big error and it can cause that you see data without access, see the problem:
Test case:
Role to lock: Garden User
I only can see records of **Seed Farm Inc.** and dependents entities
Data:
BP Value: SeedFarm
BP Name: Seed Farm Inc.
- With Garden Admin Role:
- Go to Open Item Report
- Uncheck Sales transaction flag
- Run report: Note that all business partners are showed
- Go to Role and enable **Personal Lock**
- Logout
- Go to Business Partner window and find **Seed Farm Inc.**
- Lock it for **Garden User** role:
- Exclude: false
- Dependent entities: true
- Logout
- With Garden User
- Go to Open Item Report
- Uncheck sales transaction flag
- Run report
Only **Seed Farm Inc.** should be showed
It show all business partners instead
- Record Access Setup
The …
> Fixed error with bad index for whole word on column names for query and

- base/src/org/adempiere/process/CreateCustomizationFromASP.java
Step for reproduce:
- Create a ASP and Level
- Go to Menu
- Select a Folder or summary menu
- Go to process tool bar and select "**Create Customization from Menu**" process
- Fill parameters
- Run it
Result is ok and is generated all child of menu
Now:
- Go to Menu
- Select a non summary menu like **Sales Order**
- Go to process tool bar and select "**Create Customization from Menu**" process
- Fill parameters
- Run it
Result is nothing because only process summary menu instead items
> Fixed error with create customization from Menu when a menu is not

- migration/393lts-394lts/05850_Fixed_error_with_Role_Create_From_Window.xml
This pull request fixed a error with Query data for Process in Role Window.
Step for reproduct:
- Go to role window
- Go to tool bar an d press process button
- Open Smart Browser for Create Role Process from window
- Select Sales Order window
- Search
Note that all process of all tabs of Sales Order are showed but the asigned process using table **AD_Table_Process** is hidden.
> Fixed error with Smart Browser for Create Role Process from Window

- base/src/org/adempiere/model/MBrowseField.java
- client/src/org/eevolution/grid/Browser.java
See it:
Currently for a Smart Browser only is possible create dynamic columns based on Decimal Values, a example of it can be showed in **POS Cash Closing Smart** Browser see:
But what happens if I want to show any column type?
I have a change for it. See the gif:
> This change allows define a dynamic column of smart browser based on any

- base/src/org/compiere/model/MAttachment.java
Currently on save attachment file don't save file to database.
Add validation on beforesave method for fix the bug
```
protected boolean beforeSave (boolean newRecord)
{
if(isStoreAttachmentsOnFileSystem){
if (getTitle() == null || !getTitle().equals(XML)) {
setTitle (XML);
}
} else {
if (getTitle() == null || !getTitle().equals(ZIP)) {
setTitle (ZIP);
}
}
if(!AttachmentUtil.getInstance().isValidForClient(getAD_Client_ID())) {
if(isStoreAttachmentsOnFileSystem){
return saveLOBDataToFileSystem();
}
return saveLOBDataToDB();
}
return super.beforeSave(newRecord);
}	//	beforeSave
```
> Fix bug on save attachment file

- base/src/org/compiere/util/Trx.java
Hey guys this is a critical error when a process try run a separed transaction using Trx.run method like this:
```Java
Trx.run(trxName ->
{
MOrder order = new MOrder(getCtx(), orderId, trxName);
log.info(order.toString());
//
order.setDocAction(getDocAction());
if (order.processIt(getDocAction())) {
order.saveEx();
addLog(0, null, null, order.getDocumentNo() + ": @OK@");
} else {
addLog(0, null, null, order.getDocumentNo() + ": @Error@ " + order.getProcessMsg());
throw new AdempiereException(order.getDocumentNo() + ": @Error@ " + order.getProcessMsg());
}
});
```
Note that if exist a error then is create a throw exception
when a exception happened then this method should will handle it and close connection:
```Java
public static void run(String trxName, TrxRunnable r)
{
boolean localTrx = …
```
> Fixed error with transaction open and never closed for Trx.run method

- base/src/org/compiere/model/PO.java
When a replication is enabled for import data from other process the UUID is generated internally instead sed from replication source
The problem is before save using saveReplica method instead save
```Java
columnName = I_AD_Element.COLUMNNAME_UUID;
if (p_info.getColumnIndex(columnName) != -1) {
String value = get_ValueAsString(columnName);
if (Util.isEmpty(value) || !isDirectLoad) {
value = DB.getUUID(m_trxName);
set_ValueNoCheck(columnName, value);
}
}
```
Just add support to replication flag before generate UUID
```Java
columnName = I_AD_Element.COLUMNNAME_UUID;
if (p_info.getColumnIndex(columnName) != -1) {
String value = get_ValueAsString(columnName);
if (Util.isEmpty(value) || (!isDirectLoad && !isReplication())) {
value = DB.getUUID(m_trxName);
set_ValueNoCheck(columnName, value); …
```
> Fixed error when a po is save using saveReplica instead save

- base/src/org/adempiere/model/ExportModelValidator.java
- base/src/org/compiere/model/I_AD_ReplicationStrategy.java
- base/src/org/compiere/model/X_AD_ReplicationStrategy.java
- migration/393lts-394lts/05980_Add_Flag_for_Validate_Error_Replication.xml
Just a simple change but very useful:
The previous flag allows propagate a error when not exists connection or exist a error trying replicate a record
> Add support validate error from replication strategy

- base/src/org/compiere/model/ModelValidationEngine.java
- migration/393lts-394lts/06300_Add_Model_Validator_for_Client.xml
A simple change but useful, This pull request allows define model validators by client like is defined from global or system administrador. The test case was done with Garden, see a pic:
Here a gif:
also this change add a validation for prevent duplicate call for a same validator.
> Add support to model validator window for client definition

- base/src/org/compiere/process/ProcessInfo.java
Step by Step
- Call a process like Generate Shipments from Order using keys
- See it:
```Java
ProcessBuilder.create(commandReceiver.getCtx())
.process(InOutGenerate.getProcessId())
.withTitle(InOutGenerate.getProcessName())
.withParameter(InOutGenerate.M_WAREHOUSE_ID, sourceOrder.getM_Warehouse_ID())
.withParameter(InOutGenerate.DOCACTION, DocAction.ACTION_Complete)
.withSelectedRecordsIds(I_C_Order.Table_ID, Arrays.asList(order.getC_Order_ID()))
.withoutTransactionClose()
.execute(trxName);
```
When the process **InOutGenerate** is called, the flag isSelection is false because the selection keys is not used here:
```Java
/**
* 	Generate Shipments
*	@return info
*	@throws Exception
*/
protected String doIt () throws Exception
{
log.info("Selection=" + isSelection()
+ ", M_Warehouse_ID=" + …
```
> Fixed error with process infom for selection keys:

- zkwebui/WEB-INF/tld/web/core.dsp.tld
- zkwebui/WEB-INF/tld/zk/core.dsp.tld
- zkwebui/WEB-INF/tld/zul/core.dsp.tld
This pull request removes just things which mess with newest JBoss. In tag lib there are some tags <import> which seems to be not strict schema. Removing them (and one <br/> in comment) makes it possible to deploy zkwebui on new JBoss. You need just to add Adempiere.jar and AdempiereSLib into WEB-INF/lib of zkwebui.war and set property PropertyFile pointing do Adempiere.properties of your Adempiere home. When starting JBoss (you need to download it and install) with -DPropertyFile=<Adempiere.properties location> you can deploy zkwebui.war from Jboss console (port 9990)
This pull request does not contain new ZK9 or replace default JBoss. It is just clean to make it work with new  JBoss
I have tested that removing <import> tags does not makes known problems. It deploys on JBoss and Tomcat …
> Removing JBoss Wildfly 19 obstacles

- base/src/org/compiere/model/MElement.java
- base/src/org/compiere/model/MTree.java
- base/src/org/compiere/model/PO.java
- base/src/org/compiere/process/TreeMaintenance.java
- zkwebui/WEB-INF/src/org/adempiere/webui/component/ADTreeOnDropListener.java
Hi, currently exists several errors on tree maintenance creating and moving items of tree, especifically on accounting tree elements.
With this pull request, it's resolve the next problems:
- Duplicities on favourites and recent items.
- Inserting items on same tree for differents account elements.
- Inserting items on differents tree for account elements of distincts tree types.
- Translating on popup for move and insert items of tree for the zk.
Please, check if this solution is applicable
Regards
> Fixed errors on tree maintenance

- base/src/org/adempiere/controller/SortTabController.java
- base/src/org/compiere/model/GridTab.java
- client/src/org/compiere/apps/APanel.java
- client/src/org/compiere/grid/VSortTab.java
- zkwebui/WEB-INF/src/org/adempiere/webui/panel/WSortTab.java
Currently, the sort tab only filter records by parent link column, even being available the parent column on sort tab definition.
My purpose is support the parent column of the tab if this is defined.
View this example:
Table definition to be sorted:
Table definition for filter table sorted:
Window definition for sorted records
Use this parent column instead of parent link column on table sorted definition.
If the parent column on the tab is not defined use the parent link column defined on the table.
Final sorted window:
> Add Support to Parent Column on Sort Tab

- db/ddlutils/oracle/views/RV_M_Replenish.sql
- db/ddlutils/postgresql/views/RV_M_Replenish.sql
- migration/393lts-394lts/06450_Fixed_Error_with_Replenish_Browser.xml
Hey guys just a error is fixedx here:
1. As Garden World go to **Material Management** -> **Material Management Rules** -> **Product**
2. Go to product **Transplanter**
3. Duplicate it and change value to **Test1** Name to **Test 1**
4. Go to **Replenish** tab and set it with:
- Warehouse: **HQ Warehouse**
- Replenish Type: **Maintain Maximum Level**
- Minimum Level: **20**
- Maximum Level: **40**
5. Go to **Material Management** -> **Warehouse Replenish**
6. Set Warehouse (Search Criteria) to **HQ Warehouse** and run it:
- Note that **Transplanter** product exist but **Test 1** no exist
7. Create a new **Physical Inventory** for **Test 1** in any warehouse with quantity counted **3**
8. Go to **Material Management** -> **Warehouse Replenish**
9. Set Warehouse (Search Criteria) to **HQ …
> Fixed error with Replenish Warehouse when a product not have storage

- utils_dev/build.xml
because freight depends on fleet:
class `CreateFreightOrderFromPackage` imports `MDDFreight`
Hi @yamelsenih 
in the current develop branch ther ist a prolmen when building from scratch.
This pull resolves it. A small change to ` utils_dev/build.xml `
there is no issue for that
regards EUGen
> build dir="org.eevolution.fleet" prior to "org.eevolution.freight"

- db/ddlutils/postgresql/functions/altercolumn.sql
- db/ddlutils/postgresql/functions/get_all_views.sql
- migration/393lts-394lts/06420_Fixed_Error_with_Dependences_Alter_Column.xml
When a column definition is changed, example **C_Invoice.Description** and the table have dependences with view, only is used the first level for recereate views but if the table have more than one level the synchronization throw a error like this:
```Java
===========> DB.executeUpdate: INSERT INTO t_alter_column values('c_invoice','Description','TEXT',null,'NULL') [SvrProcess_2942fe33-6d68-4844-8b37-b762037ce560] [59]
org.postgresql.util.PSQLException: ERROR: Failed to recreate dependent view
Where: PL/pgSQL function altercolumn(name,name,name,character varying,character varying) line 67 at RAISE; State=P0001; ErrorCode=0
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImp …
```
> Fixed error with dependences when a column is changed

- migration/393lts-394lts/06400_Enlarge_Size_of_Name_for_Business_Partner_Location.xml
Just a minor change and very useful for enlarge size of column **Name** for table **C_BPartner_Location** to **255** instead **60**.
> Enlarge Size of Name column for C_BPartner_Location Table to 255

- base/src/org/compiere/model/MOrder.java
Just a little change but very necessary for **getLines** helper method that prevent a bad calculation for taxes and others values when a order is created from a process and **setProcessed** method is not called for line
> Fixed error with for requery necessary for getLines Method

- base/src/org/spin/process/SetupFileStorageSystem.java
Fixed error with setup file when it is getted from external storage
When a storage alredy configured is change to other exist the follow error inserting data:
```Java
===========> DB.executeUpdate: INSERT INTO AD_AttachmentReference (AD_Client_ID,AD_Org_ID,IsActive,Created,Updated,CreatedBy,UpdatedBy,UUID,AD_Archive_ID,FileHandler_ID,AD_AttachmentReference_ID) VALUES (1000000,1000000,'Y',TO_TIMESTAMP('2020-09-14 18:08:34','YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2020-09-14 18:08:34','YYYY-MM-DD HH24:MI:SS'),1000017,1000017,'32176d82-68ac-40d5-b5c3-f7676fb3f605',1000184,1000015,1002374) [POSave_b8257369-e070-43ec-9c8f-a67f31395e6f] [33]
org.postgresql.util.PSQLException: ERROR: null value in column "filename" violates not-null constraint
Detail: Failing row contains (1000000, 1000000, …
```
> Fixed error with setup file when it is getted from external storage

- base/src/org/spin/process/rpl/exp/TestReplicationStrategy.java
The last implementation for this process just export tables but documents are not implemented
> Just add support to documents on replication strategy test process

- migration/393lts-394lts/06520_Add_Fields_reference_to_Return_orders.xml
This pull request allows drill from Return Material based on Return Mterial Order to Return Material Order Window.
Return Material Vendor:
- Purchase Order: Add reference for open Return Material Order (Vendor)
- Purchase Order Line: Add reference for open Return Material Order (Vendor) Line
Return Material Customer:
- Sales Order: Add reference for open Return Material Order (Customer)
- Sales Order Line: Add reference for open Return Material Order (Customer) Line
> Add some fields for reference of Returns orders on Return Material

- base/src/org/compiere/model/I_AD_Org.java
- base/src/org/compiere/model/I_AD_OrgInfo.java
- base/src/org/compiere/model/X_AD_Org.java
- base/src/org/compiere/model/X_AD_OrgInfo.java
- migration/393lts-394lts/06900_Add_Price_Checking_Image_for_Organization.xml
Minor change for add price checking image for organization:
This can be used for load some like this: https://docs.erpya.com/es/4.0.0/adempiere/quote-to-invoice/consultation-of-product-prices.html
> Add support to Corporate Branding Image for Organization Info

- base/src/org/eevolution/model/I_HR_Department.java
- base/src/org/eevolution/model/I_HR_Employee.java
- base/src/org/eevolution/model/I_HR_Job.java
- base/src/org/eevolution/model/X_HR_Department.java
- base/src/org/eevolution/model/X_HR_Employee.java
- base/src/org/eevolution/model/X_HR_Job.java
- migration/393lts-394lts/06580_Add_Account_Dimension_payroll_support.xml
- org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/model/MHRMovement.java
This pull request allows define accounts deimensions from Employee, Job and Department
- Activity
- User1
- User2
- User3
- User4
1. Payroll Department
2. Payroll Job
3. Payroll Employee
- After save payroll movement is evaluated the accounts dimensions from **Payroll Employee**, **Payroll Job** and **Payroll Department**
- If any account dimensions has values from employee then it is setted to movement
- Else If any account dimensions has values from job then it is setted to movement
- Else If any account dimensions has values from department then it is setted to movement
> Add support to account dimensions for movements based on employee, job

- base/src/org/spin/model/I_AD_Token.java
- base/src/org/spin/model/I_AD_TokenDefinition.java
- base/src/org/spin/model/X_AD_Token.java
- base/src/org/spin/model/X_AD_TokenDefinition.java
- base/src/org/spin/process/GenerateTokenForThirdPartyAccess.java
- base/src/org/spin/process/GenerateTokenForThirdPartyAccessAbstract.java
- base/src/org/spin/util/IThirdPartyAccessGenerator.java
- base/src/org/spin/util/ThirdPartyAccess.java
- base/src/org/spin/util/TokenGenerator.java
- base/src/org/spin/util/TokenGeneratorHandler.java
- migration/393lts-394lts/06870_Add_Third_Party_Access_Token_Generator.xml
- migration/393lts-394lts/06880_Add_Default_Token_for_Third_Party_Access.xml
This pull request allows define a **Token Type** for **Third Party Access** very similar to GirHub / GitLab and other serious applications. 
With this change can exists interfaces for login based on temporal token instead **user** and **password**
- Gihub Token: https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token
- https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html
- MD5 by default
- Process for Generate Token
- Process For Revoke Token
> Add Third Party Access support for Token based on default Token

- base/src/org/compiere/print/layout/BarcodeElement.java
When a Barcode is enable for a print format item it should generate according with barcode standard rules, the problem is that if a data used for generate barcode not have the minimum for create barcode then is generate a NPE when is running report. The follow is the trace:
```Java
-----------> BarcodeElement.createBarcode: 1000016 - net.sourceforge.barbecue.BarcodeException: Invalid data length [18]
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
at org.compiere.print.layout.BarcodeElement.createBarcode(BarcodeElement.java:146)
at org.compiere.print.layout.BarcodeElement.<init>(BarcodeElement.java:57)
at org.compiere.print.layout.LayoutEngine.layoutTable(LayoutEngine.java:1823)
at org.compiere.print.layout.LayoutEngine.layout(LayoutEngine.java:481)
at …
```
> Prevent NPE for barcode report

- migration/393lts-394lts/07110_Remove_Cash_Validation.xml
This pull request just remove a validation for filter tender types of Cash window when they are **Cash** or **Credit Memo** for Payment is keep this validation
> Remove unnecessary validation of cash tender type for Cash window

- base/src/org/spin/model/I_AD_SetupDefinition.java
- base/src/org/spin/model/I_AD_SetupLog.java
- base/src/org/spin/model/MADSetupDefinition.java
- base/src/org/spin/model/MADSetupLog.java
- base/src/org/spin/model/X_AD_SetupDefinition.java
- base/src/org/spin/model/X_AD_SetupLog.java
- base/src/org/spin/process/FunctionalitySetupProcess.java
- base/src/org/spin/process/FunctionalitySetupProcessAbstract.java
- base/src/org/spin/setup/SpinContributionTestSetup.java
- base/src/org/spin/util/ISetupDefinition.java
- base/src/org/spin/util/SetupUtil.java
- migration/393lts-394lts/06630_Add_Setup_Definition_for_client.xml
- migration/393lts-394lts/06640_Add_Test_data_for_Functionality_Setup.xml
- Setup Definition
- Setup Log
- Setup Process
A example using **org.spin.setup.SpinContributionTestSetup**
- Allows define initial setup for a new functionality
- Allows create test data for testing 
This process allows define many setup similar to **Initial Client Setup** but more dynamic
> Add support to Setup for feature

- base/src/org/spin/util/ExportFormatHTML.java
when a reporte is generated as **html** format it is loaded completely in memory as **html** object before write to file, a complete file like generated from **Fact Acct Detail** can have many records and a example for a little customer can load at least **1.5 GB**
This pull reques just write the file instead load it completely in memory.
A little change but save many RAM use.
TODO: Ins nice to have pagination for **PrintData** object, it can help to improve speed and memory use for each report running
> Fixed Memmory Consumption for HTML reports

- base/src/org/compiere/model/POInfo.java
- base/src/org/compiere/model/POInfoColumn.java
Currently the transaction name is not setted when a POInfoColumn is called from PO class then when a field is referenced to Table the query for search Reference Value information is running without main transaction, this problem generate many active transaction like the follows:
```SQL
3037 | Select AD_Reference_ID FROM AD_Column WHERE AD_Column_ID=$1
```
> Just add transaction name for query based on POInfoColumn

- migration/393lts-394lts/05910_Add_Document_Base_Type_Invoice_View.xml
The original script had four steps with the same sequence number.  Two were duplicates.  The two originals needed to be applied in order but with the same sequence number, the order of application was unspecified - resulting in errors.
In this PR, I've deleted the duplicate entries and set the correct order.
I've also adjusted the Release No to 3.9.4
The correct entries are:
(New Lines 323-324)
<Step DBType="Postgres" Parse="N" SeqNo="140" StepType="SQL">
<Comments>RV_C_INVOICE</Comments>
...
and
(New Lines 403-404)
<Step DBType="Postgres" Parse="N" SeqNo="145" StepType="SQL">
<Comments>RV_C_INVOICELINE</Comments>
....
> 3292 - fixes to migration script 5910 - remove duplicate steps and set the correct sequence.

- migration/393lts-394lts/06550_Add_Collecting_Agent_Reference_to_Payment.xml
Fixes #3296.
There were four steps with sequence number zero that added views which depended on the fields added in later steps.  I moved these four to the end and the migration worked fine.
> Change the order of steps to avoid an error when the views are added before the fields they require.

- migration/393lts-394lts/07230_Fixed_error_with_Over_Under_Amount_for_Payment_Selection.xml
- Create a AP Invoice with USD 2000
- Create a Payment for created invoice with 1500, set flag over un der
amount to true
- Print payment created
- Create a new payment selection
- Search previous invoice created from SB "Create from Invoice"
The Invoice shoul be showed with:
- Grand Total: USD 2000
- Open Amount: USD 500
- Payment Amount: 500
The invoice is missing
The Create From Invoice (SB) not show a invoice after add to payment
selection and don't allows create a new payment selection for a invoice
with a previous under payment
This Pull Request resolve it
> Fixed error with payment selection for Over Under Payment

- base/src/org/compiere/model/MInvoiceLine.java
Currently, when you have an invoice and generate landed cost but you want revert the landed costs generated, is not possible because if deleted the landed cost definition don't deleted the landed costs allocation records. It causes landed costs to be generated in a document even without you want generated landed costs for the document. 
Currently, the method validate that landed cost definition and after clean the landed costs allocation
My purpose is that clean the landed costs definition and after validate landed costs definition
Current functionality:
Purposed functionality:
> Cleaning Landed Cost Allocation when don't have landed cost definition

- base/src/org/compiere/model/MPaySelectionLine.java
- base/src/org/compiere/process/PSCreateFromHRMovement.java
- migration/393lts-394lts/07170_Add_Multi_Currency_support_to_Payment_Selection.xml
This pull request allows convert to payment selection currency all documents that will be paid. Currently exists a parameter for Smart Browser called Currency but it is used as query criteria and for convert amount of document, the problem is that always is filtered from selected currency and when it is converted is based on the same currency.
Just is change the follows Smart Browsers:
- Payment Selection Create From Invoice
- Generate Payment Selection (From Invoice) 
- Payment Selection Create From Payroll Movement
> Add support to multi-currency to Payment Selection Create From:

- base/src/org/compiere/acct/Doc.java
- base/src/org/compiere/acct/FactLine.java
Hi to all, this pull request allow to control that reversed documents with document type checked with Reversal with Original Accounting.
Currently all reversed documents with the document type with this check has been posted with negative amounts, without consider the setting for allow posting negative in Accounting Schema.
see this example:
> Add support to functionality Allow Negative Posting from Accounting

- base/src/org/compiere/acct/Doc_InOut.java
When the accounting of original receipt or shipment is reset don't accounted the original document and reversal document
Before fixed:
Original Document
Reversal Document
After fixed:
Original Document
Reversal Document
> Fixed error on Accounting of Shipment/Receipt

- base/src/org/compiere/model/MPayment.java
The current behavior is that from a collect can call only invoices (no credit memo) and from a payment only can call AP invoice (no credit memo).
This pull request allows allocate a payment with a AR Credit Memo and Collect with AP Credit Memo from payment.
Note: The Allocation Form allows all it operations.
> Allows generate allocation from payment and credit memo from a payment

- zkwebui/WEB-INF/src/org/adempiere/webui/panel/AbstractADWindowPanel.java
When a client have too many record (over 500k) the zk is slowly loading
records
- Go to window (any window) and save a record: note tha tthe window
should have some 20 records
- Go to main menu and reload recent items
- Select the recent item with last record
- After open window note that exist **1/1** records
- Press new button: here the problem, note that now have **1/20**
records (20 records because the table have 20 records but if it have
500k or more then is **1/500000** instead)
Load 500k or more in one window is very hard for database and server
memory
> Fixed error with ZK panel when a window have too many record

- base/src/org/compiere/model/MOrder.java
Currently the attribute IsDiscountPrinted only is setted on Sales Order
from a callout and it is ok. The problem is when you create a sales
order without using Sales Order window.
A example is when a sales order is created from POS.
This pull request resolve it
> Fixed error for IsDiscountPrinted attribute from business partner

- base/src/org/eevolution/service/dsl/ProcessBuilder.java
See the comments in Gitter on 16 and 17 Jan 2021.
The ProcessBuilder uses a static reference to the builder instance.  When multiple process are using the ProcessBuilder class, this static reference can end up pointing at the last instance created.
Fixes #3221
> Change the internal reference in the ProcessBuilder from a static field to a non-static field.

- base/src/org/spin/model/MADToken.java
Just a little change that set client from role when a token is generated
from a role. This prevent a "Token Not Found" message
> Set client from role for third party access token

- base/src/org/compiere/model/M_Element.java
- migration/393lts-394lts/07230_Fixed_error_with_Reversal_ID_and_ReversalLine_ID.xml
- Create a Payment
- Reverse created payment
- Copy the reversed payment and complete it
Sometimes the **Reversal_ID** is flagged as **IsAllowsCopy** on true for window, then is copied for new payment, it is a error because some validator have **Reversal_ID** as value for determinate if is a voided document or not
Is a document type is flagged as **IsReversedWithOriginalAcct** as true then the account fact engine sear a reversal document for create fact and is wrong
> Fixed error with Reversed document when it is copied from window

- JasperReports/src/org/compiere/report/ReportStarter.java
When a report based on iReport have **AD_Org_ID** parameter exist a error
```XML
<parameter name="AD_Org_ID" class="java.math.BigDecimal">
<defaultValueExpression><![CDATA[]]></defaultValueExpression>
</parameter>
```
> Add backward compatibility for iReport parameters

- base/src/org/spin/util/ThirdPartyAccess.java
Currently if a user have access to System Administrator and he need
generate a Third Party Access Token is not possible because a role with
0 on ID is invalid for this.
> Fixed error with Generate Token for System Administrator role

- .gitignore
- utils_dev/properties.xml
- utils_dev/test.properties
Changes the build properties to read test properties from a file mytest.properties which the developer can add to their IDE.  mytest.properties will be ignored by git and will allow the user to enable integration testing locally.  The test.properties will control the tests performed during the Github actions run on pull requests.
This is similar to the way mybuild.properties can be used to override the build.properties. It also means the developer has less chance of changing and accidentally committing the test.properties file.
> Enable customizable test properties which don't affect the test.properties file.

- migration/393lts-394lts/07640_Update_Currency_for_Venezuela.xml
From the last year Venezuela was change the currency from VEB to VEF and
after it now is VES.
This pull request just update the current currency for Venezuela
> Update Currency for Venezuela Country

- base/src/org/spin/util/ASPUtil.java
When a Custom Window is created with level **Overwrite** this should
show the window and fields that are added on Custom window instead merge
all.
All fields are disabled but are displayed
All fields are disabled and are not displayed
> Fixed error with ASP for Overwrite definition

- base/src/org/compiere/model/MOrder.java
When is called tax calculation method for Order it use cache for get
lines and is loaded a old data for lines
- Create two products: one without tax and other with tax
- Go to POS and create a new Order
- Add as first the product without tax
- Add as second the product with tax
When is added the second product already exist some line and the tax
make a calculation based on old line without include the new
> Fixed error with tax calculation for Sales Order

- .github/workflows/main.yml
- .github/workflows/release.yml
Fixes #3383
An upgrade to Java 11 was breaking the build processes on Github.  This PR sets the java version to use at 1.8.
Both main.yml and release.yml have been updated.
> Add github actions to use a single version of java in the build tests.

- org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/model/MHRConcept.java
Currently when a concept value is changed and it have some rule using
the old value is throwed a error like it:
```Java
Record found Global Payroll Concept: Asignación Reposo Remunerado 33%
Rule: groovy:CR_SNP -> CR_SNP Salario Normal Parcial
```
The problem is that is now showed what is the concept that is changed.
This pull request just add a better message including the concept value
and name, see:
```Java
Record found Global Payroll Concept: Asignación Reposo Remunerado 33%
[Old Value: AS_RRC New Value: AS_R33% ] Rule: groovy:CR_SNP -> CR_SNP
Salario Normal Parcial
```
> Improve error message for concept beforeSave error

- base/src/org/compiere/report/FinReport.java
https://github.com/adempiere/adempiere/issues/3421
How to reproduce:
Define Userelement2_ID as accounting dimension
Create a financial report and filter for userelement2
The result is null
Correction:
Class finReport, line 125
Erroneous Code
```
if (getUserElement2Id() != 0)
parameterWhere.append(" AND UserElement2_ID=").append(getUserElement1Id());
```
Correct code
```
if (getUserElement2Id() != 0)
parameterWhere.append(" AND UserElement2_ID=").append(getUserElement2Id());
```
Result before correction:
Result after correction:
> Adempiere B#3421 Fin Report, Parameter Userelement2_ID not  assigned

- base/src/org/compiere/model/MOrderLine.java
Currently exist a validation for price list on any order when a line is
added or modify. The problem is that if you want just add a text for
description or change a account dimension the error is throwed:
```Java
-----------> MOrderLine.save: beforeSave - MOrderLine[1098206, Line=10,
Ordered=8.0000, Delivered=8.0000, Invoiced=8.0000, Reserved=0.0000,
LineNet=22143310.32] [18]
org.adempiere.exceptions.ProductNotOnPriceListException: Product is not
on PriceList - Line No:10, Product:CEMENTO GRIS GENERICO ( SACOS ) ,
Price List:Ventas (VES), Date:02/15/2021
at org.compiere.model.MOrderLine.beforeSave(MOrderLine.java:923)
at org.compiere.model.PO.save(PO.java:2170)
at org.compiere.model.GridTable.dataSavePO(GridTable.java:2192)
at org.compiere.model.GridTable.dataSave(GridTable.java:1516)
at …
```
> Remove unnecessary exception before save order line

- base/src/org/compiere/model/MDistribution.java
When have an Accounting Distribution by Organization Dimension, this don't work.
- Create a Accounting Distribution with this definition:
- find the Vendor Invoice 10000003
- Post it document and see that the distribution don't work
Change get Distribution method for comparing with Org_ID
> Fix distribution by organization dimension

- client/src/org/eevolution/grid/Browser.java
This pull request allows create a cross tab based on String values as
columns instead ID.
You can define the follow
| Document No   |      Humidity      |  Scrap |
|----------|:-------------:|------:|
|P-001 |  17.9 | 6 |
| P-002 |    15.6   |   5.4 |
| P-003 | 12.6 |    3.6 |
The search for Humidity and Scrap is based on other table that have values like 
- Humidity: **H**
- Scrap: **S**
The old support just make a query based on ID instead values.
> Add support to axis column based on Value instead id for where clause

- base/src/org/compiere/model/MProduction.java
- Create a new Production without production batch
- Add product to produce and BOM
- Complete it
When a production is created without order it make a bad validation with
order
Just validati if exist a production batch
> Fixed error with wrong validation for production

- org.adempiere.request/src/main/java/org/compiere/model/MMailText.java
- org.adempiere.request/src/main/java/org/compiere/model/MRequest.java
- org.adempiere.request/src/main/java/org/spin/model/MRNoticeTemplate.java
> Adding a clear method to empty the previous context in the MMailText

- base/src/org/compiere/process/RequisitionPOCreate.java
- Create a requisition:
- Product: PChair
- Quantity: 2
- Required Date: 2021-04-22
- Create other requisition:
- Product: Mulch
- Quantity: 3
- Required Date: 2021-04-16
- Go to Smart browser **Browse Requisition to Create PO from Requisition
Lines**
- Select Previous requisition generated
- Select a Business partner as vendor
- Check **Consolidate to one Document**
- Do it
If the flag **Consolidate to one Document** is true and a business
partner is selected in the process it will should generate one
**Purchase Order**, nevertheless, is generated two documents.
The origin of behavior is that is validate the required date of
requisition with promised date of **purchase order** header.
Note: the promised date exists also for **purchase order** line instead
With a vendor selected and …
> Create Purchase Order from Requisition have a error

- base/src/org/compiere/util/TimeUtil.java
- base/test/src/org/compiere/util/TimeUtilTest.java
Related to the GardenWorldCleanup refactoring, this moves a method from GardenWorldCleanup into the TimeUtil class.  Tests are included.
> Issue #3309 - Refactoring part 1: Move a utility function to TimeUtil

- base/src/org/compiere/acct/Doc.java
- base/src/org/compiere/acct/Doc_BankStatement.java
- base/src/org/compiere/acct/Doc_Inventory.java
- base/src/org/compiere/acct/Doc_Movement.java
- base/src/org/compiere/acct/Doc_Production.java
- base/src/org/compiere/acct/Doc_ProductionBatch.java
- base/src/org/compiere/acct/Doc_ProjectIssue.java
- base/src/org/compiere/acct/Doc_Requisition.java
- org.eevolution.manufacturing/src/main/java/base/org/compiere/acct/Doc_DDOrder.java
- org.eevolution.manufacturing/src/main/java/base/org/compiere/acct/Doc_PPCostCollector.java
- org.eevolution.manufacturing/src/main/java/base/org/compiere/acct/Doc_PPOrder.java
- org.eevolution.manufacturing/src/test/java/base/org/compiere/acct/TestDoc.java
The GardenWorldCleanup code needs to know which document columns represent the DateAcct to use when adjusting dates.  Several documents do not use the standard column name DateAcct.  When docs have been added that do not use the standard, the GardenWorldCleanup may not take these dates into account.
This commit reduces model dependencies in GardenWorldCleanup where the code needs to know which columns in the model to use for accounting dates.  This knowledge should be the responsibility of the Doc classes.  Add methods to the Doc class to determine the column name that acts as DateAcct.  Not all documents use the same
column name for this.  The Doc class provides an implementation for the getDateAcctColumnName which child classes can override if required.  Tests for these methods are …
> Issue #3309 - Refactoring part 2: Move knowledge of the Doc classes to the Doc Classes

- base/src/org/compiere/model/MPeriod.java
- base/test/src/org/compiere/model/IT_MPeriod.java
- org.adempiere.test/src/test/java/org/adempiere/test/CommonSystemSetup.java
Required by the GardenWorldCleanup process, these methods provide a way to find the min/max dates in a calendar.
Update MPeriod getC_Calendar_ID method to allow a different client id to be used.  This is necessary when the System account tries to access calendar dates from other clients.  Used in GardenWorldCleanup as the process is run using the system context.
> Issue #3309 - Refactoring part 3: Add methods to MPeriod to find min and max dates in calendar.

- base/src/org/compiere/model/MMenu.java
- migration/393lts-394lts/07670_Add_default_false_for_summary_level_menu.xml
When a menu is flagged as summary level and also is flagged as centrally
maintained, the translation never is applied for him.
This change only ensure the the summary level is not central maintained
Note: please use squash for merge inside trunk
> Set default value for centrally maintained menu

- base/src/org/compiere/model/MPaySelectionCheck.java
When a payment selection is created automatically from Payment (after print) and the payment is created with Zelle or Mobile Payment, the payment rule of payment selection is created as Check instead **Direct Deposit** This pull request just allows create the payment selection with **Direct Deposit** for payments with tender types **Zelle** or **Mobile Payment**
Note: please use squash for merge inside trunk
> Fixed error with tender type for create payment selection from payment

- base/src/org/compiere/process/RoleAccessUpdate.java
- base/src/org/compiere/process/RoleAccessUpdateAbstract.java
- base/test/src/org/compiere/process/RoleAccessUpdate_IT.java
- base/test/src/org/compiere/process/RoleAccessUpdate_Test.java
Fixes #3427
Update RoleAccessUpdate to isolate constructors and static utilities to enable mocking for tests. Clean up the logic and fix the Main method.
In RoleAccessUpdateAbstract, change roleId to a BigDecimal and test for null in the getter.
Add unit and integration tests to show the application across all roles in all clients, all roles in the current client or a single role.
Unit and integration tests are included.
If the role is set, only that role is updated - even for the System Administration role
If the client is set to system, and role is not selected, all roles in all clients are updated
If the client is set other than system and the role is not selected, all roles in the selected client are updated
> Fix RoleAccessUpdate to enable update for all clients and all roles.

- base/src/org/compiere/model/MOrder.java
This error was introduced with a lot of changes merged in the pull
request: https://github.com/adempiere/adempiere/pull/3343
When a Sales Order is created with a line that contain a charge exist a
NPE, this was reported here:
https://github.com/adempiere/adempiere/issues/3266#issuecomment-832186309
Many customers will be affected because any sales orders with charges
don't work
Just validate if exist a product for processed lines
Please use Squash instead merge
Best regards
> Fixed error with wrong validation for Sales Order

- base/src/org/compiere/print/MPrintFormatItem.java
When a print format is created from system and called from a company is
throwed a error NPE:
```Java
Exception in thread "Physical Inventory  IFM-15  ySenih (Compañía
Estándar Admin) @ Compañía Estándar.Organización
[MyAppsServer{192.168.9.63-SEED_TEST-adempiere}]-1032743"
java.lang.NullPointerException
at org.compiere.print.DataEngine.loadPrintData(DataEngine.java:1061)
at org.compiere.print.DataEngine.getPrintData(DataEngine.java:237)
at org.compiere.print.ReportEngine.setPrintData(ReportEngine.java:274)
at org.compiere.print.ReportEngine.setQuery(ReportEngine.java:246)
at org.compiere.print.ReportEngine.<init>(ReportEngine.java:157)
at org.compiere.print.ReportEngine.get(ReportEngine.java:898)
at org.compiere.print.ReportCtl.startStandardReport(ReportCtl.java:225)
at …
```
> Fixed error with NPE for system reports

- base/src/org/adempiere/pipo/handler/PrintFormatElementHandler.java
When a print format is header and line like is **Invoice Header** and the print format is exported as .arxml format. The definition is exported but when is imported in other ADempiere instance the lines are missing.
- Login inside ADempiere
- Print a invoice
- Export format with format arxml
- Delete exported format in ADempiere
- Import the exported format: Note that the lines are missing
The header and lines should be present after import
Note: please use squash for merge inside trunk
> Fixed error with Import ARXML of Print format

- org.eevolution.hr_and_payroll/src/main/java/base/org/compiere/acct/Doc_HRProcess.java
When a **Payroll Process** is processed and is create facts, the account
from concept is created based on Account Schema, payroll of process and
business partner group.
The payroll concept used for search account configuration is based on
line of payroll process but the line just have the payroll defined by
employee for save in historic it.
The payroll used for search account from concept should be the running
payroll instead.
> Fixed wrong search for concept acct

- base/src/org/compiere/model/MOrder.java
- Create a Purchase Order
- Create a Receipt from Purchase Order
- Void the PO
When the PO is voided, the MM Receipt is completed and exist a deadlock
The PR just add a validation for PO when is void for verify if exist a
receipt.
See the message:
Note: when a PO is based on **Warehouse Order** the receipt are
automatically reversed
Please merge it with squash
> Fixed error when a Purchase order is voided

- base/src/org/compiere/model/MRole.java
- base/src/org/compiere/util/DependentRecordAccess.java
When a record is add to record access for exclude and using dependent
entities flag it work fine for windows but not work for reports.
- Login into ADempiere as **GardenAdmin** role
- Go to Role
- Lookup **GardenWorld Admin**
- Set to true the flags: **Personal Lock** and **Personal Access**
- Re-Login
- Login into ADempiere as **GardenAdmin** role
- Go to **Document Type**
- Lookup **POS Order** record
- On Tool Bar press **Ctrl** + **Lock Button**
- On Record Access Dialog:
- Press new record
- Set flag **Exclude** and **Dependent Entities** to true
- Press **Ok** button
- Logout
- Note: If you open **Sales Order** window you can see 5 Orders:
- 3 as **POS Order**
- 1 as **On Credit Orde**
- 1 as **Standard Order**
- Login into ADempiere as **Garden User**
- Go to **Sales Order** …
> Fixed error with Dependent Entities for Record Access

- base/src/org/compiere/model/MInOut.java
- base/src/org/compiere/model/MOrder.java
- base/src/org/compiere/model/MOrderLine.java
Related with #3266
- Remove unnecessary code
- Improvement of the code separating the behavior of calculation of weight and volume of the reservation process.
A good practice is that a function method in the code should be responsible for only one behavior
replace #3452
> Error in calculating quantity ordered or reserved for manufacturing order and distribution order 

- db/ddlutils/oracle/functions/DailySalaryToDateByHrProcess.sql
- db/ddlutils/postgresql/functions/DailySalaryToDateByHrProcess.sql
- migration/393lts-394lts/07680_Add_Function_Daily_Salary_by_HRProcress.xml
Add the database function to get the daily salary, based on the Employee (Business Partner), the payroll process and the date. The function returns the amount of the daily salary payroll concept that is defined in the employee's contract.
> Add the database function to get the daily salary

- base/src/org/spin/process/SetupFileStorageSystem.java
- base/src/org/spin/util/AttachmentUtil.java
- Run Process **Setup File Storage for Files System**
- Select a New File Handler
- Run Process
- Logout
- Login
- Run Process **Setup File Storage for Files System** (For other file
handler)
When the process is running, all files are ignored.
The current file storage is not setted from parameter for reference and
for get stream
> Fixed error with File Storage for process

- migration/393lts-394lts/07830_Add_Specific_Social_Media_Support.xml
- migration/393lts-394lts/07900_Add_Specific_Social_Media_Support.xml
Currently exists only a Application Type named Social Media for
determinate the type of application. Also exists many app supports for
the same **Social Media**.
This pull request create specific application types for all social
media, the improve here is that you can has many implementations for a
social media.
Example: We can have Twitter as Application Type and three implementations for twitter
> Add specific values for Social Media

- org.eevolution.manufacturing/src/main/java/base/org/eevolution/model/MPPForecastDefinitionLine.java
The value of C_BP_Group_ID in the sql where clause is correctly set.
fixes https://github.com/adempiere/adempiere/issues/3492
> fix: BP Group getSQlWhere in Forecast Run Create.

- org.adempiere.request/src/main/java/org/compiere/model/MStandardRequestType.java
- org.adempiere.request/src/main/java/org/compiere/model/RequestModelValidator.java
The model validator only work over swing UI, for ZK never load tables
When the model validator engine is load, the client or tenant is null
and the query for get all setup of Standard Request Type make a
validation for client. It is like if I make a Standar Request Type with
Client **11** and it is loaded as **AD_Client_ID = 0**
- Create a Standard Request Type
- Add Document Action Event
- Add a document type
- Add a Valid from
- Add A template for request
- Logout and login
- Test It.... Is wrong, never is loaded the table criteria
Best regards
> Fixed error with Standard Request Type Model Validator

- base/src/org/compiere/process/M_PriceList_Create.java
When the process "Create Product Price" on Price List Version is runned
using a price list discount schema based on Product PO, the price used
for calculate is the **Price List** instead **Price PO**. This have a
problem because the real price is based on Price PO instead Price List
of Product PO.
> Bad reference for price list create process

- base/src/org/compiere/process/DocumentEngine.java
- serverRoot/src/test/server/org/compiere/acct/IT_DocumentPosting.java
Fixes #3518.
A null trxName is a valid value.
> Remove test that trxName be not null from DocumentEngine.postImmediate

- JasperReports/build.xml
Bugfix to error when executing a report generated in jasper report, the error was introducing #3246
> Fixed missing JasperReport library on build

- base/src/org/adempiere/apps/graph/GraphBuilder.java
- base/src/org/compiere/model/I_AD_Chart.java
- base/src/org/compiere/model/I_PA_Goal.java
- base/src/org/compiere/model/MGoal.java
- base/src/org/compiere/model/X_AD_Chart.java
- base/src/org/compiere/model/X_PA_Goal.java
- client/src/org/adempiere/apps/graph/PAPanel.java
- client/src/org/adempiere/apps/graph/ViewPI.java
- db/ddlutils/oracle/views/RV_C_SALESDASHBOARD.sql
- db/ddlutils/postgresql/views/RV_C_SALESDASHBOARD.sql
- migration/393lts-394lts/07940_Add_support_to_Chart_for_PA_Goal.xml
- zkwebui/WEB-INF/src/org/adempiere/webui/apps/graph/WPAPanel.java
Just add support to charts based on **AD_Chart** table
Is nice this change because can join the current measure with Adaxa
implementation for Charts
See the definition:
> Add chart support for PA Goal

- base/src/org/spin/process/PaymentCreateFromInvoice.java
When the Smart Browser for create payment from Invoices is nice for
generate payments but when is created over a current payment, all values
are overwrited from parameters
> fixed error with create from on current payment

- base/src/org/compiere/model/MInventory.java
https://github.com/adempiere/adempiere/issues/3512
Similar to the other document classes reverse accrual should use the current date.
> Adempiere #3512 reverse accrual uses original movementdate

- serverRoot/src/main/server/org/compiere/server/AcctProcessor.java
- serverRoot/src/test/server/org/compiere/server/AcctProcessor_IT.java
A fix was already provided in  #3537.  This commit adds a default value to the info and includes a test which shows the fix works as expected.
> Fix for #3535 AcctProcessor throws an NPE when first initialized.

- base/src/org/eevolution/model/I_HR_Attribute.java
- base/src/org/eevolution/model/X_HR_Attribute.java
- migration/393lts-394lts/08890_Add_support_to_converted_attributes.xml
- org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/model/MHRMovement.java
- org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/model/MHRProcess.java
This pull request allows define a attribute as converted and it can be
created with other currency distinct of payroll, see a example:
- A concept created as bonus from sales
- The attribute amount is defined as **Converted** with a currency **USD**
- The value is **USD 10**
- A currency rate defined from **USD** to **VES** **1 USD** ~ **3.650.000 VES** and vice versa
- Two payrolls:
- One defined as **USD** ===> Result: **USD** 10
- Other defined as **VES** ===> Result: **VES** 36,650,000.00
> Add support to converted attributes for payroll

- adempiere.iml
In the adempiere.iml file, root source is selected as test source, this PR remove this selection when the project is handled by IntelliJ.
> Fix root source marked as test source in IntelliJ's adempiere.iml

- migration/393lts-394lts/09240_Enlarge_length_for_Description_on_Order_and_Invoice.xml
Increase size of columns:
- `C_Order.Description`
- `C_OrderLine.Description`
- `C_Invoice.Description`
- `C_InvoiceLine.Description`
This allows define a wide description for clients like services where is
used the sales order with specification of contracts
> Enlarge length for Description on Order and Invoice

- client/src/org/spin/apps/form/BankStatementMatchController.java
- client/src/org/spin/apps/form/VBankStatementMatch.java
- zkwebui/WEB-INF/src/org/spin/apps/form/WBankStatementMatch.java
The bank statement movements loaded previously should be imported after
press ok button on **Bank Statement Matcher** form when it is open from
**Bank Statement** window
- Create a new Bank Statement
- Load a Bank Statement Extract from process **Load Bank Statement**
- Open **Bank Statement Matcher** from **Bank Statement** window
- Search the No Matched imported payments
- Press Ok
- The result is nothing
- Note that is almost one payment is matched then all payments are
imported
> Fixed error after press ok on Bank Statement Matcher

- migration/393lts-394lts/09230_Add_new_Currency_for_Venezuela_Bolivar_Digital.xml
From 2021-10-01 the currency VES of Venezuela will be changed to VED
(Temp)
Reference:
http://www.bcv.org.ve/comunicado-bolivar-digital
[comunicado_bolivardigital.pdf](https://github.com/adempiere/adempiere/files/7014834/comunicado_bolivardigital.pdf)
I will to add a new currency for keep the old transactions with VES and
new transaction with VED, the VED currency will be change to VES after
conversion and the old VES currency will be change to VEO
The conversion rate will be 1 VED ≃ 1000000 VES
> Add new currency for Venezuela VED

- base/src/org/spin/queue/notification/DefaultNotifier.java
- migration/393lts-394lts/09260_Remove_Mandatory_Account_Name_of_Notification_Recipient.xml
The current validation verify that exists the user for notification if
the notification type is defined as "User Defined".
The problem is that this validation must be by user of recipient instead
user sender
> change wrong validation for user on notifier

- base/src/org/spin/queue/notification/support/EMailSender.java
Hi @yamelsenih , I see in the EmailSender that when the error is in the address (malformed), the error is not loggined in the ErrorMsg field in AD_NotificationRecipient table.
This PR fix this case and fill the field like this.
> Fix: When the email address is malformed, not log this message

- zkwebui/WEB-INF/src/org/eevolution/grid/WBrowserListItemRenderer.java
On Smart Browse when the summary row is the first row and selected another record, the selected records don't go to process.
- Open an Bank Statement
- Create From Payment
- Sort By Document Number 
- When the summary row be the first row, select a row
> Fixed process selection when summary row is the first row

- client/src/org/compiere/grid/ed/VCellEditor.java
- client/src/org/compiere/grid/ed/VMemo.java
- client/src/org/compiere/grid/ed/VString.java
- client/src/org/compiere/grid/ed/VText.java
Instead of indicating that data is modified only when focus is out of editor, this commit try to mark modification immediately after text in editor is changed.
With this change, user can type <F4> or click Save icon directly to save data after text editing is finished, without having to move focus out of editor.
BTW: I have only tested VString and VText, not sure where VMemo is used, may someone give me a hint?
Before:
After:
> Improve modification indication UX in Swing editor

- base/src/org/compiere/db/DB_MariaDB.java
- base/src/org/compiere/db/DB_MySQL.java
- base/src/org/compiere/db/DB_Oracle.java
- base/src/org/compiere/db/DB_PostgreSQL.java
As mentioned in comments of #3585, c3p0 connection leak workaround is
not needed anymore, as we have changed to use HikariCP instead.
I have only tested in PostgreSQL, may someone who has MariaDB, MySQL and Oracle environments can help to have a check.
> Remove c3p0 connection leak workaround

- base/src/org/compiere/model/GridTab.java
- base/src/org/compiere/model/GridTable.java
- client/src/org/compiere/grid/GridController.java
Fixes #3606
This commit choose another way to fix #421, i.e. instead of updating embedded tabs after sorting, this commit tries to retain selected row after sorting, so no update is needed.
The implementation is ported from iDempiere, with small tweaks.
It works both in Swing and ZK UI.
Code added by #2088 and #2238 have been reverted, as it will cause problem as described in #3606.
> Retain selected row when sorting grid table

- base/test/src/org/compiere/util/TimeUtilTest.java
`TimeUtil.getDay` will get result in locale time zone, so increase test case of `1970-01-01` by one day, to bypass the problem in timezone with positive offset.
To test this, please run following command before and after change:
```
TZ=Asia/Shanghai sh tools/lib/ant/apache-ant-1.10.10/bin/ant
```
> Fix TimeUtilTest in timezone with positive offset

- client/src/org/compiere/grid/GridController.java
Disable default keymaps for F6 and F8 in JSplitPane inside GridController, which conflict with shortcuts of "Lookup Record" and "Grid Toggle" in menu and toolbar.
Steps to reproduce the problem:
1. Login Swing client as GardenUser
2. Open Menu > Project Management > Project
3. Type F6 or F8 in keyboard
Before applying this PR, F6 and F8 will have no effect.
This is port from iDempiere: https://idempiere.atlassian.net/browse/IDEMPIERE-4934
> Disable default keymaps for F6 and F8 in JSplitPane

- base/src/org/adempiere/plaf/PLAFEditorPanel.java
According to document of javax.swing.plaf.metal.MetalLookAndFeel.setCurrentTheme(), a call to SwingUtilities.updateComponentTreeUI() is needed after theme change.
This commit contains two modifications:
1. An asynchronous repaint() may cause problem if some other components are scheduled to repaint before previewPanel, and those components have not been updated by updateComponentTreeUI(). This commit try to call previewPanel.paint() directly to do a synchronized redraw, so that original theme can be restored immediately after preview image is captured.
2. After restoring original theme in previewPanel.paint(), call updateComponentTreeUI() for previewPanel again.
Steps to reproduce:
1. Login Swing client with GardenUser
2. Open Tools > Preference > User Interface Theme, select "Nimbus", …
> Fix NPE when changing themes from Nimbus in Swing

- base/src/org/compiere/plaf/CompiereButtonUI.java
1. Make Compiere button opaque by default, to be consistent with Adempiere theme
2. Only draw 3D effect if Compiere button is opaque
Before:
After:
This PR is port from iDempiere: https://idempiere.atlassian.net/browse/IDEMPIERE-4938
> Improve sidebar UI for Compiere theme in Swing

- org.eevolution.warehouse/src/main/java/base/org/eevolution/model/MWMInOutBound.java
When is called the method getLines(whereClause, orderBy), exists a error because the custom where clause never is  send to query. Instead is used the internal where clause, see the error line:
```Java
if (!Util.isEmpty(where, true))
whereClause.append(whereClause);
```
> fixed error with getLines(String, String) method

- client/src/org/compiere/grid/ed/VMemo.java
- client/src/org/compiere/grid/ed/VText.java
In single-row mode, text input widgets and models behind them have
kind of two-way data bindings, which are established in GridController.
In order to mark data as modified as soon as possible. we currently
update model data more eagerly, as committed in #3592, which will cause
problem, i.e.:
1. user type characters in text widget
2. model got updated because of vetoable change
3. text widget got updated again because of property change
The third step not only adds an unneeded update operation, but also
cause problem if interfered with on-the-spot input methods, which will
make uncommitted characters to be saved in the text fields.
This commit tries to fix this problem by checking that text widgets
only set values triggered by property change in multi-row mode (i.e.
when those text input …
> Fix broken input method in single-row mode in Swing UI

- base/src/org/compiere/plaf/CompiereUtils.java
After merging #3619, heap usage is increased in Compiere theme, which is caused by flat backgrounds drawing using BufferedImage, which use quite a lot of memory.
This commit trying to draw flat background directly without BufferedImage.
Without this PR, Project window will be failed to open in Compiere theme mode (with default `-Xmx256M` option), i.e.:
1. Login ADempiere as GardenUser using Swing client
2. Open Project Management > Project
With step 2, OutOfMemoryError will be occured.
> Reduce heap usage of Compiere theme

- org.eevolution.warehouse/src/main/java/base/org/eevolution/model/MWMInOutBound.java
Currently exists a problem when a express receipt is created with a quantity major of purchase order, this validation already exist for **Match PO**
> Fixed error with receipt based on major quantity of purchase order

- base/src/org/spin/util/AbstractExportFormat.java
This commit remove redundant empty rows in CSV export, to make it consistent with XLSX export.
1. Login ZK-UI with GardenUser
2. Open "System Admin > Organization Rules > Organization"
3. Click "Report" icon
4. Click "Lookup Record" icon and click "Ok"
5. Select "CSV"
> Remove redundant empty rows in CSV export

- base/src/org/compiere/impexp/BankStatementMatcherInterface.java
- base/src/org/compiere/process/BankStatementMatcher.java
- base/src/org/spin/util/impexp/GenericBankMatcher.java
- base/src/org/spin/util/impexp/ReferenceNoLeftLike_BankMatcher.java
- base/src/org/spin/util/impexp/ReferenceNoLikeWithImport_BankMatcher.java
- base/src/org/spin/util/impexp/ReferenceNoLikeWithPayment_BankMatcher.java
- base/src/org/spin/util/impexp/ReferenceNoLike_BankMatcher.java
- base/src/org/spin/util/impexp/ReferenceNoRightLike_BankMatcher.java
- base/src/org/spin/util/impexp/ReferenceNo_BankMatcher.java
- client/src/org/spin/apps/form/BankStatementMatchController.java
Currently not exists a way for know if a payment already exists inside
matched payments when the form for **Match Payments** is used, then each
matcher go to find any payments without know if a payment already exists
as matched with a previous matcher.
- Create three payments with the same amount and currency
- Load a Bank Statement: Enforce it for load four lines, three with the
same amount that the previous payments created and one distinct
- Go to **Bank Statement Match** form
- Simulate a match
- Note that only one payment is matched
Each matcher make a search to db with a criteria and the first run get a
payment. After this run, the second matcher find the same payment that
the previous and is ignored.
> Add Included and Excluded Payments for bank statement

- org.eevolution.warehouse/src/main/java/base/org/eevolution/model/MWMInOutBoundLine.java
- org.eevolution.warehouse/src/main/java/base/org/spin/form/OutBoundOrder.java
- org.eevolution.warehouse/src/main/java/ui/zk/org/spin/form/WOutBoundOrder.java
Currently when a outbound order is generated the uom is not used correctly, also the movement quantity is not the real movement based on available for shipment. This pull request just allows define a correct uom for outboundline based on product.
**Features**
- Add correct UOM for OutBound Order Line
- Add correct movement quantity
- Add support to attribute set instance from Generate Outbound Order form
- Add support to default locator from Generate Outbound Order form
> Fixed error with UOM for OutBound Line

- base/src/org/compiere/model/MTable.java
```Java
Exception in thread "Acme01 - Accounting Processor"
java.util.ConcurrentModificationException
at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1579)
at java.base/java.util.HashMap$ValueIterator.next(HashMap.java:1607)
at org.compiere.model.MTable.get(MTable.java:172)
at org.compiere.model.Query.<init>(Query.java:131)
at org.compiere.model.MTable.getColumnsAsList(MTable.java:473)
at org.compiere.model.MTable.getColumns(MTable.java:451)
at org.compiere.model.MTable.getKeyColumns(MTable.java:517)
at org.compiere.model.Query.getIDsAsList(Query.java:804)
at org.compiere.acct.Doc.streamUnpostedRecordIdsForTableOnDate(Doc.java:301)
at org.compiere.acct.SessionPoster.postDocumentsOnDate(SessionPoster.java:145)
at …
```
> Fixed error with ConcurrentModificationException

- JasperReports/build.xml
- JasperReportsWebApp/build.xml
- client/build.xml
- com.kkalice.adempiere.migrate/build.xml
- extend/build.xml
- install/build.xml
- org.adempiere.asset/build.xml
- org.adempiere.production/build.xml
- org.adempiere.webservice/build.xml
- org.compiere.mobile/build.xml
- org.eevolution.cashflow/build.xml
- org.eevolution.fleet/build.xml
- org.eevolution.freight/build.xml
- org.eevolution.hr_and_payroll/build.xml
- org.eevolution.manufacturing/build.xml
- org.eevolution.warehouse/build.xml
- org.spin.finance_management/build.xml
- org.spin.hr_time_and_attendance/build.xml
- org.spin.loan_management/build.xml
- org.spin.store/build.xml
- serverApps/build.xml
- serverRoot/build.xml
- sqlj/build.xml
- tools/build.xml
- webCM/build.xml
- zkwebui/build.xml
1. Build adempiere.
Build with multiple (31) warning, see output build log:
```log
[javac] /home/user/adempiere/tools/build.xml:70: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
```
[output-error.log](https://github.com/adempiere/adempiere/files/8009397/output-error.log)
[output-fix.log](https://github.com/adempiere/adempiere/files/8009500/output-fix.log)
- Your OS: Linux Mint 20.2 Cinnamon x64.
- Java version: 11.0.13.
- ADempiere version: 3.9.3
- Browser: Mozilla Firefox.
- Browser Version: 96.0.3.
- DB Provider: PostgreSQL.
- DB version: 13.5.
> fix: Build warning 'includeantruntime' was not set.

- base/src/org/compiere/model/MClient.java
The follows are deprecated, you can use the new definition for notification using the queue introduced here: https://github.com/adempiere/adempiere/pull/3536
- `public boolean sendEMail (int AD_User_ID, String subject, String message, File attachment)`
- `public boolean sendEMailAttachments (int AD_User_ID, String subject, String message, Collection<File> attachments)`
- `public boolean sendEMailAttachments (int AD_User_ID, String subject, String message, Collection<File> attachments, boolean html)`
- `public boolean sendEMail (String to, String subject, String message, File attachment)`
- `public boolean sendEMail (String to, String subject, String message, File attachment, boolean html)`
- `public boolean sendEMail (MUser from, MUser to, String subject, String message, File attachment)` …
> Deprecate old methods for send EMail from MClient class

- .classpath
Just add vavr library to eclipse classpath
See: https://docs.vavr.io/
> Fixed error with classpath for vavr

- sqlj/build.xml
1. Build adempiere.
See output build log;
```log
sqljInit:
[echo] =========== Build SQLJ
[mkdir] Created dir: /home/edwin/workspace/glpa/adempiere/sqlj/build
[copy] Warning: Could not find file /home/edwin/workspace/glpa/adempiere/sqlj/postgresql/sqlj.ddr to copy.
```
[output-error.log](https://github.com/adempiere/adempiere/files/8009397/output-error.log)
[output-fix.log](https://github.com/adempiere/adempiere/files/8009398/output-fix.log)
- Your OS: Linux Mint 20.2 Cinnamon x64.
- Java version: 11.0.13.
- ADempiere version: 3.9.3
- Browser: Mozilla Firefox.
- Browser Version: 96.0.3.
- DB Provider: PostgreSQL.
- DB version: 13.5.
> fix: Build Warning Could not find file.

- base/src/org/compiere/model/MOrder.java
Orders cannot be voided, due to erroneous interruption
Class MOrder, line 2035
if(tax.calculateTaxFromLines()) {
return false;
correct code
**if(!tax.calculateTaxFromLines()) {**
return false;
https://github.com/adempiere/adempiere/issues/3782
> adempiere 3782  MOrder voidIt terminated

- org.eevolution.fleet/build.gradle
- org.eevolution.fleet:
- build.gradle
```Shell
gradle build
```
```Java
```
> This pull request just add support to gradle builder to fleet source folder

- org.eevolution.cashflow/build.gradle
- org.eevolution.cashflow:
- build.gradle
```Shell
gradle build
```
```Java
```
> This pull request just add support to gradle builder to cashflow source folder

- org.adempiere.production/build.gradle
- org.adempiere.production:
- build.gradle
```Shell
gradle build
```
```Java
```
> This pull request just add support to gradle builder to production source folder

- org.adempiere.asset/build.gradle
- org.adempiere.asset:
- build.gradle
```Shell
gradle build
```
```Java
// https://mvnrepository.com/artifact/javax.servlet/javax.servlet-api
implementation group: 'javax.servlet', name: 'javax.servlet-api', version: '4.0.1'
// https://mvnrepository.com/artifact/org.apache.commons/commons-collections4
implementation group: 'org.apache.commons', name: 'commons-collections4', version: '4.4'
// https://mvnrepository.com/artifact/com.sun.mail/javax.mail
implementation group: 'com.sun.mail', name: 'javax.mail', version: '1.4.7'
api 'io.github.adempiere:project:3.9.4-develop-1.0'
```
> This pull request just add support to gradle builder to asset source folder

- org.adempiere.project/build.gradle
- org.adempiere.project:
- build.gradle
```Shell
gradle build
```
```Java
```
> This pull request just add support to gradle builder to project source folder

- extend/build.gradle
- extend:
- build.gradle
```Shell
gradle build
```
```Java
```
> This pull request just add support to gradle builder to extend source folder

- base/build.gradle
folder. The gradle structure is the follow:
- base:
- build.gradle
```Shell
gradle build
```
```Java
api 'io.github.adempiere:tools:3.9.4-develop-1.0'
```
Note: now I can't find the follows libraries because are many olds and
exists from other vendor:
- /tools/lib/Verisign.jar
- /tools/lib/payflow.jar
Both libraries are dependences of:
- [org.compiere.model.PP_PayPal.java](https://github.com/adempiere/adempiere/blob/develop/base/src/org/compiere/model/PP_PayPal.java)
- [org.compiere.model.PP_PayFlowPro.java](https://github.com/adempiere/adempiere/blob/develop/base/src/org/compiere/model/PP_PayFlowPro.java)
- [org.compiere.model.PP_PayFlowPro4.java](https://github.com/adempiere/adempier …
> This pull request just add support to gradle builder to base source

- migration/build.gradle
- migration:
- build.gradle
```Shell
gradle build
```
```Java
```
> This pull request just add support to gradle builder to migration source folder

- org.adempiere.request/build.gradle
folder
- org.adempiere.request:
- build.gradle
```Shell
gradle build
```
```Java
// https://mvnrepository.com/artifact/com.sun.mail/javax.mail
implementation group: 'com.sun.mail', name: 'javax.mail', version: '1.4.7'
```
> This pull request just add support to gradle builder to request source

- base/test/src/org/compiere/model/IT_Inventory.java
- base/test/src/org/compiere/model/InventoryUtil.java
- org.adempiere.test/build.gradle
- org.adempiere.test/src/test/java/org/adempiere/test/CSVFactory.java
- org.adempiere.test/src/test/java/org/adempiere/test/MMDocument.java
- org.adempiere.test/src/test/java/org/adempiere/test/MMScenario.java
- org.adempiere.test:
- build.gradle
```Shell
gradle build
```
```Java
implementation fileTree(
dir: '../tools/lib/testing',
include: [
'SuperCSV-with_src-1.52.jar'
]
)
// https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api
api 'org.junit.jupiter:junit-jupiter-api:5.7.0'
// https://mvnrepository.com/artifact/org.mockito/mockito-junit-jupiter
api 'org.mockito:mockito-junit-jupiter:3.6.0'
// https://mvnrepository.com/artifact/org.junit.platform/junit-platform-console-standalone
api 'org.junit.platform:junit-platform-console-standalone:1.7.0'
```
Note that the library …
> This pull request just add support to gradle builder to org.adempiere.test source folder

- base/test/build.gradle
- base/test:
- build.gradle
```Shell
gradle build
```
```Java
api 'io.github.adempiere:adempiere.test:3.9.4-develop-1.0'
// https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api
api 'org.junit.jupiter:junit-jupiter-api:5.7.0'
// https://mvnrepository.com/artifact/commons-lang/commons-lang
api 'commons-lang:commons-lang:2.1'
// https://mvnrepository.com/artifact/io.vavr/vavr
implementation group: 'io.vavr', name: 'vavr', version: '0.10.4'
```
https://repo1.maven.org/maven2/io/github/adempiere/base.test/
> This pull request just add support to gradle builder to base/test source folder

- org.spin.finance_management/build.gradle
- org.spin.finance_management:
- build.gradle
```Shell
gradle build
```
```Java
api 'io.github.adempiere:base:3.9.4-develop-1.1'
```
https://repo1.maven.org/maven2/io/github/adempiere/investment-and-loan/
> This pull request just add support to gradle builder to org.spin.finance_management source folder

- org.spin.hr_time_and_attendance/build.gradle
- org.spin.hr_time_and_attendance/src/main/java/base/org/spin/model/MHRShiftIncidence.java
- org.spin.hr_time_and_attendance:
- build.gradle
```Shell
gradle build
```
```Java
api 'io.github.adempiere:base:3.9.4-develop-1.1'
api 'io.github.adempiere:human-resource-and-payroll:3.9.4-develop-1.0'
```
https://repo1.maven.org/maven2/io/github/adempiere/time-and-attendance/
> This pull request just add support to gradle builder to org.spin.hr_time_and_attendance source folder

- org.spin.loan_management/build.gradle
- org.spin.loan_management:
- build.gradle
```Shell
gradle build
```
```Java
api 'io.github.adempiere:base:3.9.4-develop-1.1'
api 'io.github.adempiere:investment-and-loan:3.9.4-develop-1.0'
```
https://repo1.maven.org/maven2/io/github/adempiere/loan/
> This pull request just add support to gradle builder to org.spin.loan_management source folder

- org.spin.store/build.gradle
- org.spin.store:
- build.gradle
```Shell
gradle build
```
```Java
// https://mvnrepository.com/artifact/org.apache.httpcomponents/httpcore
api 'org.apache.httpcomponents:httpcore:4.4.10'
// https://mvnrepository.com/artifact/org.elasticsearch.client/elasticsearch-rest-high-level-client
api 'org.elasticsearch.client:elasticsearch-rest-high-level-client:7.9.1'
```
https://repo1.maven.org/maven2/io/github/adempiere/store/
> This pull request just add support to gradle builder to org.spin.store source folder

- org.eevolution.freight/build.gradle
- org.eevolution.freight:
- build.gradle
```Shell
gradle build
```
```Java
api 'io.github.adempiere:wms:3.9.4-develop-1.0'
api 'io.github.adempiere:fleet:3.9.4-develop-1.0'
```
https://repo1.maven.org/maven2/io/github/adempiere/freight/
> This pull request just add support to gradle builder to org.eevolution.freight source folder

- base/src/org/compiere/db/DB_MariaDB.java
- base/src/org/compiere/db/DB_MySQL.java
- base/src/org/compiere/db/DB_Oracle.java
- base/src/org/compiere/db/DB_PostgreSQL.java
- base/src/org/compiere/util/Ini.java
Currently exists a enviroment variable added to ADempiere connection pool, the problem is that it jus is setted as OS variable instead of Ini loader like is all ini enviroment of adempiere. This pull request add support to Ini loader and keep the OS enviroment as second option.
The follow error is throwed if not exist the enviroment variable:
```Shell
org.adempiere.exceptions.AdempiereException: The ADEMPIERE_APPS_TYPE environment variable is not set, so it is not possible to initialize the Hikari Connection Pool
at org.compiere.db.DB_PostgreSQL.lambda$getDataSource$1(DB_PostgreSQL.java:639)
at java.base/java.util.Optional.orElseThrow(Optional.java:403)
at org.compiere.db.DB_PostgreSQL.getDataSource(DB_PostgreSQL.java:639)
at org.compiere.db.DB_PostgreSQL.getFromConnectionPool(DB_PostgreSQ …
```
> Add P_ADEMPIERE_APPS_TYPE support to Ini loader

- base/ADempiere-all.launch
Unable to launch the project because the Adempiere class was moved from the org.compiere.Adempiere package to org.adempiere.Adempiere:
`Error: Main method not found in class org.compiere.Adempiere, define main method as follows:\n public static void main(String[] args)\n Otherwise, an Application class will need to be extended JavaFX javafx.application.Application`
https://user-images.githubusercontent.com/20288327/165013373-dd63ab0a-30ae-439e-b682-5255ea097474.mp4
https://user-images.githubusercontent.com/20288327/165013375-73ef22c8-2f8c-438e-8ebf-fb1d8cea821d.mp4
introduced in the PR https://github.com/adempiere/adempiere/pull/3784
> fix: Run ADempiere-All launcher.

- base/src/org/adempiere/util/GenerateModel.java
- base/src/org/adempiere/util/GenerateModelJPA.java
- base/src/org/adempiere/util/ModelClassGenerator.java
- base/src/org/adempiere/util/ModelInterfaceGenerator.java
This pull request just add a validation to generate model class with
correct name:
The previous problem is that if a table like C_Invoice was generated, the model class generated is MCInvoice instead MInvoice (and validating it).
Also allows validate core packages to generate references
> Validate Class Name for document tables

- JasperReports/src/org/compiere/report/JasperViewer.java
- base/src/org/adempiere/pipo/handler/DataElementHandler.java
- base/src/org/compiere/model/MIssue.java
- base/src/org/compiere/model/MLookupCache.java
- client/src/org/compiere/grid/ed/VButton.java
- org.adempiere.webservice/WEB-INF/src/com/_3e/ADInterface/ADServiceImpl.java
- org.adempiere.webservice/WEB-INF/src/com/_3e/ADInterface/Process.java
- org.adempiere.webservice/WEB-INF/src/net/sf/compilo/data/CompiereDataSourceFactory.java
- org.adempiere.webservice/WEB-INF/src/net/sf/compilo/data/DBDataSource.java
- org.adempiere.webservice/WEB-INF/src/net/sf/compilo/data/ReportViewDataSource.java
- org.adempiere.webservice/WEB-INF/src/net/sf/compilo/report/ReportInfo.java
- org.adempiere.webservice/WEB-INF/src/net/sf/compilo/report/ReportPool.java
- org.adempiere.webservice/WEB-INF/src/net/sf/compilo/report/ReportProcessor.java
- org.adempiere.webservice/WEB-INF/src/net/sf/jasperreports/engine/util/JRQueryExecuter.java
- org.eevolution.manufacturing/src/main/java/ui/swing/org/eevolution/form/bom/BOMMessenger.java
- org.eevolution.manufacturing/src/main/java/ui/swing/org/eevolution/form/bom/BOMTreeCellRenderer.java
- org.eevolution.manufacturing/src/main/java/ui/swing/org/eevolution/form/bom/BOMTreeFactory.java
- org.eevolution.manufacturing/src/main/java/ui/swing/org/eevolution/form/bom/BOMTreeModel.java
- org.eevolution.manufacturing/src/main/java/ui/swing/org/eevolution/form/tree/CachableTreeCellRenderer.java
Currently there are multiple (66) warning messages concerning the hashmap is a raw type:
`HashMap is a raw type. References to generic type HashMap<K,V> should be parameterized`
> fix: Clean warning HashMap should be parameterized

- client/src/org/compiere/apps/ProcessController.java
This pull request just prevent a NPE when the `openResult` method is called without records.
The openResult feature was added by me here #1854
> Prevent NPE when openResult is called

- base/src/org/compiere/model/CalloutEngine.java
Currently the `rate` method of CalloutEngine have a rounding mode to half up, this pull request just add a decimal 128 of digits because a rounding can be little explicit if you use it on conversion rates and others functionalities with many difference.
This error affect to countries with many difference between two currency, example:
USD **1** ~ VES **4,500,000.239**
With a conversion from USD to VES
> Just change rounding up to decimal 128

- base/src/org/compiere/process/ProcessInfo.java
A minor change that allows define the PDF file reference to `pdfReportFile` of Process Info when the `reportAsFile` object have a file with .pdf extension
> Add support to default PDF to Process Info

- base/src/org/eevolution/service/dsl/ProcessBuilder.java
Just add a minimal change to add table selection support on process builder
Now you can use two methods to set selection
```Java
public ProcessBuilder withSelectedRecordsIds(int tableSelectionId, List<Integer> selectedRecordsIds);
public ProcessBuilder withSelectedRecordsIds(int tableSelectionId, String aliasTableSelection, List<Integer> selectedRecordsIds);
```
> Add a new method to set table selection Process Builder

- base/src/org/compiere/model/MDocBaseType.java
- base/src/org/compiere/model/MDocType.java
- Get document base type record with transaction name
- Prevents NPE at validate Document Type if Defined Document Base Type don't exists.
> Add support to get document base type with transaction name

- base/src/org/adempiere/engine/CostingMethodFactory.java
- base/src/org/adempiere/engine/UserDefinedCostingMethodExample.java
- base/src/org/compiere/model/I_M_CostType.java
- base/src/org/compiere/model/X_M_CostType.java
- migration/393lts-394lts/09460_Add_ClassNameForCostType.xml
Currently the Cost Engine class support is load statically, with this change in the cost type could be defined the behavior.
1. Active the User Defined Costing Method for the test.
2. Create a new Costing Type with Costing Method **User Defined** and class name **org.adempiere.engine.UserDefinedCostingMethodExample**
3. Run the **Generate Cost Transaction** process with the next parameters
4. Go to the Product Cost Window, search the **Azalea Bush** product and see cost detail
> Add Support to Cost Engine Dynamic Load

- .classpath
- base/src/org/compiere/model/MDiscountSchema.java
- base/src/org/compiere/model/MDiscountSchemaBreak.java
- migration/393lts-394lts/09470_Add_GardenWorld_Discount_Example.xml
- migration/393lts-394lts/09480_Add_default_value_to_Discount_Schema_Break.xml
This pull request allows define many discounts combinations based on real combination and hierarchy of filters.
Currently the discount schema apply a search based on sequence and it don't have a way for create a combination like **Product** and **Business Partner** directly.
With this change the hierarchy can be defined like the follow:
1. Product
2. Business Partner
3. Product Category
4. Business Partner Group
Now you can define a combination like:
- Product + Business Partner
- Product + Business Partner Group
- Product Category + Business Partner
- Product Category + Business Partner Group
- Product Only
- Product Category Only
- Business Partner Only
- Business Partner Group Only
- Any
It is very useful for retailers customers and is tested with a customer
- Go to window **"Discount …
> Allows define discount based on combinations

- base/src/org/compiere/print/ReportEngine.java
When executing the Shipment Detail report it stays in a never ending execution.
1. Open the Shipment Detail report.
2. Execute without modifying any parameters.
https://user-images.githubusercontent.com/20288327/169670009-da35b881-d23e-42f9-8232-dab3b5b81827.mp4
https://user-images.githubusercontent.com/20288327/169670003-63321805-8c35-4a65-a9b9-b3ef5dd8aa35.mp4
fix: https://github.com/adempiere/adempiere/issues/3884
> fix: #3884 Generate report Null Pointer Exception.

- migration/393lts-394lts/09700_ConversionRate_Selection_Columns.xml
They are added as selection columns:
* Currency.
* Currency To.
* Conversion Type.
* Valid From.
* Valid To.
* Divide Rate.
* Multiply Rate.
In order to be able to perform a simple search for records, since the option currently available is the advanced search and although it may be more accurate, it is not the most practical.
Before these changes:
https://user-images.githubusercontent.com/20288327/172081103-75e77171-b185-4e62-a70c-c7c4362fa79b.mp4
After these changes:
https://user-images.githubusercontent.com/20288327/172081100-a52a158b-1561-4542-8488-5a725f7c400a.mp4
Additionally, the `Currency To` field is marked as the same line, to have the same visual consistency of the `Conversion Rate` tab in the `Currency` window (left) as in the `Conversion Rate` window (right).
Before this …
> feat: Add selection columns in Conversion Rate.

- migration/393lts-394lts/09710_Smart_Browse_Selection_Columns.xml
In order to be able to perform a simple search for records, since the option currently available is the advanced search and although it may be more accurate, it is not the most practical.
They are added as selection columns in the `Smart Browse` window:
* `Smart Browse` tab:
* Search Key.
* Name.
* View.
* Process.
* Window.
* Table.
* `Smart Browse Field` tab:
* Name.
* Description.
* View Column,
* System Element.
1. Login witth `System` role.
2. Open `Smart Browse` window.
3. Lookup record.
https://user-images.githubusercontent.com/20288327/172094957-238dd389-86e7-475b-9a6f-3db65639d306.mp4
> feat: Add selection columns in smart browse.

- org.eevolution.hr_and_payroll/src/main/java/base/org/compiere/acct/Doc_HRProcess.java
https://github.com/adempiere/adempiere/issues/3914
Working with different accounting schemas the search for the corresponding register hr_Concept_acct does not work correctly.
> adempiere #3914Doc_HRProcess, wrong concept accounting for 2 Accounting Schemas

- JasperReports/src/org/compiere/report/ReportStarter.java
Currently the jasper reports are not previewed in the swing user interface, they do not generate any error/warning in the log or in the IDE console, however they work correctly in the Zk user interface.
1. Apply `test_jasper_report.xml` migration.
2. Attach `test.jasper` file on report definition.
3. Run `Test` report.
https://user-images.githubusercontent.com/20288327/175871966-a5b614f9-1c2f-49de-b86e-899bd5cf8adc.mp4
https://user-images.githubusercontent.com/20288327/175871965-61d1db07-0ded-4248-9b54-20917968d628.mp4
XML migration for Test report application dictionary and jasper report source for attachments:
[test-jasper-report.zip](https://github.com/adempiere/adempiere/files/8989134/test-jasper-report.zip)
> fix: Preview JasperReports on swing client.

- zkwebui/WEB-INF/src/org/adempiere/webui/dashboard/DPFavourites.java
Fixes: https://github.com/adempiere/adempiere/issues/3580
Now the user favorites panel can be filled via Drag/Drop:
Special thanks and credits go to @bma-robco who gave the hint to this solution.
> Correction of Favorites(User) Drag&Drop

- build.xml
Fixes https://github.com/adempiere/adempiere/issues/3932
The test would consist of checking out the Action log of _ADempiere Build_ started by this pull request and verifying there that the database is imported only once.
Besides, all other steps (except the installation, which generates a **BUILD FAILED**) should run correctly and the artifacts are generated.
> Skip executing RUN_DBRestore to avoid importing seed twice

- .github/workflows/main.yml
Fixes https://github.com/adempiere/adempiere/issues/3931
Solves `BUILD FAILED` Error running Github Action _ADempiere Build_ (file: _main.yaml_).
The test would consist of checking out the Action log of _ADempiere Build_ started by this pull request and verifying there that the error `BUILD FAILED` disappears.
Besides, all other steps should run correctly and the artifacts should be generated.
> Solve "BUILD FAILED" Error running Github Action "ADempiere Build"

- base/src/org/compiere/model/POInfo.java
In the same execution, in some cases it takes the base language and in others it doesn't, and since the sql is cached, it throws an sql syntax error because there is a SELECT reference to the cached translation table that in the FROM doesn't this.
Since the getPOInfoColumnList method is called only from one place and since it does not use cache from there, for consistency this line is left uncached.
Fix #3968
> Fix #3968 - POInfo cached sql sintax error

- .github/workflows/main.yml
Fixes #4006
This pull request makes sure that the GitHub Action generating the seed runs on Ubuntu 22.04 and Postgres 14.5, thus avoiding the bug described in #4006.
The newest Postgres version is as of now 15.0, but it runs only on a Debian image (_bullseye-slim_), which is not possible to instantiate on GitHub Actions because GitHub Actions runners run only on Ubuntu.
This means that although Adempiere may run n Postgres 15.0, the CI/CD test is done on Postgres 14.5.
The correctness of the modifications was tested with the following pull request: https://github.aom/adempiere/adempiere/pull/4007. See the results of GitHub Actions there: https://github.com/adempiere/adempiere/actions/runs/3388914703/jobs/5631431907 .
Image:
This pull request will not generate a seed; this is why the pull …
> GitHub Actions: Artifact "adempiere-postgresql-seed" generated with 0 Bytes

- .github/workflows/main.yml
Fixes #4010
As this is a pull request concerning GitHub Actions, the result of the Actions has to first be tested, before it is eligible for others to accept.
Use Node.js 16 compatible actions.
The errors according to GitHub:
```
Please update the following actions to use Node.js 16: 
actions/checkout, 
actions/setup-java, 
actions/upload-artifact, 
actions/setup-java, 
actions/checkout
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. 
For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
Looking at the GitHub Actions repository, the recommendations are as follows:
https://github.com/actions/setup-java
- uses: actions/setup-java@v3 …
> GitHub Actions: Annotations Displayed on GitHub Actions Execution

- .github/workflows/issue-and-pr-translator.yml
Solves #4138
@e-Evolution  Victor, @yamelsenih Yamel: either of you can accept this PR.
Unluckily, being this Pull Request a GitHub Action, this Pull Request can only be tested **after** the Pull Request has been accepted by creating for example a comment to a Discussion in Spanish; it should be translated as it happens now to issues and pull requests.
So, the acceptance has to be done "blindly" and if everything goes well, OK.
Otherwise, the Pull Request has to be reverted; then find the reason for the PR not functioning, fixing it and creating a new PR.
> Add translation for Discussions in GitHub

- base/src/org/compiere/model/MPriceListVersion.java
- base/test/src/org/compiere/model/UT_MPriceListVersion.java
When using the `getProductPrice` method of the `MPriceListVersion` class:
https://github.com/adempiere/adempiere/blob/0070473977179e538835f46b9b486084307a5d30/base/src/org/compiere/model/MPriceListVersion.java#L116-L127
And passing a where clause that does not start with spaces, for example `AND 1=1` or any other filter:
```sql
AND EXISTS (
SELECT 1 FROM C_OrderLine ol ol
WHERE ol.C_Order_ID = 1000035 AND ol.M_Product_ID = M_ProductPrice.M_Product_ID
)
```
it generates an error:
``` log
org.postgresql.util.PSQLException: ERROR: trailing junk after parameter at or near "$1A"
Position: 215, SQL=SELECT AD_Client_ID,AD_Org_ID,Created,CreatedBy,IsActive,M_PriceList_Version_ID,M_ProductPrice_ID,M_Product_ID,PriceLimit,PriceList,PriceStd,UUID,Updated,UpdatedBy FROM M_ProductPrice WHERE …
```
> fix: getProductPrice with where clause.

- migration/394lts-395lts/09930_Fix_Read_Only_Logic_in_AD_ClientInfo_table_columns.xml
There are several columns in the `AD_ClientInfo` table whose read-only logics have the `@` at the beginning of the column but not at the end, however the adempiere evaluator does not generate an error when evaluating the logics with this incorrect format, considering that only the `@SQL=` logics should have this format.
In all the logic the value is `@AD_Client_ID=0` when it should be `@AD_Client_ID@=0` (with opening and closing `@` in the column name)
The following query can be performed to search with regular expression (used with postgres):
```sql
SELECT
AD_Column_ID, ColumnName, ReadOnlyLogic, MandatoryLogic, DefaultValue, AD_Table_ID
FROM AD_Column
WHERE 
ReadOnlyLogic ~ '@(#|$){0,1}\w+(<>|<=|==|>=|!=|<|=|>|!|\^|~)'
OR MandatoryLogic ~ '@(#|$){0,1}\w(<>|<=|==|>=|!=|<|=|>|!|\^|~)'
OR …
```
> fix: Read Only Logic in `AD_ClientInfo` table columns.

- base/src/org/compiere/impexp/ImpFormat.java
- base/test/src/org/compiere/impexp/UT_ImFormat.java
When the `ImpFormat.load(int id)` method is used, it generates a sql exception, because the parameter receives an integer but in the SQL query it tries to compare with the column `Name` whose data type is string, when it should be compared to the `AD_ImpFormat_ID` column.
```log
===========> ImpFormat.load: SELECT * FROM AD_ImpFormat WHERE Name=? [20]
org.postgresql.util.PSQLException: ERROR: operator does not exist: character varying = integer
Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
Position: 38; State=42883; ErrorCode=0
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
at …
```
> fix: `ImpFormat` load by identifier.

- base/src/org/compiere/process/RfQCreatePO.java
- base/src/org/compiere/process/RfQCreatePOAbstract.java
Currently exists a document type as parameter when a Purchase Order is
created from a Request for Quotation but it is unused inside process.
> RFQ Create PO Fixed error with unused parameter

- base/src/org/compiere/model/MAllocationLine.java
> Cash payment does not remove check from "Assigned" when unassigned

- tools/build.gradle
Just add the file `ecs.properties` is missing after publish packages, this throw a error when you try run a report with html format
The error is showed in terminal like this:
```Shell
java.lang.NoClassDefFoundError: Could not initialize class
org.adempiere.legacy.apache.ecs.ECSDefaults
Cannot find org.adempiere.legacy.apache.ecs.ecs.properties.
```
> Fixed error with missing property file for apache ecs packages

- base/src/org/compiere/model/CalloutGLJournal.java
```
The field BigDecimal.ROUND_HALF_UP is deprecated since version 9
```
> fix: Remove deprecated warning with `BigDecimal.ROUND`.

- base/src/org/compiere/process/RequisitionPOCreate.java
- base/src/org/compiere/process/RequisitionPOCreateAbstract.java
- base/src/org/eevolution/process/CreatePOFromRequisitionLines.java
- migration/394lts-395lts/10320_Add_Document_Type_for_Requisition_PO_Create.xml
When a Purchase order is generated from a requisition using the smart browser `Requisition-to-Invoice` -> `Browser Requisition to Create PO from Requisition Lines`, the document type selected is setted but the sequence is wrong.
The smart browser never send the document type to process and the standard process for generate Purchases don't have support to document type.
This pull request add a new parameter to process `Requisition-to-Invoice` -> `Create PO from Requisition` to add support to document type.
- Create a new Requisition
- Go to Smart Browser `Requisition-to-Invoice` -> `Browser Requisition to Create PO from Requisition Lines`
- Select a Document Type distinct to default document type of PO
- Process it
Note that after process, the document type inside order is the selected but …
> Fixed error with wrong sequence for Purchase Order

- JasperReports/src/org/compiere/jr/report/ReportStarter.java
- base/src/org/adempiere/util/ProcessUtil.java
- base/src/org/compiere/print/ReportViewerProvider.java
- client/src/org/adempiere/Adempiere.java
- org.adempiere.webservice/WEB-INF/src/net/sf/compilo/report/ReportProcessor.java
- Fix NPE Jasper Report.
- Remove deprecated `JRPrintServiceExporter.setParameter`.
- Change deprecated `class.newInstance()` to `class.getDeclaredConstructor().newInstance()`.
- Move `ReportViewerProvider` class from `client/src/org/compiere/print` to `base/src/org/compiere/print`
https://github.com/adempiere/adempiere/assets/20288327/c43cdbbc-223c-45be-a183-1a7e06c74262
fixes https://github.com/adempiere/adempiere/issues/4174
> fix: #4174 NPE with preview Jasper Report on `Swing` UI.

- migration/394lts-395lts/09910_Rename_payroll_packages.xml
The `VHRActionNotice` have a wrong package name from ADempiere dictionary. Also, the Payroll Process Report have a wrong package name.
Wrong packages:
- `org.eevolution.form.VHRActionNotice`
- `org.spin.process.PayrollProcessReport`
Right packages:
- `org.eevolution.hr.form.VHRActionNotice`
- `org.spin.pr.process.PayrollProcessReport`
> Fixed error with package names for payroll

- base/src/org/compiere/model/MQuery.java
- client/src/org/compiere/apps/search/Info.java
- client/src/org/compiere/apps/search/InvoiceHistory.java
- client/src/org/compiere/minigrid/MiniTable.java
- client/src/org/compiere/report/core/RModelData.java
- org.adempiere.pos/src/main/java/ui/zk/org/adempiere/pos/WPOSTable.java
- org.adempiere.webservice/WEB-INF/src/net/sf/compilo/data/DBDataSource.java
- org.eevolution.manufacturing/src/main/java/base/org/eevolution/manufacturing/engine/forecast/MovingAverage.java
- org.eevolution.manufacturing/src/main/java/ui/swing/org/eevolution/form/VMRPDetailed.java
- org.eevolution.manufacturing/src/main/java/ui/swing/org/eevolution/form/VOrderPlanning.java
- zkwebui/WEB-INF/src/org/adempiere/webui/component/WListbox.java
- zkwebui/WEB-INF/src/org/adempiere/webui/panel/InfoPanel.java
- zkwebui/WEB-INF/src/org/adempiere/webui/panel/InvoiceHistory.java
```
The constructor Double(double) is deprecated since version 9
```
> fix: Remove deprecated warning with `new Double` constructor. 

- org.compiere.mobile/WEB-INF/src/org/compiere/mobile/MobileSessionCtx.java
- org.compiere.mobile/WEB-INF/src/org/compiere/mobile/WReport.java
- org.compiere.mobile/WEB-INF/src/org/compiere/mobile/WWindow.java
- org.compiere.mobile/WEB-INF/src/org/compiere/mobile/WWorkflow.java
`The constructor Integer(int) is deprecated since version 9`
> fix: Remove deprecated warning with `new Integer` constructor.

- base/src/org/compiere/print/layout/TableElement.java
- org.adempiere.webservice/WEB-INF/src/net/sf/compilo/data/DBDataSource.java
`The constructor Float(double) is deprecated since version 9`
`The constructor Float(float) is deprecated since version 9`
> fix: Remove deprecated warning with `new Float` constructor.

- client/src/org/compiere/apps/AppsAction.java
- zkwebui/WEB-INF/src/org/adempiere/webui/component/WAppsAction.java
`The constructor Character(char) is deprecated since version 9`
> fix: Remove deprecated warning with `new Character` constructor.

- base/src/org/spin/model/MADContextInfo.java
- org.adempiere.pos/src/main/java/ui/zk/org/adempiere/pos/WPOSActionPanel.java
- org.adempiere.webservice/WEB-INF/src/net/sf/compilo/data/DBDataSource.java
- org.eevolution.manufacturing/src/main/java/base/org/eevolution/manufacturing/process/CRPSummary.java
- org.eevolution.manufacturing/src/main/java/ui/swing/org/eevolution/form/CRP.java
- serverRoot/src/main/servlet/org/compiere/web/AdempiereMonitorFilter.java
- webCM/src/main/servlet/org/compiere/cm/cache/CO.java
- zkwebui/WEB-INF/src/org/adempiere/webui/window/WMediaDialog.java
`The constructor Long(long) is deprecated since version 9`
`The constructor Long(String) is deprecated since version 9`
> fix: Remove deprecated warning with `new Long` constructor.

- client/src/org/compiere/print/SwingViewerProvider.java
- client/src/org/compiere/print/Viewer.java
- org.eevolution.manufacturing/src/main/java/ui/swing/org/eevolution/form/VOrderDistributionReceipt.java
- org.eevolution.manufacturing/src/main/java/ui/swing/org/eevolution/form/VPrintDocument.java
```
The constructor Viewer(ReportEngine) is deprecated.
```
> fix: Remove warning `The constructor Viewer(ReportEngine) is deprecated`.

- client/src/de/schaeffer/compiere/tools/DocumentSearch.java
- client/src/org/compiere/apps/AEnv.java
- client/src/org/compiere/apps/AWindow.java
- client/src/org/compiere/apps/AZoomAcross.java
- client/src/org/compiere/apps/form/VTrxMaterial.java
- client/src/org/compiere/apps/search/Info.java
- client/src/org/compiere/apps/wf/WFActivity.java
- client/src/org/compiere/apps/wf/WFPanel.java
- client/src/org/compiere/grid/ed/VLocator.java
- client/src/org/compiere/grid/ed/VPAttributeDialog.java
- client/src/org/compiere/print/SwingViewerProvider.java
- org.eevolution.manufacturing/src/main/java/ui/swing/org/eevolution/form/VMRPDetailed.java
- org.eevolution.manufacturing/src/main/java/ui/swing/org/eevolution/form/action/ZoomMenuAction.java
```
The constructor AWindow() is deprecated
```
> fix: Remove warning `The constructor AWindow() is deprecated`.

- base/src/org/compiere/util/DB.java
- org.adempiere.webservice/WEB-INF/src/com/_3e/ADInterface/ADLookup.java
- org.adempiere.webservice/WEB-INF/src/com/_3e/ADInterface/Process.java
- org.adempiere.webservice/WEB-INF/src/net/sf/compilo/report/ReportInfo.java
- org.compiere.mobile/WEB-INF/src/org/compiere/mobile/WWorkflow.java
- serverApps/src/main/servlet/org/compiere/www/WWorkflow.java
```log
The method prepareStatement(String, int, int) from the type DB is deprecated
```
```log
The method prepareStatement(String) from the type DB is deprecated
```
> fix: Remove deprecated warning with `DB.prepareStatement` method.

- client/src/org/compiere/apps/AArchive.java
- client/src/org/compiere/apps/AMenuStartItem.java
- client/src/org/compiere/apps/form/FormFrame.java
- client/src/org/compiere/apps/form/VAttributeGrid.java
- client/src/org/compiere/apps/form/VPaySelect.java
- client/src/org/compiere/apps/wf/WFActivity.java
- org.adempiere.pos/src/main/java/ui/swing/org/adempiere/pos/POSApplication.java
`The constructor FormFrame() is deprecated`
`The constructor FormFrame(GraphicsConfiguration) is deprecated`
> fix: Remove warning `The constructor FormFrame() is deprecated`.

- migration/394lts-3.9.4.001/09970_Fix_Production_Line_constraint.xml
Currently if you want to reverse a production, this throw a error trying validate the production line with a in out.
A previos report for this was posted [here](https://github.com/adempiere/adempiere/pull/4081#issuecomment-1817709361)
- Create a new Production
- Complete this
- Try reverse it
> Fixed error with bad constraint for `M_ProductionLine.ReversalLine_ID`

- migration/394lts-395lts/09990_Fix_Lenght_for_Employee_Validation_Code.xml
The column `HR_Employee.Code` has a size of `255` but the real size from database is `1`. If you want save a record with a code like `E5454` he database throw a error.
`\d+ HR_Employee`
Table "adempiere.hr_employee"
Column | Type | Collation | Nullable | Default | Storage | Stats target | Description
-- | -- | -- | -- | -- | -- | -- | --
code | character varying(1) |   |   |   | extended |   |  
> Fixed error with size of `HR_Employee.Code`

- base/build.xml
- base/src/org/compiere/model/MProduction.java
Import `MPPProductBOMLine` class on `MProduction`.
```log
[javac] /home/runner/work/adempiere/adempiere/base/src/org/compiere/model/MProduction.java:47: error: package org.eevolution.manufacturing.model does not exist
[javac] import org.eevolution.manufacturing.model.MPPProductBOMLine;
```
Package `com.amazonaws.auth` does not exist
```log
[javac] /home/runner/work/adempiere/adempiere/base/src/org/spin/util/support/aws3/AmazonWS3.java:33: error: package com.amazonaws.auth does not exist
[javac] import com.amazonaws.auth.AWSStaticCredentialsProvider;
```
After
https://github.com/EdwinBetanc0urt/adempiere/actions/runs/6981717832
Import `MPPProductBOMLine` class on `MProduction`.
```log
/home/runner/work/adempiere/adempiere/base/src/org/compiere/model/MProduction.java:47: error: package …
```
> fix: CI with `MPPProductBOMLine` import, and `com.amazonaws` package ant build. 

- base/src/org/compiere/model/MChartDatasource.java
https://github.com/adempiere/adempiere/assets/20288327/984b4d5e-3dce-4341-b195-67a722ab2edd
https://github.com/adempiere/adempiere/assets/20288327/4abb7ba5-93a5-4ed1-9a1d-d374893a6fa0
fixes https://github.com/adempiere/adempiere/issues/4183
Additionally:
- `period` variable is evaluated by `NPE` potential.
- Changed the visibility of the `formatDate` and `convertToQuarter` methods to public and static since they are not used inside the class.
> fix: #4183 Chartdatasource and table without keys.

- base/src/org/compiere/print/ReportEngine.java
The problem only affect to reports inside windows using button **Print Preview** for non standard reports.
- Go to **Open Items** -> **Payment Selection** window
- Print Report inside window
- Note that the report show all records
The Print format must be flagged as `Form` and must has **Header** and **Content** bands
The problem is that a `OR` operator was add [here](https://github.com/EdwinBetanc0urt/adempiere/commit/5d58da08e190e7f4074dc9618f8bb4b32eb15561#diff-e6e4fea8b4088210a4e30432da4d3b4ebee36723ece363e4d96572d119ca5c7eR874) instead a compose `AND` operator.
Note: This behavior not apply for legacy formats like Invoice, Orders, Shipments and other old hardcoded formats
https://github.com/adempiere/adempiere/assets/2333092/4c03a5a1-0cde-4305-b00b-df8fbf5c3dfa
A example of multiple …
> Fixed error with many executions for report flagged as `IsForm` inside

- db/ddlutils/oracle/views/RV_COMMISSIONRUNDETAIL.sql
- db/ddlutils/postgresql/views/RV_COMMISSIONRUNDETAIL.sql
- migration/394lts-3.9.4.002/10330_Fixed_Commission_Run_Detail_View.xml
For this error you should create:
- Two commission definitions
Name | Commission Group | Calculation Basis | Frequency Type | Currency | List Details | Days due from Payment Term | Commission only specified Orders | Is Percentage | Multiplier Amount
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
Commission 1 | Test Commision Group | Invoice | Monthly | USD | Yes | No | Yes | Yes | 7
Commission 2 | Test Commision Group | Invoice | Monthly | USD | Yes | No | Yes | Yes | 3
- One commission group
Value | Name
-- | --
TCG | Test Commision Group
After it you should create two commision run:
Document No | Commission | Commission Group
-- | -- | --
TC-1 | Commission 1 |  
TC-2 |   | Test Commision Group
Now just run the **Quote-to-Invoice** -> **Sales and Marketing** -> **Commission Run Detail** …
> Fixed error with commission run detail report
